### ISSUE TITLE
setHue does not work for Groups

### ISSUE THREAD

**Issue by dgburton** [ebaauw/homebridge-hue#1]
Thanks for your work on this plugin!

I'm trying to use it to control Groups (as I've got quite a few Hue bulbs I breach the 100-devices per bridge Homekit limit if I add each bulb individually).

Everything seems to work fine apart from setting the Hue of the Group. Whenever I set the Hue either via a Scene or recalling a favourite color (using the iOS10 Home app) it fails. Dragging around the colour wheel does seem to work fine.

![image](https://cloud.githubusercontent.com/assets/6538860/19618815/a9a4a184-984c-11e6-9cd9-15a2c50b03d6.png)

**Comment by dgburton** [comment]
Think it might be something todo with these multiple PUT's for Hue and Sat both using different XY co-ords...

![image](https://cloud.githubusercontent.com/assets/6538860/19618847/b3e48456-984d-11e6-96bf-ed6b3b9f2f5f.png)

**Comment by dgburton** [comment]
I can work around it by moving the updating of the local hk.hue and hk.sat values to before the PUT request, like this.

Not very elegant but seems to work!

![image](https://cloud.githubusercontent.com/assets/6538860/19618885/bf0ed902-984e-11e6-956e-e4072619ea66.png)

**Comment by ebaauw** [comment]
Thanks for your comments!

This looks like an asynchronous execution timing issue: the this.bridge.request callback in setHue comes in after setSat is fired from homekit so setSat computes xy using the old homekit hue value.   Recalling a scene or setting a favourite colour probably changes the homekit saturation quicker after changing the hue than the colour wheel does. Group commands to the hue bridge are like 10x more expensive than light commands, so the callback comes later.

Indeed, the structural solution would be to collect the hue and sat changes into one bridge update (and one computation of xy).

Not sure about the (lack of) elegance of your workaround, though. As the homekit value has changed, it seems correct to update homebridge-hue's cache of the homekit state, regardless whether updating the Hue bridge state succeeds or not.

**Comment by dgburton** [comment]
Thanks @ebaauw :-)

**Comment by ebaauw** [comment]
_"If You're Not Embarrassed By The First Version Of Your Product, You’ve Launched Too Late"_

I've been struggling with the homebridge-hue plug-in logic dealing with homekit values vs hue bridge values and how to update these.  Just putting down some notes, mainly to myself.

**The main logic**
- A change to a homekit characteristic value emits  a `set` event, which fires `setValue()`, which computes the hue bridge value and calls `bridge.request()`.
- A change to a bridge value is detected by heartbeat() comparing the latest bridge state with the previous.  It then computes the homekit value and calls `setCharacteristic()`
- Of course `setCharacteristic()` causes `setValue()` to be fired. To prevent the bridge value to be updated again, `setValue()` checks whether the homekit value has actually changed.

**The issue**
The conversion from homekit value to hue bridge value back to homekit value might yield a different homekit value, due to rounding errors. So `setValue()` needs to compare the new value to the homekit value computed from the new bridge value, rather than from the previous homekit value.  This is implemented in `HueSensor.js` and `HueSchedule.js`: in the `bridge.request()` callback, the cached bridge state is updated, and `refresh()` is called to update the cached homekit values.  It should have been implemented like this for lights (and groups) in `setOn()`, `setBri()`, and `setCT()`.

**Colours**

**Comment by ebaauw** [comment]
@dgburton : I just pushed version 0.0.7 to npm, which, I hope, solved this issue.

**Comment by dgburton** [comment]
Thank you!
