### ISSUE TITLE
Reinstall deconz without change in homebridge-hue & HomeKit

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#1010]
Hello @ebaauw 

I need your help. Since I have some problems currently with my deconz I intend a complete reinstallation of this bridge.

Since I don't want HomeKit to know that I have reinstalled this bridge in the background, my question to you would be what do I have to adjust in the new ZLL database so that homebridge-hue does not recognize any change or how does homebridge-hue recognize that it is a new bridge?

The Zigbee devices get the same names. 
But that should not be enough or?

Or is that perhaps not possible at all? 😅

Thank you!

**Comment by ebaauw** [comment]
Homebridge Hue identifies Zigbee devices by their mac address and creates the HomeKit UUID from that.  That means you can move Zigbee devices between Zigbee gateways / bridges without impact to HomeKit, as long as they’re exposed by the same Homebridge Hue instance.

Non-Zigbee resources (CLIP sensors, groups, scenes) are identified by the resource ID, which will likely change with re-installation.  For CLIP sensors, you can patch the database table.  Groups and scenes are more tricky, since, unlike the Hue bridge, deCONZ bases their resource IDs on the Zigbee IDs.  If you’re lucky they will be read from the lights, causing deCONZ to re-create these using the same resources.

**Comment by Nastras** [comment]
Good morning,
thank you for your quick help and sorry for the delayed reply from me. 

I just want to tell you that all devices have been taken over again except for two pieces.
Since I have not created any scenes or groups, etc., they were not affected.

In summary, the move worked very well!
Thank you and have a nice day!
