### ISSUE TITLE
GLEDOPTO controller dimming off in scene

### ISSUE THREAD

**Issue by CypressGTX** [ebaauw/homebridge-hue#1015]
Hi!

I hope you can help me,

- What is the problem?
I have a GLEDOPTO controller, connected to the Hue Bridge and ported via HomeBridge to HomeKIt of course.
When I turn the GLEDOPTO controller manually on in the Homekit app, everything works fine.
When I run a scene "living room on" in the Homekit app all lights will be on, but the led strip (gledopto controller) is turning on and directly dimming off.

Here is a video what happens: https://share.icloud.com/photos/0m15EuYzOf929GBdiTFNLFE5A#Oss

- What i've tried?
#Delete the GLEDOPTO from the Hue Bridge, Homebrdige, HomeKit and add them again, but it had no effect.
#Create new scene in HomeKit
#Change to another brightness and color in the scene

GLEDOPTOP GL-C-007
FW 2.0.1

Thank you sir!

(tonight i will upload the 2 log files from Homebridge and the Hue Plugin)

**Comment by ebaauw** [comment]
From what I can see in the video, HomeKit continues to show the strip as on, after it has turned off automatically?  That would suggest the turning off happens in the controller and/or the Hue bridge.  If you leave it alone after it has turned off automatically, will HomeKit eventually reflect the off state?

**Comment by CypressGTX** [comment]
Thank you for your reply, yes. after a minute. Hue and Homekit wil mark the ledstrip as off.

As you can see in the video below, I turn the scene on. you can see the ledstrip dimming off on my cam. and after a minute hue and homekit marks the ledstrip as off.

https://www.icloud.com/photos/#0apRuZY5q0uEU6VqWmFDzMBOQ

**Comment by ebaauw** [comment]
So it would seem the controller turns itself off, without the Hue bridge realising this.  Only when the bridge next polls the controller, it sees the new state, and passes this on to Homebridge Hue.

I would need to see a Zigbee sniffer log, to understand in detail what happens, but this is probably caused by a bug in the GLEDOPTO firmware combined with the Hue bridge only playing nice with Hue lights.  If memory serves, the GLEDOPTO controllers don't like the _Move to Level (with On/Off)_ command, which the Hue bridge would send on an API call setting both `on` and `bri` in the light state.  Homebridge Hue would make this call when recalling the HomeKit scene, but not when turning the light on from the tile.

I think I saw a similar issue for the GL-C-008, for which I hard-coded a patch.  According to my info, the GL-C-007 should be exposed as two lights (one for color and one for white) by the Hue bridge, but your video only shows a single light in the Hue app and in HomeKit?  Could you please attach the debug dump file, so I can have a look at how the Hue bridge exposes the controller?

Could you try and set `waitTimeUpdate` to 0 under the _Advanced Settings_ of the Homebridge Hue _Settings_ in the Homebridge UI (or in config.json), restart HomeKit, and see if the controller still turns off spontaneously?  This will cause unwanted side-effects, but if this works I can hard-code the setting for the GL-C-007, as I've done for the GL-C-008.

**Comment by CypressGTX** [comment]
Yes that is fixing the issue, set to 0.
Thank you!
does this setting consequenses for my lights or what else :)

**Comment by ebaauw** [comment]
The setting tells Homebridge Hue not to wait and see if another setting for the same light might arrive, combining those into a single api call.  Effectively, this causes separate api calls for _On_ and _Brightness_, so the Hue bridge won’t send _Move to Level (with On/Off)_.  As I mentioned before, this impacts all lights.  It causes them to turn on at previous or even full brightness and then dimming down to the requested level, instead of turning on at minimum brightness and then dimming up.

Please attach the debug dump file, so I can enable this setting only for this light model connected to a Hue bridge, as I’ve done for the GL-C-008.

**Comment by CypressGTX** [comment]
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/7025092/homebridge-hue.json.gz)
Thank you! is the debug log from the hue-homebridge enough?

**Comment by ebaauw** [comment]
Enough to whitelist the controller.  Not enough to understand it, I'm afraid, but there's no way to obtain more info from the Hue bridge, unless you have a Zigbee sniffer.  Is this a 5-channel RGB+CCT controller, or a 4-channel RGBW controller?  Can you set colour temperature, using `ct` to drive the WW/CW channels and colour using `xy` to drive the RGB channels?

I take it, you don't see the same issue with the GL-S-007Z(lk) bulbs?  I think they are newer and have a different firmware version.  Also, they correctly expose the minimum and maximum `ct` values they support.

**Comment by dppeak** [comment]
@ebaauw Is that suppose to be GL-C-007 instead of CL-C-007 on line 62 of HueLight.js
