### ISSUE TITLE
Sonoff ZBMINI appear as light

### ISSUE THREAD

**Issue by Skyman81** [ebaauw/homebridge-hue#1027]
my Sonoff ZBMINI when added appears as a light and not as a switch.  This also appears as a light in Homekit and cannot be changed.  It is a product that can be installed as a switch for coffee machines, power sockets, fans etc ... and not always for lights.  Is there a way to change the setting?

Thank you

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue/wiki/Resource-Links

**Comment by Skyman81** [comment]
Thanks!  For me it is a problem because it is easier to understand Chinese 😂 I will try to study how to create a resourcelinks because I do not understand much and / or nothing.  Do you think in the future there will be a way to change these settings directly in the pluggin?  Are all relays recognized as "light"?  Or just the Sonoff mini?  Thank you, I apologize for the inconvenience and for my ignorance.

**Comment by ebaauw** [comment]
The issue is that too many devices advertise themselves wrongly, so I cannot determine from the device whether to expose it as light or as outlet.  Also, you might want to expose a group of these as outlet.

Currently, Homebridge Hue has no persistent storage, so it cannot remember how you want to expose the device.  That’s why I use the resource links.  For these settings to be changed from the plugin, I need to use the dynamic platform accessory model, see #4.  Even then, it will kinda awkward to expose the settings to HomeKit, it probably would make more sense to use a dynamic settings window in the Homebridge UI.

**Comment by Skyman81** [comment]
Thank's for your job.  I hope iOs 15 can introduce some kind of modification directly into Apple's Homekit to overcome this problem.
