### ISSUE TITLE
Problem With TRV TS0601 Thermostat

### ISSUE THREAD

**Issue by pillemats** [ebaauw/homebridge-hue#1032]
hi ebaauw

i spend some days to get my zigbee thermostates to work.

my hardware:

- TS0601 Zigbee Theromstates
- ConeeII Stick on VM Win10 (newest release and firmware)
- homebridge on an VM Debian10 machine
- homebridge-hue plugin for all my zigbee devices

i can add the trv to deconz and they will work great with API.

<img width="448" alt="Bildschirmfoto 2021-10-16 um 22 03 31" src="https://user-images.githubusercontent.com/26164977/137600819-3f316781-76c3-4d5e-953a-137acbc76eea.png">

I tried all of the funktions with the deconz guys and the supportet me great! Many thanks!

Now the problem:

The TRV will shown correctly as an trv in homekit and i can change the temperature but i cant change the state.
Mode off and manuall wont work
if i change to off, it will switch directly to automatic back.
also in some cases the temperatur will not correctly transmitted.
The TRV says 15 grad and in Homekit 2 grad

![IMG_0020](https://user-images.githubusercontent.com/26164977/137600739-b561d8ea-583e-4376-8295-2ff6b23dd927.jpg)
![IMG_0622 2](https://user-images.githubusercontent.com/26164977/137600741-29dae15f-dd89-494c-a8b1-b8d5b9e55b31.jpg)

the guys from deconz say this is an homebridge issue and i hope you can help me!!!

Thank you very much

**Comment by ebaauw** [comment]
> i can add the trv to deconz and they will work great with API.

Are you sure?  It's reporting a current temperature of 2°C.  That would explain why HomeKit reports that value.

> the guys from deconz say this is an homebridge issue and i hope you can help me!!!

It's not so much a Homebridge issue, as it is a difference between HomeKit and Zigbee (or probably even the Tuya device, since they hardly follow the Zigbee standard).  HomeKit expects a _Current Heating/Cooling State_ and a _Target Heating/Cooling State_.  You set the target state through the Home app, and it reports the current state through the colour fo the temperature on the tile.  The current state takes values off, heating, and cooling.  The target state takes values off, heating, cooling, auto, where the latter means: automatically switch between heating and cooling.  So that value only makes sense for thermostats that actually support cooling, unlike TRVs.

Back in the day (before I fully understood the HomeKit support for thermostats), I made a hack for the Eurotronic Spirit, which actually support three operating modes for the valve: closed, open, temperature controlled.  I incorrectly mapped these to _Target Heating/Cooling State_ values off, heating, auto.  For other TRVs, the characteristic is exposed, but not yet implemented, as I don't know how these work.  I'm happy to add support for thus TRV, but I need documentation on what the API attributes mean, and what values they can take.  Also, the wrongly reported current temperature needs to be fixed in deCONZ (or in the device firmware).

**Comment by ebaauw** [comment]
> alternatively HomeKit heat could be considered as boost and auto mode as auto, but this could break the logic in general, so I always go with the "my practice"

Yes, I agree.  As I indicated above, the use of AUTO vs HEAT for the Spirit is a hack.

So `auto` in the REST API plugin basically means automatically control the valve position, where in HomeKit it means: automatically choose between heating and cooling.  Consequently, Boost mode should be exposed separately, both in the API as well as in HomeKit.

Above change supports setting _Target Heating Cooling State_, with values OFF (0) and HEAT (1), for any ZHAThermostat that supports `config.mode`.  When setting the characteristic to OFF, `mode` is set to `off`; when setting it to HEAT, `mode` is set to `auto`.  API value `auto` and any value other than `off` (e.g. `heat`) are mapped to HEAT.

This means that boost mode for the Eurotronic Spirit will no longer be recognised (as it's reported as HEAT) and can no longer be set from HomeKit.  I could eventually expose this using a custom characteristics, but before doing that, I think it should be exposed better by the deCONZ REST API (probably when supporting setting the valve position directly).

**Comment by ebaauw** [comment]
In v0.13.27.
