### ISSUE TITLE
Temperature Offset for hue motion sensor

### ISSUE THREAD

**Issue by Fish2** [ebaauw/homebridge-hue#1064]
Both of my hue motion sensor are reading around 2c lower than any other temp sensor I compare with is there a way you can add a temp offset and the I can run them throw this Homebridge plug in instead of native

**Comment by ebaauw** [comment]
I implemented an offset in deCONZ, which is exposed by Homebridge Hue.  I cannot do the same for the Hue bridge, as it cannot store the offset between Homebridge restarts, see #492.

I find the the temperature sensor in the Hue motion sensor is not very accurate, and adding an offset only helps a little.  Even after calibrating the sensor with an offset, so that it would correctly read 21°C, it would still be off at 15°C.

I think there’s a reason Signify don’t mention the temperature sensing feature in their marketing.  I was actually surprised when the device turned out to include this.  I think the device doesn’t actually contain a separate temperature sensor, but simply re-uses the infrared sensor for motion detection.

**Comment by Fish2** [comment]
Ok thanks for getting back to me. so there no way for the plugin to read the temp that is send to it and then add a number to that temp from the plugins config file then re report it ? or how would I go about configuring the deCONZ offset ? cant see any pages in the wiki relating to thats

**Comment by ebaauw** [comment]
The offset in deCONZ is exposed as `config.offset` on the ZHATemperature `/sensors` resource.  Homebridge Hue exposes it through a custom _Offset_ characteristic on the _Temperature Sensor_ service.  Apple's Home app doesn't support custom characteristics, but you can set this from any decent HomeKit app.
