### ISSUE TITLE
Error 202 -- certain devices no longer work.

### ISSUE THREAD

**Issue by barryl93** [ebaauw/homebridge-hue#1081]
#### Issue

Hi! I'm having a problem with Homebridge Hue and I'm not sure where else to turn. I've checked the troubleshooting steps, the wiki, and the existing issues, but haven't been able to resolve anything.

I've been running the plugin with no problems for several months now. But suddenly a slew of devices just aren't connecting. They still show up in Home.app, but they don't react when I tap on them. The log throws an error like the below.

I've updated to HB 1.3.9 and to the latest beta of the deCONZ software. Also running Node.js v16.13.1.

What's really weird is that of the 9 devices I have connected through Homebridge-Hue, four them are rock-solid. The other five don't connect. I run Hue in a child bridge, which I have restarted repeatedly. I've also rebooted my Conbee2 and rebooted my Raspberry Pi, all to no avail.

Any ideas?

#### Log Messages

```
[1/15/2022, 10:52:06 AM] [Hue] Sengled Foyer: homekit on changed from false to true
[1/15/2022, 10:52:06 AM] [Hue] Conbee2: request 314: PUT /lights/6/state {"on":true}
[1/15/2022, 10:52:06 AM] [Hue] Conbee2: request 314: api error 202: resource, /lights/6/state, is not modifiable. Device is not reachable.
```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/7875297/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
It’s an API error returned by the deCONZ gateway.  It indicates that the gateway thinks it cannot reach the light, and therefore won’t send the Zigbee command to the light to turn it on.  You should see similar issues using other deCONZ clients. The name on the correponding nodes in the GUI, are probably greyed out.

Make sure the lights are powered.  Press `0` in the GUI, on each node to revive them.  If that doesn’t work, power cycling the light usually does.  Since you mention that you have only 9 lights, I don’t think you’d be experiencing routing issues, but you could be experiencing interference issues.  Do you see Zigbee errors in the deCONZ log.  Did you physically move the host running deCONZ, or place some new devices next to it, with WiFi, Bluetooth or USB-3.

**Comment by barryl93** [comment]
Thanks for responding so quickly!

I haven't moved the Conbee2 or put anything new near it since first setting it up months ago.

It's not just lights -- there's also a thermostat, a couple of seniors, and a button. I've attached a screenshot of the deCONZ GUI.

When I select a device and hit 0, the little dot flashes red and then nothing.

Everything connected to the deCONZ just fine and everything was working beautifully through Hue and then... I don't know what happened.

I don't know where to get to the deCONZ log.
![Screen Shot 2022-01-15 at 10 46 53 AM](https://user-images.githubusercontent.com/39839859/149629747-0aa22fd3-f6aa-4c70-9628-c91a1d791ad8.png)

**Comment by ebaauw** [comment]
> I don't know where to get to the deCONZ log.

Under _Help_ | _Debug View_.  Anyways, this is an issue between deCONZ and the Zigbee devices - nothing Homebridge Hue can do anything about.

**Comment by barryl93** [comment]
Thank you for your time and for pointing me in the right direction. 

-----------

Transmitted via Mr. Jobs' Wonder Glass
