### ISSUE TITLE
Systemd startup problem

### ISSUE THREAD

**Issue by abko** [ebaauw/homebridge-hue#109]
Since I while I have a problem when I start homebridge via systemd. After a reboot it appears as if homebridge is active and all config has been processed without errors. Homebridge is however not exposing itself to Homekit.

Restarting homebridge via 'sudo systemctl restart homebridge' solves the problem.

By removing config for other plugins I believe I have isolated the problem to be homebridge-hue related.

With a config only loading the hue platform I actually get the error below.

Does anyone have hint of what could cause the problem?

> pi@raspberrypi:~ $ sudo systemctl status homebridge -l
> ● homebridge.service - Node.js HomeKit Server
>    Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
>    Active: active (running) since Sun 2017-05-14 20:48:20 CEST; 1min 32s ago
>  Main PID: 481 (homebridge)
>    CGroup: /system.slice/homebridge.service
>            └─481 homebridge                                           
> 
> May 14 20:48:56 raspberrypi homebridge[481]: [5/14/2017, 8:48:56 PM] Registering accessory 'homebridge-yamaha.YamahaAVR'
> May 14 20:48:56 raspberrypi homebridge[481]: [5/14/2017, 8:48:56 PM] Registering platform 'homebridge-yamaha.YamahaAVR'
> May 14 20:48:56 raspberrypi homebridge[481]: [5/14/2017, 8:48:56 PM] ---
> May 14 20:48:56 raspberrypi homebridge[481]: [5/14/2017, 8:48:56 PM] Loaded config.json with 0 accessories and 1 platforms.
> May 14 20:48:56 raspberrypi homebridge[481]: [5/14/2017, 8:48:56 PM] ---
> May 14 20:48:57 raspberrypi homebridge[481]: [5/14/2017, 8:48:57 PM] Loading 1 platforms...
> May 14 20:48:57 raspberrypi homebridge[481]: [5/14/2017, 8:48:57 PM] [Hue] Initializing Hue platform...
> May 14 20:48:57 raspberrypi homebridge[481]: [5/14/2017, 8:48:57 PM] [Hue] homebridge-hue v0.4.3, node v7.10.0, homebridge v0.4.20
> May 14 20:48:57 raspberrypi homebridge[481]: [5/14/2017, 8:48:57 PM] Loading 0 accessories...
> May 14 20:48:57 raspberrypi homebridge[481]: [5/14/2017, 8:48:57 PM] [Hue] meethue portal: communication error EAI_AGAIN

**Comment by ebaauw** [comment]
According to Google, EAI_AGAIN is a DNS lookup timeout error.  homebridge-hue tries to contact www.meethue.com, to see which bridges have been registered, but this fails.  I think systemd is starting homebridge too early, before the network is fully initialised.  I had similar issues trying to start homebridge automatically on my Mac server.

homebridge-hue shouldn't be blocking homebridge - this is a bug.  However, it's a blessing in disguise: when homebridge would have continued, it would have exposed itself to HomeKit without the homebridge-hue accessories.  HomeKit would subsequently delete these accessories from its configuration, losing any assignments to HomeKit rooms, groups, scenes and automation.  After restarting homebridge, HomeKit would see the homebridge-hue accessories as new accessories.  I can fix the bug, but I'm afraid it would make your issue worse.  Alternatively, I could force homebridge to exit when homebridge-hue can't initialise properly, under the assumption that systemd would restart it, hopefully now with a fully initialised network.

The structural problem is that homebridge-hue still uses the static platform accessory model, where all accessories must be initialised during homebridge startup.  The structural solution is to change homebridge-hue to use dynamic platform accessories, see issue #4.  I'm working on this, but it involves quite a lot of refactoring, which might take me a couple of months.

Maybe one the following workarounds could help in the meanwhile:
- On my (headless) Mac server, I'm now starting homebridge as a user agent for the autologin user rather than as a system agent.  I find the network to be fully initialised by the time the user is logged in and the agent is started.
- I'm not too familiar with the pi boot sequence, but there is a _Wait for network_  option under the _System_ tab in the _Raspberry Pi Configuration_.  Maybe that causes systemd to wait until after the network is up.
- If your Hue bridge has a static IP address (or your DHCP server/router uses a fixed address for the Hue bridge) you can specify this in config.json.  In that case, homebridge-hue will not do any discovery and connects to the bridge without any DNS lookup.

**Comment by ebaauw** [comment]
I just released v0.4.4, which will retry the bridge discovery every 30 seconds until at least one bridge has been found.  Note that homebridge won't be visible to HomeKit during this time.

**Comment by abko** [comment]
Thanks! I'll try it this evening and will let you know. Excellent plugin by the way. Thanks a lot !!

**Comment by abko** [comment]
Could there be something wrong in discovery? It is now retrying in a loop:

> [5/15/2017, 7:39:26 PM] [Hue] searching bridges
> [5/15/2017, 7:39:26 PM] [Hue] meethue portal: get /api/nupnp
> [5/15/2017, 7:39:26 PM] [Hue] upnp search: searching at 239.255.255.250:1900 for 5 seconds
> [5/15/2017, 7:39:26 PM] [Hue] meethue portal: found bridge 001788FFFE217B63 at 192.168.1.58
> [5/15/2017, 7:39:31 PM] [Hue] upnp search: done
> [5/15/2017, 7:39:31 PM] [Hue] no bridges found - retrying in 30 seconds

**Comment by ebaauw** [comment]
Oops looks like I made a typo in the code: `> 1` instead of `> 0`.  Consequently, homebridge-hue waiting for a second bridge.  I have two bridges at home, so v0.4.4 passed my testing yesterday.

Will publish v0.4.5 with fix shortly.

**Comment by abko** [comment]
Thanks again. I will do another test when it's available!

**Comment by abko** [comment]
Just tested 0.4.5 and it's working also without host specified, both when starting via systemd or manually! Thanks for the fix!

**Comment by jdshkolnik** [comment]
I now seem to be hitting this same problem with 0.4.8.

**Comment by ebaauw** [comment]
Could you pls post the log when starting `homebridge -D`?

**Comment by jdshkolnik** [comment]
I think that might've been a genuine connection problem because it's working ok now. My bigger problem is that Homebridge no longer appears as an accessory. I tried changing the bridge name username in config.json but it still doesn't appear. The idea of wiping out the entire home is not appealing.

**Comment by ebaauw** [comment]
Typically this happens when homebridge thinks it's still paired, but HomeKit thinks it isn't.  Whiping your home won't help in this case.  You need to remove `~/.homebridge/persist` and restart homebridge.

**Comment by jdshkolnik** [comment]
In my case, the only persist folders are in ./var/lib/homebridge and ./root/.homebridge/persist but deleting them doesn't fix the problem.

**Comment by ebaauw** [comment]
How many accessories do you expose from homebridge?  HomeKit only supports 99 accessories per bridge.

**Comment by jdshkolnik** [comment]
I formatted the RPi and started over.

**Comment by ebaauw** [comment]
And?

**Comment by jdshkolnik** [comment]
It's running. I added that generic flag but, oddly, on my iPad it shows up as a switch accessory (which is the device I used to register the homebridge) but on both my iPhones it shows up as a motion sensor. As a result, the automation rule I set up on my iPad "When Flag Turns On" becomes "Motion Detected" on my iPhones and "When Flag Turns Off" on iPad doesn't appear at all on iPhones.

**Comment by ebaauw** [comment]
It would seem the HomeKit configuration isn't synced correctly (over iCloud) between your iOS devices.  How big is your HomeKit configuration?  Somewhere around 150 accessories, the sync breaks, but this is a limit on the size of the configuration, not on the number of accessories, so your mileage may vary.

Even well below this limit, HomeKit doesn't like to sync a lot of configuration changes in short succession.  I usually disable Home in the iCloud settings on all my iPhones and AppleTV, before seriously reconfiguring HomeKit on my iPad.  Only when the entire config on the iPad is done, I re-enable Home on the other devices.

**Comment by jdshkolnik** [comment]
I have 74 accessories. What do you recommend I do now? Disconnect all but iPad and then reconnect?

**Comment by ebaauw** [comment]
This is no fun, but if you're up to it, these are the steps I take when my HomeKit configuration has screwed up (like every other month or so):
- Remove the home from HomeKit;
- Wait for this change to propagate to all devices.  Might take several minutes;
- Disable Home from iCloud settings on all your other devices, incl. AppleTV;
- Setup the iPad as HomeKit Hub (connect it to power, restart Settings and Home should appear under Safari);
- Create a new HomeKit home;
- Re-create the HomeKit rooms and zones;
- Stop homebridge; delete persist and accessories in ~/.homebridge; restart homebridge and check the output/log to make sure all expected accessories are being exposed;
- Factory-reset any other accessories;
- Re-pair homebridge and any other accessories;
- Re-configure all accessories (rooms, favourites, notifications, what have you);
- Re-create your HomeKit groups, scenes, automations;
- Re-configure HomeKit rooms (order of scenes and accessories);
- Check that the automations work;
- Re-enable HomeKit on the AppleTV; disable HomeKit Hub on the iPad (check the arrow in the upper left corner in the Home view in the Home app); wait some minutes and check that the automations still work;
- One by one re-enable Home under iCloud settings on the iPhones.  Wait for the config to be synced before enabling the next device.

**Comment by jdshkolnik** [comment]
I can't bring myself to do all that. I bet it'd still not work correctly in which case I'd be left with ritual suicide as the only honorable way to continue.
