### ISSUE TITLE
When I restart the server, the homebridge-hue service takes more than 6 minutes to start.

### ISSUE THREAD

**Issue by marmitol** [ebaauw/homebridge-hue#1098]
Thank you very much for this fantastic plug-in.
When I restart the server, the hue service takes more than 6 minutes to start.
I have a raspberry pi 4. If I restart raspberry pi 4 all services start, but the homebridge-hue service has to wait up to 6 minutes. After this time it works correctly.
![image](https://user-images.githubusercontent.com/61157812/159029568-868d1178-2206-4797-9042-ad87a21b2962.png)

**Comment by ebaauw** [comment]
That's by design: Homebridge Hue delays Homebridge startup until it has discovered and connected to a Hue bridge or deCONZ gateway.  If it wouldn't, HomeKit would remove the accessories on Homebridge startup.

Six minutes does seem a bit long for deCONZ to start, though.  Are Homebridge and deCONZ running on the same Pi?

**Comment by marmitol** [comment]
Yes everything is running on the same raspberry pi 4.

**Comment by ebaauw** [comment]
Homebridge Hue works as designed - I don't need any other info.

I don't know why deCONZ takes this long to start and become discoverable.  You might want to specify the localhost in `hosts`, to bypass discovery.  I doubt this will help, however, as local discovery through UPnP should be almost instant.

**Comment by marmitol** [comment]
I will continue to investigate. If I have any news on the subject I will write it down.
