### ISSUE TITLE
Phoscon-GW: /sensors/3: warning: unknown ZHAFire sensor

### ISSUE THREAD

**Issue by ruudbol** [ebaauw/homebridge-hue#1108]
Hi, I get (only for the added sensors) messages during homebridge startup with the following statement:

eg:
Phoscon-GW: /sensors/3: warning: unknown ZHAFire sensor {"config":{"enrolled":1,"on":true,"pending":[],"reachable":true},"ep":1,"etag":"2632665781d47b845ae361206ca2d161","lastannounced":"2022-08-21T17:53:24Z","lastseen":"2022-08-22T06:01Z","manufacturername":"Bitron Home","modelid":"902010/24","name":"Woonkamer Rookmelder","state":{"fire":false,"lastupdated":"2022-08-22T06:01:34.789","lowbattery":false,"tampered":false},"swversion":"20150210","type":"ZHAFire","uniqueid":"00:12:4b:00:06:21:94:08-01-0500"}

Is there anything I can do about this ?

Kind Regards,
Ruud

**Comment by ebaauw** [comment]
I just a warning that this model hasn't been whitelisted.  If it works otherwise, the warning can safely be ignored.

I'll get rid of most whitelisting in Homebridge deCONZ.  It's mostly needed for switches (since the API doesn't yet report the buttons); for other device types, deCONZ does a fair job of standardising how the API exposes the device.
