### ISSUE TITLE
how to change zigbee-switches to another room?

### ISSUE THREAD

**Issue by JaJaRoRo** [ebaauw/homebridge-hue#1111]
Hi,
I'm new to homebridge. I just succesfully connected my Hue Bridge to my Homebridge by using the first example in the configuration wiki.
My zigbee-switches are now visible in homekit, great! But i can't change them to the correct room. They appear to be fixed to the room where the Homebridge is "placed". 
Is there an easy way to fix this issue?

**Comment by ebaauw** [comment]
You can only assign or change rooms from a HomeKit app.  The accessory itself (nor Homebridge nor any Homebridge plugin) has no visibility on rooms, groups, scenes, nor automations.

**Comment by JaJaRoRo** [comment]
Thanks, i did understand that. But when i try to move it to another room in Homekit, it changes back to its original room (where the homebridge is located in homekit) when i close te settings-page. I do not have this problem with other plugins (for example: Ring, iRobot)

**Comment by ebaauw** [comment]
It’s technically impossible to be related to the plugin.

Config changes spontaneously reverting in my experience is due to failing iCloud synchronisation across Apple devices.  Make sure all your Apple devices are on the latest OS version.  Otherwise, there’s very little to do about it, other than waiting for the dust to settle.  You might try and power down some of the devices, I am particularly suspicious of the HomePod mini.

**Comment by JaJaRoRo** [comment]
You were right! One of my iPads running on an older version of OS15 was the cause. Turning it off, like you suggested, made me able to change the switches to other rooms. After updating the OS version, everything works fine.
Thanks for your support!
