### ISSUE TITLE
Hue Bridge API Update from 1.53.0 to 1.55.0 causes warnings

### ISSUE THREAD

**Issue by Soilman82** [ebaauw/homebridge-hue#1133]
#### Issue

Hi,

I think the Hue Bridge API was updated and now I get this warnings after (re-)starting HueBridge. Could you please check if the API is compatible and recommend the higher version? 

Thank you for this plug-in and all your work on it!

Cheers
Michael

#### Log Messages

```
[5.1.2023, 09:14:54] [HueBridge] Philips Hue: Signify Netherlands B.V. BSB002 bridge v1955082050, api v1.55.0
[5.1.2023, 09:14:54] [HueBridge] Philips Hue: warning: not using recommended Hue bridge api version 1.53.0
```

**Comment by ebaauw** [comment]
> Could you please check if the API is compatible

No.

The good folk at Signify haven't published any [changelog](https://developers.meethue.com/develop/hue-api/api-documentation-changelog/) since API v1.39, and the [release notes](https://www.philips-hue.com/nl-nl/support/release-notes/bridge) don't even mention API versions.

I only use my Hue bridge for reverse-engineering new Hue devices, so I wouldn't notice any incompatibilities.  It looks like my bridge updated on Dec 12, and I hadn't even noticed it before.  I'm really relying on you folks to report any issues, and if there aren't, I'm happy to bump the dependency, to get rid of the warning.

**Comment by jostrasser** [comment]
@ebaauw mine updated approx. a months ago and I did not recognize any issues with 1.55. Looks good so far.

**Comment by ebaauw** [comment]
And now we have 1.56.0, with functional changes to the event stream, see #1142.
