### ISSUE TITLE
Using resourcelink

### ISSUE THREAD

**Issue by rgerr** [ebaauw/homebridge-hue#1134]
I’m trying to use resource links ( https://github.com/ebaauw/homebridge-hue/wiki/Resource-Links) to expose some lights (ledvance plug in reality, but Hue bridge sees them as lights).

I’m just having trouble know which device is which number exactly, for example ‘lights/23’.

This used to be in the Hue app, in settings under ‘about’, but this is not there anymore. Is there another way finding out which light is which, so I know which I can expose as a plug?

p.s. I checked the wiki and other issues, but nothing answers my question. Sorry if I missed something.

#### Log Messages

```
```

**Comment by ebaauw** [comment]
I think the Hue app no longer shows the resource IDs, since it is migrating to the Hue API v2, where they've replaced the resource IDs by UUIDs.  Even less user-friendly.

Probably easiest to expose all lights temporarily, and check the _Resource_ in Eve or another decent HomeKit app.  Alternatively, run Homebridge in DEBUG mode and check the log messages.  Homebridge Hue logs all resources on startup, and you can see the resource as Homebridge Hue logs commands sent to the Hue bridge when you control the lights from HomeKit.

**Comment by rgerr** [comment]
> I think the Hue app no longer shows the resource IDs, since it is migrating to the Hue API v2, where they've replaced the resource IDs by UUIDs. Even less user-friendly.
> 
> Probably easiest to expose all lights temporarily, and check the _Resource_ in Eve or another decent HomeKit app. Alternatively, run Homebridge in DEBUG mode and check the log messages. Homebridge Hue logs all resources on startup, and you can see the resource as Homebridge Hue logs commands sent to the Hue bridge when you control the lights from HomeKit.

Not sure where to find the resource in the latest Eve app, but I will give the homebridge log in debug mode a try. Thanks for this and the great plug-in!
