### ISSUE TITLE
Can't move exposed light or outlet to different room

### ISSUE THREAD

**Issue by lugaetsch** [ebaauw/homebridge-hue#1143]
#### Issue
Hi fellas!
Since I had plenty issues with new Home architecture I reset my whole(!) Home config.
Anyway - I recycled the configuration for huebridge-hue plugin. So everything was in the same configuration but adding a new user for huebridge connection (I reset this as well, just in case ;-) ).
I do see the exposed light and outlet but can't move them into a different room?
With below config I do see another exposed thing with same name as my huebridge. For this item I am able to move it into a different room...
Any experiences on that or do I miss anything in my config?

#### config-file
{
            "name": "Hue",
            "anyOn": true,
            "effects": false,
            "hosts": [
                "192.168.30.15"
            ],
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "resource": true,
            "users": {
                "xxx": "xxx"
            },
            "platform": "Hue"
        }

**Comment by ebaauw** [comment]
Assigning an accessory to a room happens in HomeKit, invisible to the accessory itself.  It's technically impossible for this issue to be related to Homebridge or Homebridge Hue.

Any weirdness in HomeKit since iOS 16.2 and/or the new HomeKit architecture is probably caused by a rogue home hub.  Make sure these are on the latest firmware.  Power-cycle them.  Power-down all except one, preferable an AppleTV connected by Ethernet.

**Comment by lugaetsch** [comment]
Hi Erik, thanks for your kind reply!
Sometimes patience is your friend - assignment to a different room worked after a few moments waiting :)
