### ISSUE TITLE
v0.14.3 not working getting the following messages

### ISSUE THREAD

**Issue by ruudbol** [ebaauw/homebridge-hue#1196]
After update I get the following messages.
[09/11/2024, 12:05:15] [Hue] homebridge-hue v0.14.3, node v22.11.0, homebridge v1.8.5
[09/11/2024, 12:05:15] [Hue] config.json: effects: invalid key
[09/11/2024, 12:05:15] [Hue] Hue Bridge: Signify Netherlands B.V. BSB002 bridge v1967054020, api v1.67.0
[09/11/2024, 12:05:16] [Hue] Hue Bridge: request 3: GET /button
[09/11/2024, 12:05:16] [Hue] Hue Bridge: request 3: http status 404 Not Found
[09/11/2024, 12:05:16] [Hue] Hue Bridge: http status 404 Not Found - retrying in 15s

downgrade to v0.14.2 for now, no problem.

**Comment by herbertblom** [comment]
My issue is the same.
Downgrade did the job for now.
Patiently waiting

**Comment by ebaauw** [comment]
Could you please run Homebridge in DEBUG mode, so I can see the request to and response from the Hue bridge?  Do you have any switches connected to your Hue bridge?

**Comment by herbertblom** [comment]
When I have the time I will. I have a switch connected to hue which is not compatibel with HomeKit. That is why I use homebridge. Met vriendelijke groet,Herbert BlomOp 9 nov 2024 om 16:40 heeft Erik Baauw ***@***.***> het volgende geschreven:﻿
Could you please run Homebridge in DEBUG mode, so I can see the request to and response from the Hue bridge?  Do you have any switches connected to your Hue bridge?

**Comment by ebaauw** [comment]
Sorry, I meant a wireless switch, like the Hue dimmer switch, Hue smart button, Hue tap dial switch, Hue tap switch, Hue wall switch module, or a Friends-of-Hue switch.

Never mind the DEBUG mode (it won't show the info I need); but please run the `ph -DD -H ... get /button`.

**Comment by ruudbol** [comment]
Yes, hue dimmer switch and hue tap dial switchOp 9 nov 2024 om 20:11 heeft Erik Baauw ***@***.***> het volgende geschreven:﻿
Sorry, I meant a wireless switch, like the Hue dimmer switch, Hue smart button, Hue tap dial switch, Hue tap switch, Hue wall switch module, or a Friends-of-Hue switch.
Never mind the DEBUG mode (it won't show the info I need); but please run the ph -DD -H ... get /button.

**Comment by ruudbol** [comment]
![IMG_0554](https://github.com/user-attachments/assets/ef164b57-9099-4241-955c-903c2869d2a1)

**Comment by herbertblom** [comment]
![IMG_0078](https://github.com/user-attachments/assets/f54f4e1c-17c1-4de8-b719-bc25deae7c33)
![IMG_0077](https://github.com/user-attachments/assets/ce3dd59f-d7a2-4537-b0cb-201f3b934566)

Did the ph -DD -H with the 0.14.3.
I hope this makes sense to you.
Herbert

**Comment by ebaauw** [comment]
You need to press the button on the Hue bridge and within 60s issue `ph -H 192.168.178.20 getApiKey` for `ph` to obtain an API key.  `ph` automatically stores the key in `~/.ph`.  Homebridge Hue cannot store its API key automatically, hence the instruction to edit config.json manually and store the API key there.

**Comment by herbertblom** [comment]
I pressed the hue bridge button within 5 seconds of the question asked. An api is created, and that key I need to put in the config.json? Because, as in 0.14.2, 0.14.3 doesn’t do this automaticaly. Am i right?Met vriendelijke groet,Herbert BlomOp 10 nov 2024 om 16:55 heeft Erik Baauw ***@***.***> het volgende geschreven:﻿
You need to press the button on the Hue bridge and within 60s issue ph -H 192.168.178.20 getApiKey for ph to obtain an API key.  ph automatically stores the key in ~/.ph.  Homebridge Hue cannot store its API key automatically, hence the instruction to edit config.json manually and store the API key there.

**Comment by ebaauw** [comment]
`ph` and Homebridge Hue each use their own API key (aka username).  For Homebridge Hue, see https://github.com/ebaauw/homebridge-hue?tab=readme-ov-file#installation; for `ph`, see https://github.com/ebaauw/homebridge-hue/wiki/ph-Tutorial#obtaining-an-api-key.  Note that as of v0.14.3, `username` has been replaced with the more accurate `apiKey`, so it's `ph getApiKey` instead of `ph createuser`

**Comment by ruudbol** [comment]
Hi Erik, I still get the following message 

[11/11/2024, 08:08:37] [Hue] Hue Bridge: Signify Netherlands B.V. BSB002 bridge v1967054020, api v1.67.0
[11/11/2024, 08:08:37] [Hue] Hue Bridge: request 3: http status 404 Not Found
[11/11/2024, 08:08:37] [Hue] Hue Bridge: http status 404 Not Found - retrying in 15s

I executed ph -H …. getApiKey
XBZ2bTWlM39CH9NzsDah-fSF6g6Dw1MqsnjQg099

And in config.json I put the ApiKey in users part

            "users": {
                "ECB5FAFFFE2E0CD1": "XBZ2bTWlM39CH9NzsDah-fSF6g6Dw1MqsnjQg099"
            },


This is the complete json.config for HUE

"name": "Hue",
            "anyOn": true,
            "excludeSensorTypes": [
                "Daylight"
            ],
            "forceHttp": true,
            "hosts": [
                "192.168.1.100:80"
            ],
            "lights": true,
            "effects": true,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": false,
            "resource": true,
            "sensors": true,
            "users": {
                "ECB5FAFFFE2E0CD1": "XBZ2bTWlM39CH9NzsDah-fSF6g6Dw1MqsnjQg099"
            },
            "_bridge": {
                "username": "0E:73:66:35:B4:8E",
                "port": 51840
            },
            "platform": “Hue"

Hope you can help, for now i will downgrade to 0.14.2

Kind Regards,
Ruud

**Comment by herbertblom** [comment]
I have got a username/api for ph but everytime I push the hue button it gives me a different apikey. With 0.14.2 that was what i did and it went on from there. Automaticaly. Now it is not. Everytime I restart homebridge I pushed the hue button, but now with0.14.3 I need to put the apikey from hue in config.json?Met vriendelijke groet,Herbert BlomOp 10 nov 2024 om 23:19 heeft Erik Baauw ***@***.***> het volgende geschreven:﻿
ph and Homebridge Hue each use their own API key (aka username).  For Homebridge Hue, see https://github.com/ebaauw/homebridge-hue?tab=readme-ov-file#installation; for ph, see https://github.com/ebaauw/homebridge-hue/wiki/ph-Tutorial#obtaining-an-api-key.  Note that as of v0.14.3, username has been replaced with the more accurate apiKey, so it's ph getApiKey instead of ph createuser

**Comment by ebaauw** [comment]
> I have got a username/api for ph but everytime I push the hue button it gives me a different apikey.

Yes, every time an API clients requests an API key from the Hue bridge, a new API key is generated.  This enables the Hue bridge to keep track of the different API clients.  That why the API key needs to be persisted, or you would have to press the Hue bridge key everything you start Homebridge Hue (or with every `ph` command).  Homebridge Hue persists the API key in config.json; unfortunately that needs to be maintained manually (as config.json should not be writeable from Homebridge).  `ph` persists the key automatically in `~/.ph`.

All this has little to do with the "http status 404 Not Found" issue.  I need to see exactly what Homebridge Hue (or `ph`) sends to the Hue bridge, and what the Hue bridge responds.

>             "forceHttp": true,

Why do you have this set?  I think this might actually be causing the issue, as the GET of `/button` is an API v2 call, which only works over `https`.  Still a bug that Homebridge Hue won't continue without using the event stream.  v0.14.2 uses a separate API client for this v2 call, which would use `htttps` irrespective of the setting, but v0.14.3 uses the updated `HueClient` that supports both API versions.  If you didn't see any errors in v0.14.2, `https` works, and you shouldn't be setting `forceHttp` anyways.

**Comment by ebaauw** [comment]
v0.14.4 will not try to use the event stream when `forceHttp` has been set (as the event stream is part of the v2 API, it only works over HTTPS).  This should solve this issue, but will lead to sluggish performance, especially on button presses.  One could argue that version before v0.14.3 actually had a bug, in that `forceHttp` wasn't fully honoured.

Morale: don't set `forceHttp`.  That's why it's under the _Advanced Settings_ that you shouldn't change.

Also, I've added a `-f` or `--forceHttp` flag to `ph` for debugging.

**Comment by ruudbol** [comment]
Hi Erik, installeer 0.14.4 and switch off force http, however I then get the following message

[11/11/2024, 10:36:07] Loaded 0 cached accessories from cachedAccessories.0E736635B48E.
[11/11/2024, 10:36:07] [Hue] homebridge-hue v0.14.4, node v22.11.0, homebridge v1.8.5
[11/11/2024, 10:36:07] [Hue] Hue Bridge: Signify Netherlands B.V. BSB002 bridge v1967054020, api v1.67.0
[11/11/2024, 10:36:07] [Hue] Hue Bridge: request 1: GET /
[11/11/2024, 10:36:07] [Hue] Hue Bridge: request 1: write EPROTO C0EAFE76:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:

[11/11/2024, 10:36:07] [Hue] Hue Bridge: write EPROTO C0EAFE76:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
 - retrying in 15s



Kind regards,
Ruud

**Comment by ebaauw** [comment]
I guess that would be the reason why you set `forceHttp`.  Looks like the NodeJS installation on your system isn’t compatible with the SSL version.  I’m afraid that’s beyond me.  Did you have a similar message with v0.14.2 without `forceHttp`?  Do you see the same error for `ph`?   If not: Are you running Homebridge Hue in a separate child bridge? and: Did you re-install Homebridge and Homebridge Config UI X after upgrading to NodeJS v22?

You can still set `forceHttp` in v0.14.4 and use an aggressive `heartbeat` setting to mitigate the sluggyness.

**Comment by ruudbol** [comment]
Did you have a similar message with v0.14.2 without forceHttp — YESAre you running Homebridge Hue in a separate child bridge —YESDid you re-install Homebridge and Homebridge Config UI X after upgrading to NodeJS v22 — NOOp 11 nov 2024 om 11:17 heeft Erik Baauw ***@***.***> het volgende geschreven:﻿
I guess that would be the reason why you set forceHttp.  Looks like the NodeJS installation on your system isn’t compatible with the SSL version.  I’m afraid that’s beyond me.  Did you have a similar message with v0.14.2 without forceHttp?  Do you see the same error for ph?   If not: Are you running Homebridge Hue in a separate child bridge? and: Did you re-install Homebridge and Homebridge Config UI X after upgrading to NodeJS v22?
You can still set forceHttp in v0.14.4 and use an aggressive heartbeat setting to mitigate the sluggyness.

**Comment by herbertblom** [comment]
Can’t we do this in dutch. I am lost in translation. Met vriendelijke groet,Herbert BlomOp 11 nov 2024 om 13:52 heeft ruudbol ***@***.***> het volgende geschreven:﻿
Did you have a similar message with v0.14.2 without forceHttp — YESAre you running Homebridge Hue in a separate child bridge —YESDid you re-install Homebridge and Homebridge Config UI X after upgrading to NodeJS v22 — NOOp 11 nov 2024 om 11:17 heeft Erik Baauw ***@***.***&gt; het volgende geschreven:﻿
<br>
I guess that would be the reason why you set forceHttp.  Looks like the NodeJS installation on your system isn’t compatible with the SSL version.  I’m afraid that’s beyond me.  Did you have a similar message with v0.14.2 without forceHttp?  Do you see the same error for ph?   If not: Are you running Homebridge Hue in a separate child bridge? and: Did you re-install Homebridge and Homebridge Config UI X after upgrading to NodeJS v22?
<br>
You can still set forceHttp in v0.14.4 and use an aggressive heartbeat setting to mitigate the sluggyness.
<br>

<br>

**Comment by ebaauw** [comment]
There is something wrong with your system that breaks SSL support from NodeJS.  SSL is used for HTTPS, which the Hue bridge requires for the API v2.  This is not caused by Homebridge Hue, and cannot be solved by Homebridge Hue.  As a workaround, you can set `forceHttp` to make Homebridge Hue not use HTTPS, but then it cannot use the event stream.  This workaround will not work for Homebridge Hue2.

**Comment by oleschaper** [comment]
I had the exact same issue, thanks for looking into it and the fix!
Also the same error message regarding SSL when setting forceHttp to false.
In my case the reason was due a hardcoded port 80 in the hosts settings (I don't know why that was in there...)
After I removed the port and just kept the IP it worked fine with https.

**Comment by ebaauw** [comment]
Thanks for the info!  The port  in `hosts` was needed for deCONZ, which can be configured to use a non-default port.  Since we dropped deCONZ support, I’d better remove support for specifying the port in Homebridge Hue.

So, apparently, the wrong version number in the error message refers to the SSL version of the Hue bridge (which would be bogus on the plain HTTP port 80), rather than the version of the SSL library on the NodeJS host?

**Comment by ruudbol** [comment]
Thx @oleschaper, that solved my issue, i removed port 80, everything is working fine now, even https.
