### ISSUE TITLE
"Blocked" motion sensor accessory

### ISSUE THREAD

**Issue by ronnycarr** [ebaauw/homebridge-hue#123]
Hi, apologies if I missed an answer to this somewhere.

But after setting everything I am unable to edit any attribute for my motion and corresponding light sensors. When I try to move them from Default Room I get an error saying the accessory is blocked and can't be edited. This only happens for this one device. My dimmer switches, non Hue bulbs, and Hub are all editable.

Thanks in advance! And I gotta say, homebridge is incredible! I can't believe I didn't know about it until yesterday.

**Comment by ebaauw** [comment]
HomeKit marks an accessory as "blocked" when it doesn't like it, typically because it reports invalid values, or contains an invalid combination of services and characteristics.  Some HomeKit apps support unblocking a block accessory, but that has never helped me.  Best cause of action, in my experience, is removing the accessory from HomeKit and re-connecting it.

To remove the motion sensor, without resetting your entire HomeKit configuration, add the following to config.json:
```json
  "excludeSensorTypes": [ "ZLLPresence", "ZLLLightLevel", "ZLLTemperature" ]
```
and restart homebridge.  Wait for the sensor to be removed from all your iOS devices, this might take several minutes.  After that, revert the change to config.json and restart homebridge for a second time.  The motion sensor should re-appear (as a new accessory).  Note that the motion, light level and temperature sensors are services of the same accessory, so you need to disable all three of them for homebridge-hue to stop exposing the accessory.

I have no clue as to why the motion sensor has been blocked.  I've only come across blocked accessories in homebridge / homebridge-hue during development/test, when I make some code changes to an accessory and restart homebridge to test these changes, without removing and reconnecting the accessory.  
I've never seen this running homebridge-hue and I haven't received any reports either.  I suspect it could be related to failures or hiccups during iCloud synchronisation of the HomeKit database between you iOS devices.  This tends to deteriorate with larger configurations, until you hit a size limit where synchronisation stops completely.  Typically this limit is well above 100 accessories, though.

**Comment by ronnycarr** [comment]
Excluding and adding the device again worked like a charm. Thank you so much for the help! I've been scratching my head and Googling like cray to try and figure it out.
