### ISSUE TITLE
iCloud sync issue

### ISSUE THREAD

**Issue by yaudouin** [ebaauw/homebridge-hue#129]
I have an iPad Air 2, iPhone 6 and Apple TV.
All my bulbs are ok (directly from hue bridge)
All my sensors are ok (from homebridge-Hue)
But when I add osram plugs from homebridge-hue, the synchronization between the ipad and the iphone is no longer done (I set just the room and I set the type on light instead of switch)

I have 3 Hue bridges. I tried one after another with the same result. When I remove the plugs, the synchronization starts again..

**Comment by ebaauw** [comment]
I don't think this is related to The Osram Lightify plugs - they work work fine for me.  How many HomeKit accessories do you have in total?  HomeKit iCloud sync fails when your HomeKit config exceeds a single CKRecord, typically above some 120 - 150 accessories, but your mileage may vary.

**Comment by yaudouin** [comment]
Thank you Erik !

Ok, I understand. I count 1+42+7+10+14+25+1+3 accessories (on 3 Hue bridges, and 4 Homebridge) = 103 accessories, 110 if I add bridges. This limit is a total of accessories per bridge or a total of accessories per home ?

**Comment by yaudouin** [comment]
Ok, I think I've found the problem : the size of Homekit CKRecord.
The last version of homebridge-hue plugin expose DimmerSwitches, and the number of all my accessories has grown.  Now I removed all dimmer switches and the plugs are synchronized :-)

**Comment by ebaauw** [comment]
Yeah the HomeKit config for an iCloud account needs to fit a single CKRecord.  It doesn't even matter whether it's in a single home or multiple homes.  See also https://forums.developer.apple.com/thread/64682.

I'm not sure what counts against this limit, but I assume it's all of HomeKit: accessories, rooms, groups, scenes, automations.  I haven't (yet) run into the limit in my "production" environment, but every time I launch a test instance of homebridge with more than a few accessories I run into this limit.

How much of your accessories are exposed by homebridge vs the native Philips Hue?  And how much through homebridge-hue?  Do you reach the limit earlier (with fewer accessories) when you expose lights through homebridge-hue instead of through the Hue bridges?

I want to see if reducing the memory footprint of the homebridge-hue accessories would make a difference, e.g. by:
- Dropping string characteristics like `Resource` or `Last Updated` (`Resource` is reported in the debug log, but I would miss `Last Updated` - would be a config.json setting);
- Dropping the `BridgingState` service (see https://github.com/KhaosT/HAP-NodeJS/issues/408);
- Combining all lights in a room in a single accessory (see #43) (cf. combining the services for the Hue motion sensor in a single accessory).

**Comment by ebaauw** [comment]
v0.5.3 no longer exposes the `Resource` characteristic, when you specify `"resource": false` in config.json.  @yaudouin, if you're up to it, could you test this version and see if this setting allows you to add more accessories before the sync fails?

Note: `Resource` is a read-only custom characteristic holding a string value for the Hue bridge resource (e.g. `/lights/1` or `/sensors/2`) corresponding to a service exposed by homebridge-hue.  The iOS builtin Home app doesn't support custom characteristics, but other apps, like Eve do.

**Comment by yaudouin** [comment]
Thank you Erik, I am French and my English is maybe a bit hazardous.

I have a total of 7 bridges:

1 hue bridge: 14 bulbs
1 hue bridge: 10 bulbs
1 hue bridge: 7 bulbs
1 bridge homebridge (containing the 3 hue bridge): 40 accessories = 3 hue bridge, 6 motion detectors + temperature, 25 osram plugs
1 homebridge bridge (containing NEST accessories): 1 thermostat, 3 smoke detector, 3 monoxide detector
1 homebridge bridge (containing just my alarm via http-security-system)
1 homebridge bridge (containing 25 peripherals type specific motion detector via camera, PC ping, etc.)
1 Eve Outdoor (containing 1 temperature probe, 1 humidity probe)

Total: about 102 accessories

I do not expose my DimmerSwitches (I've got 20 accessories connected on my 3 hue bridges)

I also have 12 scenes (synced with Hue)

I have 17 rooms

No automation on Homekit (delegates on the Domoticz solution because of the reliability of homkit)

**Comment by yaudouin** [comment]
I had never reached the limit before this homebridge-hue update. But it is because the latter has exposed my DimmerSwitches and my CLIPGenericStatus

**Comment by yaudouin** [comment]
Yes I can test version 0.5.3 by exposing my DimmerSwitches, adding "resource": false in config.json and checking if iCloud synchronization continues to work

**Comment by ebaauw** [comment]
homebridge v0.4.21 no longer creates the (hidden) `BridgingState` service.  homebridge-hue v0.5.6 forces homebridge v0.4.21, see the [Release Notes](https://github.com/ebaauw/homebridge-hue/releases/tag/v0.5.6).
