### ISSUE TITLE
Requesting config and lights every 5 seconds

### ISSUE THREAD

**Issue by robboz4** [ebaauw/homebridge-hue#134]
Hi!

I installed this plugin to access my original Philips Hue. It works except for a request every 5 seconds to get the config and lights
7/21/2017, 12:13:24 PM] [Hue] Club-Robbo: hue bridge request #41: get /config
[7/21/2017, 12:13:25 PM] [Hue] Club-Robbo: hue bridge request #41: ok
[7/21/2017, 12:13:25 PM] [Hue] Club-Robbo: hue bridge request #42: get /lights
[7/21/2017, 12:13:25 PM] [Hue] Club-Robbo: hue bridge request #42: ok

Is there a config parameter to stop this? 

Also as a side note I get lamps that will intermittently turn off when they shouldn't. Is that a Homebridge issue or a result of one of the above messages timing out?

**Comment by ebaauw** [comment]
No, this is by design.  As the Hue bridge offers no notifications, homebridge-hue, like any Hue app, needs to poll the bridge, retrieving it's state every five seconds.  You can set the polling interval using the `heartrate` parameter in config.json, or using the custom characteristic in the bridge service.  You'd need another HomeKit app for that, as the iOS built-in Home app doens't support custom characteristics.

These debug messages actually only show when homebridge is started with `-D`.

**Comment by robboz4** [comment]
Thanks for the quick reply. I know the messages are only on debug as I was setting up the home bridge system I wanted to learn what was going on. I'll look into the heartrate option. 

Thanks once again.
