### ISSUE TITLE
Lights Randomly Turn Off

### ISSUE THREAD

**Issue by ljcaswell** [ebaauw/homebridge-hue#137]
I have this running with three lights in my living room. It runs fine, lights are on, then randomly one of them will turn off. Then another a few minutes later. I can turn them back on using the Home app, then a few minutes later, they'll turn off again. 

It was running smoothly until I updated to the latest version. Killing Homebridge prevents this from happening. I do not have any automations set up.

Any ideas?

**Comment by robboz4** [comment]
I had this problem until I changed the heart rate setting to 30 seconds from its default of 5 seconds.

**Comment by ljcaswell** [comment]
Thanks. I'll try that later and let you know.

**Comment by ebaauw** [comment]
What does the homebridge log/output look like?  What's your config.json?  Did you set `wallSwitch`?

Changing the heartrate only changes the rate at which homebridge-hue polls the Hue bridge.  Setting it to 30 seconds means it can take up to 30 seconds, before a change on the Hue bridge is reflected in HomeKit.  If you only control your lights from HomeKit that would be fine, but if you use Hue apps, or even rules on the Hue bridge (for motion sensors, dimmer switches, etc) it will be a lousy experience.

**Comment by robboz4** [comment]
I have a Weemo, Samsung TV and the Pi temperature plugin installed and running on a Pi3. I have an IFTTT setting to turn on the hue and weemo at sunset. Until I moved the heart rate to 30, I would get glitches on the hue lights. One would go off or dim. After I changed the heart rate to 30 and no other changes, no more hue hiccups. Could it be that polling  the hue bridge, and mine is an original one, every 5 seconds occasionally caused it to hiccup? It's been over 5 days since the changes and the Pi has not been rebooted or homebridge restarted.
I have no sensors connected to the hue, only the three button switch.
Cheers

**Comment by ebaauw** [comment]
> Could it be that polling the hue bridge, and mine is an original one, every 5 seconds occasionally caused it to hiccup?

No, not when the Hue bridge is functioning normally.  If you run `homebridge -D`, homebridge-hue issues a debug message for each API requests it makes to the Hue bridge.  To change a light, it would have to issue a `put` instead of a `get` request.  It also issues a debug message for each change made directly to the Hue bridge.  Of course, it only sees these changes on a heartbeat, on the `get` of `/lights`.

> I would get glitches on the hue lights. One would go off or dim.

A light going off could be caused by homebridge-hue when `wallSwitch` is set in config.json, but it wouldn't dim a light spontaneously.  With `wallSwitch`, homebridge-hue sets the light off when the bridge reports it as unreachable, assuming this is because the light is powered off using a ... wall switch.  However, when the light is actually still powered and there's just a glitch in the ZigBee network, the light will turn off.  
Unlike the Hue dimmer switches or motion sensors, Hue lights don't support ZigBee attribute reporting - they don't push state changes to the bridge.  Instead, the Hue bridge polls the lights to retrieve their state.  When it doesn't get an answer, it marks the light unreachable.  When it gets an answer the next round, it marks the light as reachable.  
The Hue bridge polls one light at a time, so the interval between polls of the same light depends on the number of lights connected to the bridge (hence the recommended limit of 50 lights, even though technically it can support 64 lights).  When you only have three lights, they'll be polled several times during 30 seconds, so the change that homebridge-hue sees the unreachable state decreases with a longer heartbeat interval.

There's several reports of light glitches on the Hue developers forum.  I'm no fan of allowing outside (cloud-based) solutions, like IFTTT or even the meethue portal access to my home.  You can create a Hue bridge rule to turn on lights at sunset, using the builtin Daylight sensor.  
I would delete all usernames on the Hue bridge (except the one used for homebridge-hue and the Hue apps you really use) to make sure no-one is messing with the bridge.  Also I would double-check the rules and schedules on the bridge to make sure nothing funny is happening.  I you want to, you could attach a dump your bridge state here, so I can have a look (see **Troubleshooting** in the README).

**Comment by robboz4** [comment]
Let's leave it running a while longer as I'm just getting started with home kit and homebridge, and things seem to be stable. If I hit issues while moving forward I'll come back with the file for analysis. Thanks for info above.
