### ISSUE TITLE
iOS 11 Beta 4 Error

### ISSUE THREAD

**Issue by marcodesantis71** [ebaauw/homebridge-hue#138]
Hi,

I just installed iOS 11 Beta 4 and now hue plugin not working.

No error on the logs of homebidge. The Home App return "not responding" error.

Another iPhone with iOS 10 Works fine.

**Comment by ebaauw** [comment]
That would be a communication issue between homebridge and HomeKit on iOS 11, most likely unrelated to homebridge-hue.  Do you use other plugins with homebridge?  Do the accessories exposed by these respond?

If you start homebridge manually using
```
DEBUG=* homebridge -D
```
it issues debug messages on the communication with HomeKit devices.  Maybe that would give a clue as to what's happening.

I only tried the second beta of iOS 11 briefly, and ran into a lot of HomeKit related issues.  Not sure if HomeKit likes being synced between iOS 10 and iOS 11 beta.  You might want to setup a separate instance of homebridge and homebridge-hue and pair that with iOS 11 beta using a separate iCloud user ID.

**Comment by ebaauw** [comment]
Just installed iOS 11 public beta 3.  As with the fist (?) public beta it seems to work (more or less), except that Home reports a _cannot configure accessory_ error while stepping through my devices after pairing homebridge.  It happens at the same light as before, which Matthias' Home app shows the accessory as blocked (but won't unblock, since it isn't a bridge?).  Not sure if it's related to the light or just the _n_-th accessory it tries to configure.
