### ISSUE TITLE
Warning icon eve app

### ISSUE THREAD

**Issue by Nastra888** [ebaauw/homebridge-hue#144]
Hello Erik,

I have a question about a bug that I noticed.

With my Osram Gardenspots I get a any time a symbol that this would not be accessible.

But i can still be controlled.

Do you have an idea why this is?

![img_1648](https://user-images.githubusercontent.com/27686185/29015680-4fc54146-7b4f-11e7-9097-8b020c2fe39e.PNG)
![img_1649](https://user-images.githubusercontent.com/27686185/29015681-4fef69da-7b4f-11e7-8ae3-da78ec71c87c.PNG)

**Comment by ebaauw** [comment]
Yes, if you click on the warning, it should tell you something like the device reports fault status 1 (I don't know how Eve says that in German).  homebridge-hue sets this status when the Hue bridge reports the light as unreachable.  You should see an error in the Hue app as well.

The bug is with the Hue bridge, as it marks the light as unreachable, when it isn't.  See https://github.com/ebaauw/homebridge-hue/issues/80.

**Comment by Nastra888** [comment]
All clear, many thanks for the info.
