### ISSUE TITLE
Support recalling bridge scenes from HomeKit

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-hue#158]
Picking up from @snozzlebert comment in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/98.

> Although, recalling scenes using a HomeKit switch in homebridge-hue would be nice ;) 

I suppose I could implement a switch service for each scene in a group accessory (cf. the services under the bridge/gateway accessory for schedules).  The scene would be recalled when setting the switch _On_ and the switch would revert to _Off_ automatically after a second or so.

> Would result in one API call, instead of one for every light in a HomeKit scene.

Currently, I use a CLIPGenericFlag to achieve one API call (and, more importantly, one ZigBee request).  From HomeKit automations, I only set the room master switch and I recall the Hue/deCONZ scene from a bridge/gateway rule.

Achieving one API call (and fewer ZigBee requests) is why included the possibility to expose bridge/gateway groups to HomeKit, but I find I'm not using this at all.  I'm seriously constrained by the 99 accessories per HomeKit bridge limit and simply cannot afford an additional HomeKit accessory for each bridge/gateway group.

And here's the dilemma:
- In the deCONZ scene setup, this would work "naturally", as scenes are linked to the group, but, as said, you'll run into the HomeKit limit pretty quickly.  As a workaround I could actually list the LightBulb services under the group accessory instead of under a separate accessory per light, but then you'd probably want _Room_ groups to make sure a light only sits in one group.
- In the Hue scene setup, all scenes are actually stored under `/groups/0`.  This is _not_ the 0x0000 ZigBee group, but a hidden regular group to which each light is added after pairing.  I would only need to expose `/groups/0` (or expose the scenes under the bridge/gateway accessory), but then there's no possibility to recall a scene for a particular group only.  I could expose the scenes under all groups, but you'd run into the same issues as for the deCONZ scene setup (too many accessories) and you would see the scene in groups that don't share lights with the scene.  Fixing that would definitely be a disproportionate amount of "extra work" ;-)

**Comment by snozzlebert** [comment]
I don't think I need this anymore.
For lights in the same armature I expose the LightGroup to homebridge-hue (#227 is probably fixed in the next deCONZ release) 

I'm also using CLIPGenericStatus sensors similar to the SceneCycle sensors created by the Hue bridge for dimmer switches. In deCONZ I use rules to map value changes of the CLIPGenericStatus (condition) to a specific recall scene action. E.g. 0 to off, 1 to /groups/1/scenes/1/recall, etc.
I expose these "scene sensors" to homebridge-hue. In the Eve app I'm able to configure HomeKit scenes to set a specific value for the CLIPGenericStatus sensor. 

Advantages:
- This technique can be used for deCONZ and the Philips Hue bridge. 
- It is possible to use only one dummy CLIPGenericStatus to be able to recall many scenes, so you don't hit the 99 accessories per HomeKit bridge limit.

Disadvantage:
- You need configuration in two places. For every scene you want to be able to recall in HomeKit you need a rule in deCONZ/Hue and a mapping in HomeKit.
