### ISSUE TITLE
MultiCLIP explanation 

### ISSUE THREAD

**Issue by jpaquino3** [ebaauw/homebridge-hue#164]
I am at a loss on which file I need to edit for MultiCLIP. Would you mind explaining in greater detail? Thanks!

**Comment by ebaauw** [comment]
MultiCLIP is a trick to combine multiple CLIP sensors on the Hue bridge into one HomeKit accessory, to avoid hitting the HomeKit limit of 99 accessories per HomeKit bridge.   It's very much like how the Hue motion sensor is exposed: one HomeKit accessory with multiple services (one for each resource) instead of a different accessory per resource.

You don't need to edit any file, you just need to create your CLIP sensors on the Hue bridge, with the following attributes:
- `manufacturername` must be `"homebridge-hue"`;
- `modelid` must be equal to `type` (so `CLIPGenericFlag`, `CLIPGenericStatus`, ...);
- `uniqueid` must be unique and of the form `"`_id_`-`_subtype_`"`.  All CLIP sensors with the same _id_ are then combined into one accessory.

For example, I've created the following sensors to control my Living Room (this is on deCONZ, but it's the same for the Hue bridge):
```json
{
  "config": {
    "on": true,
    "reachable": true
  },
  "etag": "b559f5b22f93fea07906a679c8c56932",
  "manufacturername": "homebridge-hue",
  "modelid": "CLIPGenericFlag",
  "name": "Living Room",
  "state": {
    "flag": true,
    "lastupdated": "2017-09-19T20:46:14"
  },
  "swversion": "1",
  "type": "CLIPGenericFlag",
  "uniqueid": "/sensors/220-220"
}
```
and
```json
{
  "config": {
    "on": true,
    "reachable": true
  },
  "etag": "c0546974f862e1b1c79ce10b02ab28d8",
  "manufacturername": "homebridge-hue",
  "modelid": "CLIPGenericStatus",
  "name": "Living Room Status",
  "state": {
    "lastupdated": "2017-09-19T20:46:22",
    "status": 1
  },
  "swversion": "-1,3",
  "type": "CLIPGenericStatus",
  "uniqueid": "/sensors/220-221"
}
```
In HomeKit, this becomes:
![img_0009](https://user-images.githubusercontent.com/22179355/30615522-7bb34098-9d8f-11e7-9ded-874761f81538.PNG)
Note how I (ab)use `swversion` to set the allowed values for the `status`, so Eve adjust the slider accordingly.

Another example is my [virtual weather station](https://github.com/ebaauw/homebridge-hue/wiki/Getting-Started#242-virtual-weather-station), for which I've created the following:
```json
{
  "config": {
    "on": true,
    "reachable": true
  },
  "etag": "0f293e90fd4625487b7a509cc827f352",
  "manufacturername": "homebridge-hue",
  "modelid": "CLIPHumidity",
  "name": "Terrace Humidity",
  "state": {
    "humidity": 7400,
    "lastupdated": "2017-09-19T20:50:04"
  },
  "swversion": "0",
  "type": "CLIPHumidity",
  "uniqueid": "/sensors/340-347"
}
```
```json
{
  "config": {
    "on": true,
    "reachable": true
  },
  "etag": "0f293e90fd4625487b7a509cc827f352",
  "manufacturername": "homebridge-hue",
  "modelid": "CLIPPressure",
  "name": "Terrace Air Pressure",
  "state": {
    "lastupdated": "2017-09-19T20:50:04",
    "pressure": 1020
  },
  "swversion": "0",
  "type": "CLIPPressure",
  "uniqueid": "/sensors/340-348"
}
```
```json
{
  "config": {
    "on": true,
    "reachable": true
  },
  "etag": "0f293e90fd4625487b7a509cc827f352",
  "manufacturername": "homebridge-hue",
  "modelid": "CLIPTemperature",
  "name": "Terrace Temperature",
  "state": {
    "lastupdated": "2017-09-19T20:50:04",
    "temperature": 1280
  },
  "swversion": "0",
  "type": "CLIPTemperature",
  "uniqueid": "/sensors/340-349"
}
```
This becomes:
![img_0010](https://user-images.githubusercontent.com/22179355/30615797-59750538-9d90-11e7-963f-eec1822512f7.PNG)

**Comment by jpaquino3** [comment]
Thank you so much!

**Comment by ebaauw** [comment]
As of v0.8.4, MultiCLIP resources are created using resourcelinks, like:
```json
{
  "classid": 1,
  "description": "multiclip",
  "links": [
    "/sensors/347",
    "/sensors/348",
    "/sensors/349"
  ],
  "name": "homebridge-hue",
  "owner": "xxxxxxxxxx",
  "recycle": false,
  "type": "Link"
}
```
You no longer need to set the `manufacturername`, `modelid`, and `uniqueid` of the `/sensors` resource to create a MultiCLIP accessory, as described above.  This method still works, but will be deprecated.

Similarly, you can create a MultiLight resource, to combine multiple lights (e.g. in a single chandelier) into one accessory:
```json
{
  "classid": 1,
  "description": "multilight",
  "links": [
    "/lights/221",
    "/lights/222",
    "/lights/223",
    "/lights/224",
    "/lights/225",
    "/lights/226"
  ],
  "name": "homebridge-hue",
  "owner": "xxxxxxxxxx",
  "recycle": false,
  "type": "Link"
}
```

The serial number and the name for the MultiLight or MultiCLIP accessory are taken from the first (valid) resource in `links`.

Run `homebridge -D` to see debug messages:
```
[2018-3-10 11:49:01] [Hue] pi2: /resourcelinks/221: 6 multilight entries
[2018-3-10 11:49:01] [Hue] pi2: /resourcelinks/347: 3 multiclip entries
...
[2018-3-10 11:49:01] [Hue] pi2: 0017880100xxxxxx: dresden elektronik MultiLight "Living Room 1"
[2018-3-10 11:49:01] [Hue] pi2: /lights/221: Extended color light "Living Room 1"
[2018-3-10 11:49:01] [Hue] pi2: /lights/222: Extended color light "Living Room 2"
[2018-3-10 11:49:01] [Hue] pi2: /lights/223: Extended color light "Living Room 3"
[2018-3-10 11:49:01] [Hue] pi2: /lights/224: Extended color light "Living Room 4"
[2018-3-10 11:49:01] [Hue] pi2: /lights/225: Extended color light "Living Room 5"
[2018-3-10 11:49:01] [Hue] pi2: /lights/226: Extended color light "Living Room 6"
...
[2018-3-10 11:49:01] [Hue] pi2: 00212EFFFFxxxxxx-347: dresden elektronik MultiCLIP "Terrace Weather"
[2018-3-10 11:49:01] [Hue] pi2: /sensors/347: CLIPTemperature "Terrace Weather"
[2018-3-10 11:49:01] [Hue] pi2: /sensors/348: CLIPHumidity "Terrace Weather"
[2018-3-10 11:49:01] [Hue] pi2: /sensors/349: CLIPPressure "Terrace Weather"
```

**Comment by ooii** [comment]
Hi,

I wanted to create a `MultiCLIP` accessory from a Xiaomi temperature/pressure/humidity sensor, which ids are resp. 44,45, and 59.
I used `ph`  as follows:

```
ph post /resourcelinks '{
	"classid": 1,
	"description": "multiclip",
	"links": [
		"/sensors/44",
		"/sensors/45",
		"/sensors/59"
	],
	"name": "homebridge-hue",
	"recycle": false
}'
```

And that has created a `resourcelink`. However, when restarting `homebridge-hue`, I have the following output:

```
[2018-5-24 23:35:18] [Hue] conBee: /resourcelinks/10: /sensors/44: ignoring unsupported multiclip resource
[2018-5-24 23:35:18] [Hue] conBee: /resourcelinks/10: /sensors/45: ignoring unsupported multiclip resource
[2018-5-24 23:35:18] [Hue] conBee: /resourcelinks/10: /sensors/59: ignoring unsupported multiclip resource
```

Should I first create `CLIPTemperature`, `CLIPHumidity`, and `CLIPPressure` and assign them to the `resourcelink`?

Thanks.

**Comment by ebaauw** [comment]
> I wanted to create a MultiCLIP accessory from a Xiaomi temperature/pressure/humidity sensor

Why on earth would you want to do that?

**Comment by ooii** [comment]
Because I thought that the three sensors are exposed as three accessories. Why did I think that? No idea.
