### ISSUE TITLE
Remote button as doorbell

### ISSUE THREAD

**Issue by jsve** [ebaauw/homebridge-hue#179]
I have modded an Ikea remote to use as an extension for my doorbell (built into the frame so nothing looks altered from the outside). It shows up like a programmable switch right now (which I guess is logical :) ) but I'd really like it to be identified as a doorbell-service by HomeKit. Is this maybe an enhancement you might consider (I'd be happy to provide a guide for others who are looking for an easy non-intrusive way of adding a zigbee-doorbell). If not; do you have any suggestions for how I could get this to work?

I'm on deconz and am using the centre button as doorbell. The other buttons are not in use at the moment.

**Comment by ebaauw** [comment]
Interesting idea!

I haven't looked at the HomeKit Doorbell service before, but I don't suppose it would be a big deal for homebridge-hue.  Playing with the HomeKit accessory simulator however, Apple's Home app seems to support the Doorbell service only as part of a Video Doorbell accessory, not as a bridged accessory.  Do you know of any other homebridge plugins that expose a Doorbell?

The main issue for homebridge-hue is how to specify that you want this particular switch to be exposed as doorbell.  I'm very reluctant to make config.json more complicated (as a lot of issues relate to config.json errors), and you would need to specify the switch's mac address (or sensor resource ID), unless you want all your switches to turn into doorbells.

**Comment by jsve** [comment]
The switches Mac-adress, is that whats exposed as Characteristic.SerialNumber? But thats for all buttons? Is there another way to select a specific button, or is it just the int that is set here: https://github.com/ebaauw/homebridge-hue/blob/544c98a17dbd18afd0293ccba2999fd3cf632f99/lib/HueSensor.js#L155

Or is it the name that is the identifier?

Not sure about if it is possible to add doorbell separately. Like you, I played around with the Accessory Simulator. I can add just a doorbell to a service, but that accessory is then not recognised in the Home app. If I add a IP-camera they are both recognised. In my case I would like to add an IP-camera from one service and connect that to a doorbell (the modded IKEA-switch). Do you know if that is possible?

**Comment by jsve** [comment]
Just remembered: A motion sensor in the same room as the camera will trigger a camera feed in the notification. This works even if there are two separate accessories for the camera and the motion sensor.

**Comment by ebaauw** [comment]
This is the most confusing and inconsistent part of HomeKit.  Normally, an _accessory_ is a physical device / gadget, which you can place in a room.  A _service_ is a logical device, like a light bulb, doorbell, video camera, motion sensor, ...   An accessory contains multiple services, one of which, the Accessory Information service, holds the SerialNumber, Manufacturer, Model, FirmwareRevision, and (optionally) HardwareRevision.

Typically, Apple's Home app shows a tile per _service_, not per accessory (even though it labels them `Accessories`).  The exception is the Stateless Programmable Switch, which actually is a service per button: all services of this type are shown as a single tile.  So yes, there's one SerialNumber characteristic (in the Accessory Information service) for all the buttons (Stateless Programmable Switch services in the same accessory).

For a single device, deCONZ (as well as the Hue bridge) typically shows a separate resource for each ZigBee endpoint and/or cluster (the part after the dash in the `uniqueid`).  homebridge-hue re-assembles these resources into a single accessory, based on the ZigBee mac address (the part before the dash in `uniqueid`).  Typically, each resource is exposed as a separate service, except for, again, the Stateless Programmable Switch, where each button is a separate service.

Please read the above paragraphs again.  As I said: it's very confusing.

> The switches Mac-adress, is that whats exposed as Characteristic.SerialNumber? But thats for all buttons? Is there another way to select a specific button, or is it just the int that is set here:

Services are identified by type (UUID) and subtype: https://github.com/ebaauw/homebridge-hue/blob/544c98a17dbd18afd0293ccba2999fd3cf632f99/lib/HueSensor.js#L621

homebridge-hue simply uses an array subscript linked to to the buttonevent value to select the right service: https://github.com/ebaauw/homebridge-hue/blob/544c98a17dbd18afd0293ccba2999fd3cf632f99/lib/HueSensor.js#L789

> Just remembered: A motion sensor in the same room as the camera will trigger a camera feed in the notification. This works even if there are two separate accessories for the camera and the motion sensor.

Are you sure?  I cannot reproduce this.  The HomeKit Accessory Simulator creates a single video doorbell accessory with multiple services: IP Camera, Microphone, Speaker, Doorbell, Motion Sensor, and, of course, Accessory Information.  Apple's Home app shows this as two (sort of) tiles: one for the camera (incl. bell, microphone and speaker) and one for the motion sensor.  Are you sure the camera and motion sensor in your example are separate accessories (can you assign them to a room separately or has the other also moved when you re-assign one of them) or are they just separate services/tiles?

> Not sure about if it is possible to add doorbell separately

Technically: yes, but it won't do you any good.  I'm afraid, Apple's Home app simply doesn't support the Doorbell service, unless it's part of the Video Doorbell accessory.  Same for Speaker (and Microphone), incidentally, see https://github.com/ebaauw/homebridge-zp/issues/21.  Since Home doesn't support it, I cannot configure it for notifications.

> If I add a IP-camera they are both recognised.

Please double-check: you add a second service to the same accessory.  I think it's actually the other way round (at least in HAS 3.0 (123.1)): you add a Doorbell to an IP Camera.

> In my case I would like to add an IP-camera from one service and connect that to a doorbell (the modded IKEA-switch). Do you know if that is possible?

That would only be possible if both the IP Camera and Doorbell services belong to the same accessory.  And that would only happen, if a single homebridge-plugin would provide this single accessory (and both these services).  I'm sorry, but it's way out of scope for homebridge-hue to expose IP devices not connected to a Hue bridge or deCONZ gateway, let alone IP cameras.

**Comment by jsve** [comment]
Took some screenshots showing the motion sensor as a separate accessory from the IP-camera. I agree that the hue plugin should not have any kind of functionality for IP-cameras! What I'm getting at with this is that it might not have to. The Hue plugin could just expose a motion-sensor (like it already is able to), and when that is placed in the same "room" as the camera, they will work together. **You need to enable notifications from the motion sensor to get notifications.**

I have seen a few other plugins that work just like described above. A button is "faked" as a motion sensor, and then placed together with the camera to make a video-doorbell.

Do you think faking a stateless switch as a motion sensor would be something that can be added to your plugin? I'm thinking that maybe everything could be exposed just the way it is now, but (based on a config flag :P) the user can identify a list of buttons (by MAC and button number, or something) that will also expose them as a motion sensor. If you feel this is to far from the scope of the plugin, could you give some indication of how this might be done? I'm considering either wrapping your plugin and make something that just exposes the fake doorbell (motion sensor). Maybe a fork is the way to go. What do you think?

![screen shot 2017-10-17 at 17 10 35](https://user-images.githubusercontent.com/9053945/31673404-66a2236e-b35f-11e7-9189-4a56917240a1.png)
![screen shot 2017-10-17 at 17 11 04](https://user-images.githubusercontent.com/9053945/31673405-66beb9a2-b35f-11e7-82b1-c40461f71ba5.png)
![img_0974](https://user-images.githubusercontent.com/9053945/31673406-66d5c5b6-b35f-11e7-98e0-922572bd9389.JPG)
![img_0975](https://user-images.githubusercontent.com/9053945/31673407-675b2896-b35f-11e7-84e1-7f90b46dc809.JPG)

**Comment by ebaauw** [comment]
> Took some screenshots showing the motion sensor as a separate accessory from the IP-camera.

Cool!  Got it working like that, exposing a camera accessory from HAS and using an IKEA Trådfri motion sensor exposed by homebridge-hue.

> You need to enable notifications from the motion sensor to get notifications.

That probably did the trick.  Note that the accessories don't "work together", it's Apple's Home app that actually provides the integration. Fun fact: when adding a second camera to the room, I actually get two notifications, one for each camera.

> Do you think faking a stateless switch as a motion sensor would be something that can be added to your plugin?

That's the easy part.  I'll try with my Xiaomi Aqara smart switch first, that looks quite doorbell-ish.

> but (based on a config flag :P) the user can identify a list of buttons (by MAC and button number, or something) that will also expose them as a motion sensor.

That's more elaborate.  Would you still want to use the other buttons as Stateless Programmable Switches, or are you happy with dedicating the remote to a doorbell / motion sensor function (so you'd only need to specify the device, not the button).

**Comment by ebaauw** [comment]
Did some more testing.  The Camera and Motion Sensor accessories need to be in a room other than the default room.  That's why I couldn't get it to work previously.  The integration of the Camera service in the notification only seems to work for a Motion Sensor service, not for an Occupancy Sensor nor a Contact Sensor, even though Home supports notifications for these services as well.

I think I have a better alternative for this functionality, rather than over-complicating config.json.  If you create a CLIPPresence sensor on the deCONZ gateway, homebridge-hue could expose it as Motion Sensor (currently it exposes it as a Occupancy Sensor, but I'll change that).  You can than create a (number of) rule(s) on the gateway, to set the CLIP sensor's `state.presence` to `true` on whatever button(s) you like.  By using the CLIP sensor's `config.duration`, you don't even need a rule to reset `state.presence` to `false` manually.

**Comment by jsve** [comment]
Yep, thats right. I tried almost all of the other types of configuration, with doors, contact sensors and some weird hybrid/nonsense accessories. Seems to work only with motion sensor.

> Would you still want to use the other buttons as Stateless Programmable Switches, or are you happy with dedicating the remote to a doorbell / motion sensor function (so you'd only need to specify the device, not the button).

The main part is of course to get it working at all. Dedicating the entire switch is ok for that. It would be kind of nice, maybe, to be able to use the other buttons for something else. That, however, is more of a cost-issue. I have some ideas of maybe making my own custom buttons, maybe one "I'm home" and one "I'm going", like a big green and red button. But thats nothing I'll be doing for quite a while. And for that, I could just rip apart another IKEA remote :)

> (currently it exposes it as a Occupancy Sensor, but I'll change that)

Wont that break the CLIP sensors for those using that? I'm having problems finding anything about CLIP. Is that like a physical sensor that tells deconz if you are home?

**Comment by ebaauw** [comment]
> Dedicating the entire switch is ok for that.

You might want to check out the [Xiaomi Aqara smart wireless switch](https://www.gearbest.com/access-control/pp_626695.html): just one button, they almost look like a doorbell.

> Wont that break the CLIP sensors for those using that?

I would change them, but I doubt any-one is using that.

> I'm having problems finding anything about CLIP. Is that like a physical sensor that tells deconz if you are home?

A CLIP sensor is best seen as a variable on the gateway, which can be set programmatically, but is exposed like a ZigBee sensor.  See https://github.com/ebaauw/homebridge-hue/wiki/Getting-Started#24-clip-sensors.

**Comment by jsve** [comment]
> You might want to check out the Xiaomi Aqara smart wireless switch: just one button, they almost look like a doorbell.

I'm actually waiting for a couple of Xiaomi-units right now. I'm usually to eager to wait for the delivery times. Haven't found anyone that delivers to Sweden in under like 3 weeks :/

CLIP sensors seem useful! But do they work only on the Hue or with the conrbee aswell?

I might be missing something, but your suggestion is:

- Ikea remote is identified as a multi button, stateless switch (like it already is)
- in home (Home.app) I automate so that every time the button is pressed, the motion sensor (CLIP) is activated
- the flag in the config makes sure that the CLIP times out on its own in like 10 seconds

What I think might get in the way of the above is that motion sensors can not be automated like this.

I only have the HAS motion sensor to play with, so maybe it is possible if you create the sensor from the plugin...

<img width="375" alt="image" src="https://user-images.githubusercontent.com/9053945/31680872-e9129dcc-b375-11e7-95e6-44d34789d325.png">

**Comment by ebaauw** [comment]
> But do they work only on the Hue or with the conrbee aswell?

Now they do ;-)  See #31.

> Ikea remote is identified as a multi button, stateless switch (like it already is)

Yes

> in home (Home.app) I automate so that every time the button is pressed, the motion sensor (CLIP) is activated

No.  Sensors in HomeKit are read-only, so you cannot update them from a HomeKit automation.  You need to update the CLIPPresence `state.presence` through a rule on the deCONZ gateway.  You create the rule (and the CLIPPresence sensor) using the [deCONZ REST API](http://dresden-elektronik.github.io/deconz-rest-doc/rules/).  I've created some [bash scripts](https://github.com/ebaauw/ph.sh) to interact with the API from the command line.

> the flag in the config makes sure that the CLIP times out on its own in like 10 seconds

Yes, `config.duration`, which homebridge-hue actually exposes to HomeKit (but of course, not recognised by Apple's Home app).

So, your CLIPPresence sensor would look like:
```json
{
  "config": {
    "duration": 1,
    "on": true,
    "reachable": true
  },
  "etag": "4a0a9b8e5911b45218432fda48b109f3",
  "manufacturername": "homebridge-hue",
  "modelid": "CLIPPresence",
  "name": "Doorbell",
  "state": {
    "lastupdated": "2017-10-17T16:55:21",
    "presence": false
  },
  "swversion": "0",
  "type": "CLIPPresence",
  "uniqueid": "/sensors/1"
}
```

Assuming the IKEA remote is `/sensors/2`, the rule would look like:
```json
{
  "actions": [
    {
      "address": "/sensors/1/state",
      "body": {
        "presence": true
      },
      "method": "PUT"
    }
  ],
  "conditions": [
    {
      "address": "/sensors/2/state/buttonevent",
      "operator": "eq",
      "value": "1002"
    },
    {
      "address": "/sensors/2/state/lastupdated",
      "operator": "dx"
    }
  ],
  "created": "2017-10-17T19:57:00",
  "etag": "b94441e1ba06facab02ec4b026e64b94",
  "lasttriggered": "none",
  "name": "Doorbell",
  "owner": "xxxxxxxxxxx",
  "periodic": 0,
  "status": "enabled",
  "timestriggered": 0
}
```

**Comment by jsve** [comment]
I'll try this CLIP stuff in a few days. Maybe this weekend. I have managed to get the hardware-parts of my doorbell pretty much working. I wrote up a page about what I have found out and what I ended up with. I hope this can be useful for others wanting to make something like this themselves. I'd happily take any feedback you might have! 

https://github.com/jsve/diy-doorbell-from-ikea-remote

Feel free to link this, where you see fit :)

**Comment by Samfox2** [comment]
For the camera part, I extended the ffmpeg-plugin to a video-doorbell plugin. It starts a small webserver for triggering from any external device with a simple curl command. This could also be useful for others.

**Comment by jsve** [comment]
The CLIP sensor works perfectly with the remote!

## For future reference:
I used the same API key to communicate with the deConz as homebridge-hue is already using. This is found in the config.json.

using curl, these commands are useful, replacing XXX with your gateway IP and YYY with your api-key:

### make CLIP:
```
curl --request POST \
  --url 'http://XXX/api/YYY/sensors?=' \
  --header 'content-type: application/json' \
  --data '{
  "config": {
    "duration": 1,
    "on": true,
    "reachable": true
  },
  "manufacturername": "homebridge-hue",
  "modelid": "CLIPPresence",
  "name": "Doorbell",
  "swversion": "0",
  "type": "CLIPPresence",
  "uniqueid": "/sensors/1"
}
'
```

### get all sensors:
```
curl --request GET \
  --url 'http://XXX/api/YYY/sensors?='
```

For me, the IKEA remote had ID 1 and the CLIP got ID 2. To set the rule I used:
```
curl --request POST \
  --url 'http://XXX/api/YYY/rules?=' \
  --header 'content-type: application/json' \
  --data '{
  "actions": [
    {
      "address": "/sensors/2/state",
      "body": {
        "presence": true
      },
      "method": "PUT"
    }
  ],
  "conditions": [
    {
      "address": "/sensors/1/state/buttonevent",
      "operator": "eq",
      "value": "1002"
    },
    {
      "address": "/sensors/1/state/lastupdated",
      "operator": "dx"
    }
  ],
  "created": "2017-10-17T19:57:00",
  "etag": "b94441e1ba06facab02ec4b026e64b94",
  "lasttriggered": "none",
  "name": "Doorbell",
  "owner": "xxxxxxxxxxx",
  "periodic": 0,
  "status": "enabled",
  "timestriggered": 0
}'
```

I needed to remove some of the lines from your code above, @ebaauw. I think a few are still not necessary but deConz accepts the requests like I put them above.

I think we can consider this issue closed. Next project will be connecting this to a camera somehow, but like we said, probably not as part of this plugin.

Keep up the good work! :)
