### ISSUE TITLE
Expose timers

### ISSUE THREAD

**Issue by ooii** [ebaauw/homebridge-hue#181]
Hue has introduced timers few weeks ago. These timers allow to trigger an action (eg light blinks) when a timer ends. Is it possible to expose timers to HomeKit, as switched for instance? Thus, we’ll be able to trigger them with the accessories. Thanks.

**Comment by ebaauw** [comment]
> Hue has introduced timers few weeks ago. (...) Is it possible to expose timers to HomeKit

That's just the app, the API has supported them for years.  So has homebridge-hue.  By setting `"schedules": true` in config.json, homebridge-hue exposes an additional custom service for each schedule/timer to the Hue bridge accessory, with a custom `Enabled` characteristic.  Of course, Apple's Home app doesn't support custom services and characteristics, but other apps, like Eve, do:
![img_0011](https://user-images.githubusercontent.com/22179355/31678961-f4509f28-b36f-11e7-8875-e779f04f4894.PNG)

If you create a HomeKit scene in Eve, you can activate it from Apple's Home and use it in rules just fine, even when it contains custom characteristics.

> as switched for instance

I deliberately use a custom service with a custom `Enabled` characteristic instead of the standard `Switch` service and `Power` characteristic to prevent Siri from inadvertently en/disabling the timers when telling her to switch on/off a room.

**Comment by ooii** [comment]
Of course. Thanks @ebaauw.

**Comment by ooii** [comment]
@ebaauw, I have a question that does not concern your plug-in but maybe you can help me.
I have a timer that makes a bulb blink after 2 minutes. When I enable this timer in Eve, the bulb blinks immediately and does not wait for 2 minutes. Is that the expected behavior?

**Comment by ebaauw** [comment]
I wouldn’t know.  I only use timers and schedules for scheduled (recurring) events, not for automation events.  I find these are far better handled by rules, using the `ddx` operator, which allows you to trigger a rule x amount of time after something changed.

**Comment by ooii** [comment]
OK, thanks @ebaauw. 
I have one request (that can be time consuming): can you share with us how you personally use homekit and hue? If you can provide real life examples and how you implement them. For me, it'd be helpful.

**Comment by ebaauw** [comment]
I’ve published most of my scripts configuring the Hue bridge (or deCONZ gateway) in [ph.sh](https://github.com/ebaauw/ph.sh).  There’s some description in the [Wiki](https://github.com/ebaauw/homebridge-hue/wiki/Getting-Started#241-home-automation).
