### ISSUE TITLE
Status fault and not reachable errors

### ISSUE THREAD

**Issue by abrahamw88** [ebaauw/homebridge-hue#187]
Recently some of my hue bulbs have been turning off randomly. When this happens I get two messages in homebridge hue. “Set HomeKit status fault from 0 to 1” and “not reachable: set homekit power from 1 to 0”. These issues started happening once I began using a new dimmer switch. These issues only happen when homebridge is running. I have tried resetting the hue bridge, dimmer switch and my homekit home. Homebridge and homebridge-hue are fully updated. Any ideas?

**Comment by ebaauw** [comment]
> Set HomeKit status fault from 0 to 1

The Hue bridge set the light’s `state.reachable` to false.  This is reflected in the _Status Fault_ characteristic.

> not reachable: set homekit power from 1 to 0

You set `wallSwitch` in config.json, asking homebridge-hue to turn off the light when `state.reachable` is false.  See https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

The bridge sets `state.reachable` to false when it doesn’t receive an answer while polling the light.  Normally this should happen when the light is powered off (indeed, by the traditional wall switch), but quite often there’s just a hiccup in the ZigBee network traffic.  This could be caused by physical conditions (e.g. metal light enclosures blocking the signal to the bulb) or interferance from other (ZigBee or WiFi) networks.

**Comment by abrahamw88** [comment]
Thank you very much for the helpful response. I have changed wallswitch to false. I am just wondering why the lights randomly started becoming unreachable when nothing changed except for the addition of a hue dimmer.

**Comment by abrahamw88** [comment]
I will close this once I’m sure they are behaving correctly again.

**Comment by ebaauw** [comment]
> I am just wondering why the lights randomly started becoming unreachable when nothing changed except for the addition of a hue dimmer.

As am I.  The dimmer, like any battery-operated device is a ZigBee end device, not a router participatng in forming the mesh network.  Also it uses attribute reporting, so it wouldn’t slow down the rate at which a light is polled, like adding mode lights would.  Maybe one of your neighbours got a new WiFi or even ZigBee network?  You good try and place the bridge differently or change the ZigBee channel.  ZigBee channel 25 has least overlap with the WiFi channels.

**Comment by abrahamw88** [comment]
Yea it’s slightly odd because the issue started happening right after I setup the dimmer in the hue app and it didn’t go away even when I reset the dimmer and took the batteries out for a few days. I was thinking about changing the channel if it continues to give me unreachable errors.

**Comment by deanlyoung** [comment]
I’ve been noticing every once in a while my hue lights will report as disconnected. I don’t have a dimmer switch, and I’ve only noticed it since upgrading to iOS 11.0.3. Any chance it could be iOS or the HomeKit server? Sorry I don’t have any more specifics at the moment...

**Comment by ebaauw** [comment]
When HomeKit shows an accessory as disconnected, it’s a hiccup in the communication between your iPhone and the Hue bridge.  I’d recommend using wired ethernet between your Hue bridge, Apple TV and server running homebridge.

_Status Fault_ or `state.reachable` is a hiccup in the communication between the bridge and the bulb, something entirely different.

**Comment by abrahamw88** [comment]
deanlyoung yea it likely is not iOS since as ebaauw said this is an issue only between the bridge and the bulbs. Ebaauw I have had everything connected by Ethernet except for the Apple TV which is a 3rd gen so I don’t believe it participated in homekit or hue at all. I also have changed the zigbee channel but unfortunately I am still getting status faults in homebridge though it isn’t turning the lights off now because I changed the wallswitch setting.

**Comment by deanlyoung** [comment]
I misunderstood. I thought these disconnections were also appearing in the Home app. Changes in Home app need to propagate to the HomeKit in iCloud, too, so the Home app momentarily reporting them as unreachable could be an issue with HomeKit.

**Comment by abrahamw88** [comment]
I suppose.. well I am still getting the status faults in homebridge but at least they aren’t turning the lights off now. So I guess I can close this?

**Comment by ebaauw** [comment]
> so the Home app momentarily reporting them as unreachable could be an issue with HomeKit

Yes, I think this is a HomeKit issue, unrelated to homebridge (or homebridge-hue).  People also report having this issue using the gen2 Hue bridge instead of homebridge, see https://developers.meethue.com/content/homekit-no-response-issue.

> well I am still getting the status faults in homebridge

This is caused by the Hue bridge marking the light's `state.reachable` false, also unrelated to homebridge-hue.  See also https://developers.meethue.com/content/reachable-state.

> So I guess I can close this?

Yes, I'll do that.
