### ISSUE TITLE
Xiaomi WXKG02LM switch

### ISSUE THREAD

**Issue by AntiHeld889** [ebaauw/homebridge-hue#203]
Hey Erik,
When you have a chance, would you mind adding the following sensor/switch to the whitelist?

[RaspBee] deCONZ-GW: /sensors/5: warning: ignoring unknown ZHASwitch sensor {"config":{"on":true,"reachable":true},"ep":1,"etag":"565df762c5e85c025b3a720071154a4f","manufacturername":"LUMI","mode":1,"modelid":"lumi.sensor_86sw2","name":"lumi.sensor_86sw2","state":{"buttonevent":2002,"lastupdated":"2017-11-03T20:35:00"},"swversion":"20160517","type":"ZHASwitch","uniqueid":"00:15:8d:00:01:64:15:31-01-0006"}

**Comment by ebaauw** [comment]
Switches need a bit more work, as I need to map the `buttonevent` values to the buttons and  actions in HomeKit.  Is this the switch?  https://github.com/dresden-elektronik/deconz-rest-plugin/commit/e395207899d4f6c653a25328bf5419073ea850a9

So it would be exposed to HomeKit as a three-button switch (left, right, both) with only _Single Press_ for each button?

**Comment by AntiHeld889** [comment]
Yes this is the Switch. Yes it would exposed as a three-button switch with Single Press :)

**Comment by ebaauw** [comment]
In v0.5.42.  Please report whether it works - I cannot test it myself.

Note that support for this switch is not yet included in a deCONZ release, so you need to compile the REST API plugin yourself, from the latest GitHub commit.

**Comment by AntiHeld889** [comment]
Yes it's working perfect. Thanks

**Comment by flomeister88** [comment]
Hi Erik,
there seems to be a bug for me with this switch: I got 2 of these connected to my deconz-Gateway (v2.04.99). Every time I start homebridge, I get this error:
`[2018-1-3 22:22:02] [Hue] Initializing platform accessory 'lumi.sensor_86sw2 (2)'...
[2018-1-3 22:22:02] [Hue] Error: Cannot add a Service with the same UUID '00000089-0000-1000-8000-0026BB765291' and subtype 'Left' as another Service in this Accessory.`
If I start homebridge manually and look at the logs while pressing the buttons, I can see the following:
`[2018-1-3 22:39:41] [Hue] lumi.sensor_86sw2 Both: homekit button single press
[2018-1-3 22:39:43] [Hue] lumi.sensor_86sw2 Left: homekit button single press
[2018-1-3 22:39:45] [Hue] lumi.sensor_86sw2 Right: homekit button single press
[2018-1-3 22:39:47] [Hue] lumi.sensor_86sw2 Left: homekit button single press
[2018-1-3 22:39:49] [Hue] lumi.sensor_86sw2 (2) Right: homekit button single press
[2018-1-3 22:39:50] [Hue] lumi.sensor_86sw2 (2) Left: homekit button single press
[2018-1-3 22:39:51] [Hue] lumi.sensor_86sw2 (2) Both: homekit button single press`

So it seems that the switches are somehow connected to the homebridge, but with that error, connecting via homekit is not possible.

By excluding all sensors in the config.json (=false), there is no error.

Did I miss something here?

Thanks in advance!

**Comment by ebaauw** [comment]
What version of homebridge-hue are you running?  Did you recently update or has this error been there for a longer time?

**Comment by flomeister88** [comment]
I had the error with v0.5.49, updated to v0.5.57, but still the same problem.
These are my current program versions:
homebridge-hue v0.5.57, node v8.9.3, homebridge v0.4.33, deCONZ-GW: deCONZ gateway v2.4.99, api v1.0.4

**Comment by ebaauw** [comment]
Could you please attach the debug dump the homebridge-hue makes on startup?  I suspect the switch uses multiple `/sensors` resources, or you have a stale resource on your gateway.  Could you also post a screenshot what the switch looks like in the deCONZ GUI: endpoints and clusters?

**Comment by flomeister88** [comment]
hope this is the debug you meant:

> [2018-1-4 00:50:29] [Hue] deCONZ-GW: gateway request 3: ok
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: gateway request 4: get /resourcelinks
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: gateway request 4: ok
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/1: IKEA of Sweden TRADFRI wireless dimmer (ZHASwitch) "TRADFRI wireless dimmer "
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/2: IKEA of Sweden TRADFRI remote control (ZHASwitch) "Schlafzimmer Remote"
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/3: CLIPGenericStatus excluded
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/4: CLIPGenericStatus excluded
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/5: LUMI lumi.weather (ZHATemperature) "Multisensor Küche"
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/6: LUMI lumi.weather (ZHAHumidity) "Multisensor Küche"
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/7: LUMI lumi.weather (ZHAPressure) "Multisensor Küche"
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/8: LUMI lumi.sensor_motion.aq2 (ZHALightLevel) "Bewegungsmelder Flur"
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/9: LUMI lumi.sensor_motion.aq2 (ZHAPresence) "Bewegungsmelder Flur"
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/10: LUMI lumi.sensor_magnet.aq2 (ZHAOpenClose) "Fenster Balkon rechts"
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/11: LUMI lumi.sensor_magnet.aq2 (ZHAOpenClose) "Fenster Balkon links"
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/12: LUMI lumi.sensor_86sw2 (ZHASwitch) "lumi.sensor_86sw2 (3)"
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/13: LUMI lumi.sensor_86sw2 (ZHASwitch) "lumi.sensor_86sw2 (3)"
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/14: LUMI lumi.sensor_86sw2 (ZHASwitch) "lumi.sensor_86sw2 (3)"
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/15: LUMI lumi.sensor_86sw2 (ZHASwitch) "lumi.sensor_86sw2"
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/16: CLIPPresence excluded
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /sensors/17: CLIPGenericStatus excluded
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: 13 sensors
> [2018-1-4 00:50:29] [Hue] deCONZ-GW: /lights/1: IKEA of Sweden TRADFRI bulb E27 CWS opal 600lm (Color light) "Stehlampe Wohnzimmer"
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: /lights/2: Philips LWB006 (Dimmable light) "Wohnzimmer Decke 1"
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: /lights/3: Philips LWB006 (Dimmable light) "Wohnzimmer Decke 2"
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: /lights/4: Philips LCT001 (Extended color light) "Wohnzimmer Decke Farbe"
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: /lights/5: IKEA of Sweden TRADFRI bulb GU10 W 400lm (Dimmable light) "Küche 1"
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: /lights/6: IKEA of Sweden TRADFRI bulb GU10 W 400lm (Dimmable light) "Flur oben"
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: /lights/7: IKEA of Sweden TRADFRI bulb E14 WS opal 400lm (Color temperature light) "Flur Bad"
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: /lights/8: IKEA of Sweden TRADFRI bulb E27 opal 1000lm (Dimmable light) "Arbeitszimmer Decke"
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: /lights/9: Philips LWB006 (Dimmable light) "Flur unten"
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: /lights/10: Philips LCT001 (Extended color light) "Schlafzimmer Decke"
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: /lights/12: IKEA of Sweden TRADFRI bulb GU10 WS 400lm (Color temperature light) "Küche 2"
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: /lights/13: OSRAM LIGHTIFY Outdoor Flex RGBW (Extended color light) "Lichtstreifen"
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: 12 lights
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: 0 groups
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: 0 schedules
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: 0 rules
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: 21 accessories
> [2018-1-4 00:50:30] [Hue] Initializing platform accessory 'deCONZ-GW'...
> [2018-1-4 00:50:30] [Hue] deCONZ-GW: 2 services
> [2018-1-4 00:50:30] [Hue] Initializing platform accessory 'TRADFRI wireless dimmer '...
> [2018-1-4 00:50:30] [Hue] Initializing platform accessory 'Schlafzimmer Remote'...
> [2018-1-4 00:50:30] [Hue] Initializing platform accessory 'Multisensor Küche'...
> [2018-1-4 00:50:30] [Hue] Initializing platform accessory 'Bewegungsmelder Flur'...
> [2018-1-4 00:50:30] [Hue] Initializing platform accessory 'Fenster Balkon rechts'...
> [2018-1-4 00:50:30] [Hue] Initializing platform accessory 'Fenster Balkon links'...
> [2018-1-4 00:50:30] [Hue] Initializing platform accessory 'lumi.sensor_86sw2 (3)'...
> [2018-1-4 00:50:30] [Hue] Error: Cannot add a Service with the same UUID '00000089-0000-1000-8000-0026BB765291' and subtype 'Left' as another Service in this Accessory.

I had a look at the deconz GUI, and now it gets really weird (at least for my limited understanding;)):
There is a node, I do not recognize called 8xDE5; if I delete it, it just re-appears out of nowhere after a while.
<img width="1157" alt="screenshot 2018-01-04 01 16 54" src="https://user-images.githubusercontent.com/20266524/34546181-8643c8c8-f0f2-11e7-9910-a20ac901597a.png">

Also the switches show different information.
Switch 1:
<img width="358" alt="screenshot 2018-01-04 01 22 48" src="https://user-images.githubusercontent.com/20266524/34546206-97fdea30-f0f2-11e7-9d58-1f4b7320fc15.png">

Switch 2:
<img width="341" alt="screenshot 2018-01-04 01 47 42" src="https://user-images.githubusercontent.com/20266524/34546191-8e8f552e-f0f2-11e7-82d3-cfc78f08bf81.png">

**Comment by ebaauw** [comment]
No, sorry, I meant the `homebridge-hue.json.gz` file, see https://github.com/ebaauw/homebridge-hue#debug-dump-file.  This log does show that there’s four resources for the 64sw2 switches.  Also, the name has changed, `lumi.sensor_86sw2 (3)` instead of `lumi.sensor_86sw2 (2)`, since your previous log?

I read in the deCONZ sources that the sensor has indeed three endpoints, but deCONZ only creates a resource for the first.  The left switch, Switch 2, looks like what I’d expect, but the right, Switch 1, doesn’t.  The second endpoint definitely looks odd, very non-Xiaomi, and suspiciously like @Nastras’  funny temperature sensor in https://github.com/ebaauw/homebridge-hue/issues/245.  @manup, do you have any idea what’s happening here?

**Comment by flomeister88** [comment]
I can explain the name change: I reset and re-added both sensors in the meantime, because I thought it might solve the problem with the odd looking endpoint from switch 2 (but unfortunately it did not work like I had in mind).
Unfortunately I do not get this dump file, when I get the error. Only when excluding the sensors, like mentioned before, the file is created:
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/1602868/homebridge-hue.json.gz)

**Comment by flomeister88** [comment]
Ok, today I had a fresh look on the problem and it seems to be solved now. 

Here is what I did: 
I checked the debug dump and the deconz REST-API (sensors):
It appeared to me, that one switch was always creating 3 sensors in the REST-API of deconz. (2 with `"buttonevent": 0` ).
I reset the switches (press both switches on each one for 10s), removed the battery. Then I deleted all sensors manually in the REST-API and from the GUI.  
homebridge-hue was now initializing correctly, with all other sensors, but without the lumi switches (of course)
I then re-added one switch, checked REST --> only one sensor; homebridge-hue worked
Did the same for the 2nd switch --> voila everything works now as intended

Sorry for bothering you :D, looks like I could have solved this on my own as well, but some of your hints were quite useful in the process :) Thank you 👍

**Comment by ebaauw** [comment]
> Unfortunately I do not get this dump file, when I get the error.

Damn.  Unfortunately, the error is raised from homebridge itself, and I cannot catch and handle it in homebridge-hue.  I will change homebridge-hue to create the dump before returning the list of accessories to homebridge.

From the dump, deCONZ exposes the following sensor resources:
```json
{
  "12": {
    "config": {
      "on": true,
      "reachable": true
    },
    "ep": 2,
    "etag": "03818c9674d9b49ff1b9370763ea4a23",
    "manufacturername": "LUMI",
    "mode": 1,
    "modelid": "lumi.sensor_86sw2",
    "name": "lumi.sensor_86sw2 (3)",
    "state": {
      "buttonevent": 0,
      "lastupdated": "1970-01-01T00:00:00"
    },
    "type": "ZHASwitch",
    "uniqueid": "00:15:8d:00:01:70:ef:0f-02-0012"
  },
  "13": {
    "config": {
      "on": true,
      "reachable": true
    },
    "ep": 3,
    "etag": "03818c9674d9b49ff1b9370763ea4a23",
    "manufacturername": "LUMI",
    "mode": 1,
    "modelid": "lumi.sensor_86sw2",
    "name": "lumi.sensor_86sw2 (3)",
    "state": {
      "buttonevent": 0,
      "lastupdated": "1970-01-01T00:00:00"
    },
    "type": "ZHASwitch",
    "uniqueid": "00:15:8d:00:01:70:ef:0f-03-000c"
  },
  "14": {
    "config": {
      "on": true,
      "reachable": true
    },
    "ep": 1,
    "etag": "71bb79e4eb9b735b966346912969b7cc",
    "manufacturername": "LUMI",
    "mode": 1,
    "modelid": "lumi.sensor_86sw2",
    "name": "lumi.sensor_86sw2 (3)",
    "state": {
      "buttonevent": 2002,
      "lastupdated": "2018-01-04T00:59:57"
    },
    "type": "ZHASwitch",
    "uniqueid": "00:15:8d:00:01:70:ef:0f-01-0006"
  },
  "15": {
    "config": {
      "on": true,
      "reachable": true
    },
    "ep": 1,
    "etag": "10b330e162febecb4a8acefcb49c4bf5",
    "manufacturername": "LUMI",
    "mode": 1,
    "modelid": "lumi.sensor_86sw2",
    "name": "lumi.sensor_86sw2",
    "state": {
      "buttonevent": 3002,
      "lastupdated": "2018-01-04T01:00:04"
    },
    "type": "ZHASwitch",
    "uniqueid": "00:15:8d:00:01:64:03:eb-01-0006"
  }
}
```
12, 13, and 14 correspond to Switch1; 15 corresponds to Switch2.  Indeed, deCONZ has created additional resources for the _Multistate Input_ cluser (0x0012) on endpoint 0x02, and for the _Analog Input_ cluster (0x000c) for endpoint 0x03.  homebridge-hue doesn't expect these resources, so it creates the same buttons (`Stateless Programmable Switch` services, UUID 00000089-0000-1000-8000-0026BB765291) three times, hence causing the duplicate service error.

The quickest workaround is for you to blacklist `/sensors/12` and `/sensors/13`, see https://github.com/ebaauw/homebridge-hue#configuration.

A more structural workaround is for homebridge-hue to treat all devices as (potential) multi-resource devices, to prevent homebridge from crashing.  Unfortunately, this change would cause  HomeKit to see different services, so you'll lose all HomeKit room, group, scene and automation assignments.  Also, this would still cause additional (non-functional) switches to appear in HomeKit.

> I reset and re-added both sensors in the meantime, because I thought it might solve the problem with the odd looking endpoint from switch 2 (but unfortunately it did not work like I had in mind).

As I explain in https://github.com/ebaauw/homebridge-hue/issues/245#issuecomment-354600232, before re-pairing, you need to:
- delete the node from the deCONZ GUI;
- delete the resource(s) from the REST API;
- physically delete the _Deleted_ sensor records from the REST API database;
- Reset the switch,

otherwise deCONZ restores the previously created resource(s).

The structural issue is, of course, that deCONZ a) sometimes sees additional endpoints with _Multistate Input_ and _Analog Input_ clusters, and b) creates additional sensor resources for these.  I suspect a) is actually caused by the Xiaomi firmware rather than by deCONZ.  I'm probably to blame for b): while adding support for these clusters for the Xiaomi Smart Cube, I didn't explicitly whitelist the cube as only device where these clusters are valid.  I will issue a PR to deCONZ for that.

**Comment by flomeister88** [comment]
Thank you very much for your detailed answer. Basically I did what you described as the more structural workaround (see my last post). Only difference was, that I did not `physically delete the Deleted sensor records from the REST API database;` (I didn't know that this would be necessary)
But it worked out fine this way too!
