### ISSUE TITLE
ConBee Connection

### ISSUE THREAD

**Issue by SmartHank1** [ebaauw/homebridge-hue#230]
Hey all,

I have an issue regarding my Homebridge connection. The Plugin connects with my Hue Bridge but it doesn't want to connect to my Conbee / deConz. I opened the connection to the stick in the Webinterface but the plugin doesn't get the user data...
The error I receive is the following: (I deleted the IP and wrote the X instead)

XXX.XXX.X.XX: bridge request 33: get /config
XXX.XXX.X.XX: bridge http status 404 Not Found

What is going wrong?
THX

**Comment by ebaauw** [comment]
What version of deCONZ are you using?   Could you post the output of `homebridge -D`?

**Comment by SmartHank1** [comment]
I tried it again this morning it works...
I changed the line in the Config where to put user data.
Initially I just copied your configuration example and after running Homebridge I overwrite the l Nes for the HUE bridge. Now I deleted the numbers of the second line and it worked.
Thx at all, especially for answering so fast...

**Comment by ebaauw** [comment]
Are you sure deCONZ is at port 80?  Can you double check by entering http://192.168.0.43/ in your web browser and see if the deCONZ web app displays.  A _404 Not Found_ http status means that the requested resource, `/api/config`, doesn't exist on the web server at 192.168.0.43:80.  My guess is another web server (instead of deCONZ) took control of port 80 after rebooting the pi.

What happens if you remove the `"hosts"` key and let homebridge-hue discover the Hue bridge and deCONZ?  It should find both through UPnP.

If deCONZ is indeed running on another port (typically 8080), you can specify that in config.json:
```
"hosts": [ "192.168.0.9", "192.168.0.43:8080"]
```

**Comment by SmartHank1** [comment]
> f deCONZ is indeed running on another port (typically 8080), you can specify that in config.json:

"hosts": [ "192.168.0.9", "192.168.0.43:8080"]

This seems to work for me... Adding the port 8080 makes it run through....
Homebridge runs and the deConz shows up in HomeKit. Unfortunately the Xiaomi Sensors do not show up.... I think this is just a matter of my config. I will study your your Wiki first...

THX a lot for your help!!!

**Comment by ebaauw** [comment]
You’ll want to add `”sensors”: true` to config.json,
