### ISSUE TITLE
Hue Motion wrong Temperature in HomeKit

### ISSUE THREAD

**Issue by Nastra888** [ebaauw/homebridge-hue#236]
Hi Eric,

im about to move my lights and sensors from hue bridge too the rasbee gateway. 

I noticed that in the Philips Hue Motion the temperature sensor always shows 0 C in HomeKit and iConnecthue.

Over the Hue Bridge the temperature value was spent correctly.

Do you have an idea why the value is not displayed correctly?

I use deconz 2.04.99 and homebridge-hue@0.5.50

Thank you!

![img_0052](https://user-images.githubusercontent.com/27686185/34333626-183f6216-e93f-11e7-8629-faf09d3f9a22.jpg)
![img_0053](https://user-images.githubusercontent.com/27686185/34333627-18590400-e93f-11e7-8c03-b487a61f7d25.PNG)

**Comment by ebaauw** [comment]
Probably because deCONZ hasn't yet setup attribute reporting the _Temperature measurement_ cluster.  What does the ZHATemperature sensor's `state` object look like?  Does it have a `lastupdated` attribute?  Is `temperature` 0?

See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/340#issuecomment-353648984 for setting up attribute reporting manually.

**Comment by Nastra888** [comment]
Thanks for your quick reply. I reset and reconnected the sensor to deconz and now the temperature is displayed correctly. The first connection was probably a mistake.

Thanks to you and a happy new year!
