### ISSUE TITLE
Proposal: Whitelisting groups through config.json

### ISSUE THREAD

**Issue by grover** [ebaauw/homebridge-hue#240]
Hi @ebaauw,

thanks for the awesome plugin. I'm using it with deCONZ, however I believe that the following will also apply to Hue bridge users.

I have a chandelier with 3 hue e14 bulbs, which I'd like to expose as a group. However I don't want to expose all groups in deCONZ to HomeKit. I'd like to implement this by providing a separate group whitelist in the configuration - or change the groups entry in config.json to also accept either a boolean or an array of group IDs. I'd prefer the latter.

Before I start with the implementation for this I'd like to gather some input from you, which way you'd prefer this to be done. I plan to file a pull request with the change.

Thanks!

**Comment by ebaauw** [comment]
> I have a chandelier with 3 hue e14 bulbs, which I'd like to expose as a group.

I use HomeKit groups for that.  Apple's Home app shows a single tile for the HomeKit group, but you can still see and control the individual lights if you want to.  
Alternatively, you can create a deCONZ group and expose that through homebridge-hue.  You can blacklist the other groups, and even the individual lights in the chandelier, using a resourcelink on the gateway, see https://github.com/ebaauw/homebridge-hue/issues/170#issuecomment-338417513.  
Please note that in order to read resourcelinks, the latest version of homebridge-hue needs PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/331, which hasn't yet been included in the latest deCONZ v2.04.99 release, see https://github.com/ebaauw/homebridge-hue/releases/tag/v0.5.50.

> Before I start with the implementation for this I'd like to gather some input from you, which way you'd prefer this to be done. I plan to file a pull request with the change.

Thanks, I appreciate that.  Frankly, I don't think it's a good idea to put more configuration options in config.json.  In a multi-bridge environment, you'd need to specify which whitelist belongs to which bridge, so this would become quite complex and error prone.  Hence my decision to use resourcelinks instead for the blacklist.  
For v1.0 (with dynamic platform accessories, see issue #4), I plan to show a list of discovered resources and let the user select which ones homebridge-hue should expose.  This would then be persisted in `~/.homebridge/accessories/cachedAccessories`, as the bridge username.  No more manually editing config.json.

If the blacklist doesn't work for you, I would consider implementing a whitelist as resourcelink.  We'd need some additional naming convention (ugly) or use `classid` and/or `description` (even more ugly?) to distinguish between black- and whitelists.  The resourcelink would contain links to the resources to be exposed, irrespective of the config.json settings.

**Comment by grover** [comment]
Unfortunately Elgatos Eve App does not group lights in the same way as the Home app does, which was the reason I started thinking about this.

Blacklisting, using resourcelinks, will work as I only have a few groups at the moment. I'm a bit hesitant to update deCONZ at the moment. The version that I'm running is running quite stable and some of the recent reported issues give me pause in updating it right now.

**Comment by ebaauw** [comment]
As of v0.5.51 individual resources to be exposed to HomeKit can be whitelisted or blacklisted using bridge/gateway resourcelinks.  Should also work with deCONZ versions where the resourcelinks aren't yet included in GET /.

**Comment by grover** [comment]
Thank you for the quick update.
