### ISSUE TITLE
Exclude Hue Bridge 

### ISSUE THREAD

**Issue by jaal2001** [ebaauw/homebridge-hue#260]
Hi,
so far I understood that I do have to make a JSON/REST call to exclude specific lights/sensors/whatever from exposing them to homebridge. I only want to use homebridge with deCONZ and leave all "Philips" devices on the HUE Bridge. I do have some lights on the HUE bridge, which are from IKEA, some of them not reachable and are loaded during homebridge start:
[2018-1-11 19:41:15] [Hue] Philips hue: 3 services
[2018-1-11 19:41:15] [Hue] Initializing platform accessory 'Upper Middle'...
[2018-1-11 19:41:15] [Hue] Initializing platform accessory 'Ikea 1'...
[2018-1-11 19:41:15] [Hue] Initializing platform accessory 'Ikea 2'...

If I exlcude these lights in the config.json, all devices connected to deCONZ (including my plugs) disappear from Homekit. Creating a REST call everytime I change my setup is not my ideal idea for working with smart lights.

Is there any easy way to prevent homebridge-hue to load any setup from the HUE bridge? Removing it from the config did not work, as homebridge-hue tried to reach it during startup.

Thanks
Jan

**Comment by ebaauw** [comment]
> Is there any easy way to prevent homebridge-hue to load any setup from the HUE bridge? 

If you specify `"host": "127.0.0.1"` in config.json, homebridge-hue will only expose the local deCONZ and not search for other bridges/gateways.  You can also specify multiple hosts by `"hosts":["192.68.1.10", "192.168.1.11"]`.  You can also specify hostnames instead of IP addresses.

> Removing it from the config did not work, as homebridge-hue tried to reach it during startup.

The `"users"` key serves to store usernames, it does not specify what to expose, see https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

>  I understood that I do have to make a JSON/REST call to exclude specific lights/sensors/whatever from exposing them to homebridge.
> If I exlcude these lights in the config.json

In config.json, you can only exclude sensor _types_, or, on a v2 (square) Hue bridge, you can include Hue lights or Hue sensors and switches (these are excluded by default, as the Hue bridge already exposes these).  To exclude individual lights or sensors, you need to create a resourcelink on the Hue bridge or deCONZ gateway to blacklist them, see https://github.com/ebaauw/homebridge-hue#configuration.

**Comment by jaal2001** [comment]
> If you specify "host": "127.0.0.1" in config.json, homebridge-hue will only expose the local deCONZ and not search for other bridges/gateways. You can also specify multiple hosts by "hosts":["192.68.1.10", "192.168.1.11"]. You can also specify hostnames instead of IP addresses.

Okay, that is easy. I didn't got that from the documentation. 

> In config.json, you can only exclude sensor types, or, on a v2 (square) Hue bridge, you can include Hue lights or Hue sensors and switches (these are excluded by default, as the Hue bridge already exposes these). To exclude individual lights or sensors, you need to create a resourcelink on the Hue bridge or deCONZ gateway to blacklist them, see https://github.com/ebaauw/homebridge-hue#configuration.

That is what I understood and wanted to prevent. I thinks is a feature which needs always manual intervention and does not support fast changes to the "infrastructure". (I guess this is handy when it comes to the point, where most of the house is setup with Zigbee and I'm not still trying to change things.

Thanks again for your help!
