### ISSUE TITLE
Disconnected Hue Lamp is shown as reachable in HomeKit

### ISSUE THREAD

**Issue by Sonsi79** [ebaauw/homebridge-hue#263]
Im using actually version of HB and HB-Hue but 1 Lamp which isn't reachable is still shown as reachable and switchable in HomeKit.

I know it is normal still to be switchable, but why is the status "Reachable" still set in HomeKit?

My Config:
            ...
            "heartrate": 3,
            "sensors": true,
            "nativeHomeKitSensors": false,
            "nativeHomeKitLights": false,
            "excludeSensorTypes": ["Daylight", "CLIP", "Geofence"],
            "lights": true
        },

Hope you can help :-)

**Comment by ebaauw** [comment]
homebridge-hue doesn't report an accessory as unreachable, but  sets `Status Fault` when a device is reported unreachable by the Hue bridge.  This is because the bridge sometimes/often reports a device as unreachable while it's working perfectly.  If homebridge-hue were to announce the device as unreachable to HomeKit, like the Hue bridge, you could no longer control it in this case.

Note that when setting `"wallSwitch": true` in config.json, homebridge-hue will report "unreachable" lights as Off, and you won't be able to control these from HomeKit.

I tried the Hue bridge approach in v0.5.56, but reverted this in v0.5.58 because it caused more harm then good.  You might try one of these versions to see whether you agree (check https://github.com/ebaauw/homebridge-hue/releases first), or whether you'd prefer the Hue bridge approach.  I could re-introduce the Hue bridge approach conditionally, based on a config.json setting (or combined with `"wallSwitch"`).

**Comment by CooperCGN** [comment]
I'm actually happy the way it is. My Osram gardenspots are working perfectly for a few days, then suddenly the bridge shows them as not reachable although can be controlled as normal. After unplugging them they usually switch back to reachable but not for long.
