### ISSUE TITLE
Osram Lightify E14 bulbs not exposing color temperature when in a group

### ISSUE THREAD

**Issue by dgburton** [ebaauw/homebridge-hue#27]
Hi,

Thanks for your work on this!

I've got a Hue group made up entirely of these Osram bulbs:

https://www.amazon.co.uk/dp/B00YSXBHS4

Through the native Hue app I can adjust the color temperature, but then I expose them in a group via the plugin I only see "Brightness" via the iOS Home app, not Colour.

Is this the expected behaviour?

Thanks!

**Comment by sejoki** [comment]
I got the same issue for the GU10/PAR16 spots. In the hue app I can change the color temperature and in Eve as well and I can even set the color up in scenes, but not in the home app.

My workaround was setting up two scenes for all the affected lights, one with bright white and one with warm white. Then a corresponding rule if any of them are switched on before sunset to trigger the bright white scene and if they're switched on after sunset the warm white.

It's not a pretty solution as it creates even more scenes, but better than not being able to change them at all. On the other hand it makes sense though, because the only time I would change the color temperature is at night to be warm white and during the day to be cold.

**Comment by ebaauw** [comment]
@dgburton @sejoki
The iOS 10 Home app doesn't support color temperature, nor any other custom characteristic.  You need to use another homekit app (like Eve) to use Color Temperature.

@dgburton Afaik, a group should inherit the "high water mark" of attributes of the lights it contains.  So a group which contains a color temperature light (like the Osram E14) should expose the Color Temperature characteristic.  If not, could you please attach a dump of your bridge state here (see **Troubleshooting** in the README)?

@sejoki The iOS 10 Home app should still be able to activate a homekit scene created in Eve, including Color Temperature.
