### ISSUE TITLE
Disabled motion sensors triggers anyway?

### ISSUE THREAD

**Issue by SeydX** [ebaauw/homebridge-hue#273]
#### Issue

Hey everyone,

i am using the aqara motion sensor with deconz and hue plugin. It works very well. 
Now, i created new automation with my camera running with homebridge-camera-ffmpeg.

The camera captures a snapshot und upload it to google drive if the aqara motion sensors detects a motion. 

My problem is, i want to activate the sensor ONLY if i  am not at home, i tried already with disabling the motion sensor but it triggers anyway. What i am doing wrong? 

#### Log Messages

```
Sensor:

{
-"config": {
"duration": 15,
"on": false,
"reachable": true
},
"ep": 1,
"etag": "7d68302d92b7ea5bd59bc017ba897357",
"manufacturername": "LUMI",
"modelid": "lumi.sensor_motion.aq2",
"name": "Presence 2",
-"state": {
"lastupdated": "2018-01-23T00:11:42",
"presence": false
},
"type": "ZHAPresence",
"uniqueid": "00:15:8d:00:01:e1:61:e3-01-0406"
}
```

**Comment by ebaauw** [comment]
This is an issue with deCONZ, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/90.

**Comment by SeydX** [comment]
oh okay thanks for the info, is there maybe any workaround for the problem ? :/

**Comment by ebaauw** [comment]
There’s two:
1. As @manup indicated you could temporarily disable the rules.  homebridge-hue can expose them to HomeKit, so you can enable/disable gateway rules from a HomeKit scene.  You need to create these HomeKit scenes in Eve, because Apple’s Home app doesn’t support custom attributes.  Also you might want to whitelist the motion sensor rules instead of exposing all gateway rules.
2. Use a CLIP sensor as virtual switch to enable the motion sensor and change you gateway rules to check for the CLIP sensor’s state in addition to the ZHAPresence state.  This is actually what I do at home.

**Comment by SeydX** [comment]
i am not so good in this :/ can you help me solving this problem with one of the points you wrote?

**Comment by SeydX** [comment]
what u mean with "disabling" the rule"? i dont have any rules regarding the motion sensor... or you mean first creating a rule that puts the config.on of the motion sensor to false? hmmm

**Comment by SeydX** [comment]
So i finally got it ^^ thanks for all :)
