### ISSUE TITLE
double and long press function for xiaomi aqara button

### ISSUE THREAD

**Issue by bonze4** [ebaauw/homebridge-hue#274]
Thx for this awesome plugin!
Is it possible with deconz to add double and long press function for xiaomi aqara button (2)?

**Comment by ebaauw** [comment]
Double press: yes, see https://github.com/ebaauw/homebridge-hue/commit/3b739a31eab39444873297345fdf299c2bc00976.  Long press: no, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/349#issuecomment-359294830.

**Comment by bonze4** [comment]
Thx for information! Double press works.

**Comment by tomky** [comment]
Hi, I would like to bring this up again as I find that there is a significant delay in the single press event triggered by Aqara switch compared with Philips Hue Dimmer switch. I feel that it could be due to the support of double press in Aqara switch so it must wait for a while to distinguish these two events. In some cases like light switching, this extra delay (around 1 sec) could be annoying. 

If that is really the cause, could we disable double press event in exchange for faster single press detection?

**Comment by ebaauw** [comment]
Not in deCONZ; the Aqara switch sends different messages for single press vs double press.  You would have to change this in the Aqara firmware (which is not upgradable over-the-air).

**Comment by tomky** [comment]
It seems to me that there are 1000 (press) and 1002 (release) events, and single press is triggered by 1002 so far. What if single press is triggered by 1000 so it will be triggered as soon as a press occurs?

If this brokes other mechanisms, what if we replace “long press” in homebridge with 1000 event so users who would like rapid single press can use this instead (although ironic)

**Comment by ebaauw** [comment]
The Hue dimmer switch sends events on press vs release, the Aqara switch doesn’t.  As I said before, it sends events on single press vs double press instead.  Unfortunately the ZigBee standard doesn’t define this, and each manufacturer handles this differently.

**Comment by tomky** [comment]
Actually, I find that this idea really works. I redirect the PRESS case to trigger LONG_PRESS event in hkZLLSwitchAction instead of NULL, and change the button type to SINGL_DOUBLE_LONG. I can see the following log:

```
Nov 04 09:34:46 pi homebridge[4640]: [11/4/2018, 9:34:46 AM] [Hue] lumi.sensor_switch_2 Button: homekit button long press
Nov 04 09:34:47 pi homebridge[4640]: [11/4/2018, 9:34:47 AM] [Hue] Light 3: homekit on changed from 0 to 1
Nov 04 09:34:47 pi homebridge[4640]: [11/4/2018, 9:34:47 AM] [Hue] lumi.sensor_switch_2 Button: homekit button single press
Nov 04 09:34:52 pi homebridge[4640]: [11/4/2018, 9:34:52 AM] [Hue] lumi.sensor_switch_2 Button: homekit button long press
Nov 04 09:34:52 pi homebridge[4640]: [11/4/2018, 9:34:52 AM] [Hue] Light 3: homekit on changed from 1 to 0
Nov 04 09:34:53 pi homebridge[4640]: [11/4/2018, 9:34:53 AM] [Hue] lumi.sensor_switch_2 Button: homekit button single press
```

As you can see, a long press is triggered before a single press for around 1 sec earlier and triggered the homekit action. Also in the double press event, there will be two long press actions. So I need to remove both single press and double press actions to avoid conflicts. But I'm satisfied with the rapid "Long Press" action.

I also doubt maybe I'm actually using an old version of Xiaomi round button switch instead of Aqara version. Not sure where to check this.

**Comment by tomky** [comment]
Yes, I agree that it is a hack and will be unsuitable for general purpose. I will maintain my own fork. Thanks for the assistance!

**Comment by tomky** [comment]
Yes, I agree that it is a hack and will be unsuitable for general purpose. I will maintain my own fork. Thanks for the assistance!
