### ISSUE TITLE
Lightify support

### ISSUE THREAD

**Issue by sejoki** [ebaauw/homebridge-hue#28]
First of all, thank you for this plugin, it makes the Hue bridge truly HomeKit compatible. I have a few minor issues/suggestions though.

I only own two Hue bulbs that were included in my starter kit, the rest are Lightify devices as they just seemed more reasonable, first regarding the price and second the functionality - I don't need RGB lights in all of my rooms (I know, Philips makes them as well, but they're still twice as expensive).
Anyways…

The classic white bulbs work without any issues at all. I have three PAR16 spots that, after an update, are working fine, but don't seem to be recognised by home kit as color temperature enabled.
The third one is an LED strip that does work, better after updating, but I have it in a couple of scenes and every now and then (not always though) I get the error 

> [Hue] Philips hue: hue bridge error 201: parameter, bri, is not modifiable. Device is set to off.

Sometimes it doesn't turn on at all, sometimes it does but doesn't apply color changes (there's a second error message that I wasn't able to recreate right now)

And the fourth type of device is the Lightify plug. It only shows the on/off state as it's not dimmable, but I find it highly confusing that it shows up as a light bulb. A couple of other plugins I have installed, mainly switches, allow me to modify the type - whether it's a light bulb, fan or switch.

I know that a symbol for plugs exists as the Elgato one doesn't show up as a bulb, is there a way you can allow the symbol for the switch to be modified in a future update?

I don't know how I can provide any help with a better support for the spot lights or the LED strip, but if there's anything I can do I'd be glad to.

**Comment by ebaauw** [comment]
@sejoki 

> I have three PAR16 spots that, after an update, are working fine, but don't seem to be recognised by home kit as color temperature enabled.

Please note that the iOS 10 Home app provides only limited functionality.  In particular, it doesn't support custom characteristics like Color Temperature.  You might want to use another HomeKit app, like Eve.  See **Caveats** in the README.
> I have it in a couple of scenes and every now and then (not always though) I get the error

This is expected behaviour: the Hue bridge doesn't support changing light attributes when the light is off.  Or more precisely, when the Hue bridge thinks the light is off.  See below.
> Sometimes it doesn't turn on at all, sometimes it does but doesn't apply color changes (there's a second error message that I wasn't able to recreate right now)

When the communication between the Osram light and the Hue bridge fails, the Hue bridge might report the wrong light state and bridge commands might not reach the light.  The Zigbee connection between the Hue bridge and Osram devices appears to be less robust that the connection between the Hue bridge and Philips devices.  I don't have any Osram Lightify lights myself, only two On/Off plugs.  I do find the Hue bridge reports them as unreachable on occasion.  I expose the `reachable` attribute as `Status Fault` to HomeKit, but again, the iOS 10 Home app doesn't support this.  In Eve, you'll see a red exclamation mark when the device is unreachable.  Unfortunately, with the current design of homebridge-hue, I cannot expose `reachable` as HomeKit `Reachable` (see issue #4), which is supported by Home.

4) My bad.  I expose the On/Off plug as a Light, instead of a Switch.  I only have lights connected to the On/Off plugs and really didn't think about this.
