### ISSUE TITLE
Q: Any reasons to keep hue bridge when there is deconz?

### ISSUE THREAD

**Issue by iantait** [ebaauw/homebridge-hue#297]
Obviously not an issue, but not sure of a better place to ask this (tell me if there is) - are there any good reasons not to use deconz entirely and retire the hue bridge?

I've got a few lights connected to both at the mo and a hue motion sensor connected to the hue bridge.
I'm liking the potential 'power' monitoring via deconz (just started to see this cos I deleted eve and reinstalled)

**Comment by ebaauw** [comment]
Possible reasons (not necessarily good - I've decommissioned my Hue bridge months ago):
- deCONZ is still in beta;
- deCONZ doesn't provision the Green Power proxies (so the Hue tap only works when in direct range of the RaspBee/ConBee, not through the mesh;
- Hue Entertainment.

I'd still keep the Hue bridge around, just to be able to update the firmware of the Hue lights, sensors, and switches.  Philips don't publish their firmware, so these can only be updated through the Hue bridge.

**Comment by ooii** [comment]
Can the same accessories (lights, sensors, etc) be associated with both? 
Given all the issues I have with my hue bridge and the poor quality of Philips Hue support, I'm planning to move to deConz.

**Comment by ebaauw** [comment]
No, each device can only be associated with one ZigBee network, and both the Hue bridge and deCONZ create their own.  Instead of deleting the device from the Hue bridge, you can simply reset it, so you can rejoin it later without having lost its configuration.

Be careful when exposing both the Hue bridge and deCONZ to HomeKit using homebridge-hue.  You need to blacklist the stale resources on the Hue bridge, or you’ll get the infamous cannot add an accessory with the same UUID error.

**Comment by ooii** [comment]
Thanks @ebaauw.

**Comment by ooii** [comment]
One more question regarding the deCONZ: does it push events to homebridge-hue or does this latter need to make regular polls?

**Comment by ebaauw** [comment]
deCONZ pushes events on a web socket, which homebridge-hue reads.  In addtion, homebridge-hue (still?) polls deCONZ over the REST API, for changes that are not pushed on the websocket and as a backup.  If you run homebridge -D, homebridge-hue logs a debug message for each API and for each web socket event.

I think by now (v2.05.xx), deCONZ creates web socket notifications for all changes to `/lights`, `/groups`, and `/sensors` `state` and `config` attributes.  You can probably run homebridge-hue with a `heartrate` of 30 seconds without noticing any delay.

**Comment by ooii** [comment]
Thanks again.

**Comment by ooii** [comment]
One more question: is there any (easy) way to migrate accessories and lights from the hue bridge to the deconz one? I have more than 60 lights/accessories and re-associating all that will take some time.

**Comment by ebaauw** [comment]
No there isn't.

**Comment by ooii** [comment]
Just to let you know: next version of Hue bridge fw, v1.25, will have debugging and logging information. That will probably help a lot in situations where the system does not behave as expected.

**Comment by flobernd** [comment]
I just added a RaspBee device to my `homebridge` Raspberry Pi system and was asking me the same question as the OP. Sorry for bugging you instead of asking this on the deCONZ page, but I just found this "old" issue while I was browsing your repo. 

Is the information in your first-answer still up-to-date @ebaauw ? Especially the part about the Green Power proxy functionality?

**Comment by flobernd** [comment]
Aww thats not cool :/ I'll definitely keep my Hue bridge until this is implemented. Thanks for your reply.
