### ISSUE TITLE
Philips Hue Motion Sensor: Custom Duration not stored

### ISSUE THREAD

**Issue by DSchumacher2104** [ebaauw/homebridge-hue#304]
Hello! I'm so happy about the possibility to set a custom duration to the hue motion sensors, cause the nativ homekit setting of 10 seconds is not usable to control light with the motion sensor. Fortunatly your plugin allows to set a custom duration in EVE App in Device Settings. However i discovered, that this settings are not stored after a restart of your plugin. Is it possible to store this setting?

**Comment by ebaauw** [comment]
Not at the moment, the Hue bridge doesn’t offer this and I need to move to dynamic platform accessories (issue #4) to persist the accessory state between homebridge-hue restarts.

**Comment by DSchumacher2104** [comment]
Okay, does your answer mean, that it planed in (near) future?

**Comment by ebaauw** [comment]
It's envisioned, but not planned.  I want to persist the usernames (API keys) as well, and get rid of the need to edit config.json and store them there.  Technically, it's by far the biggest change ever to homebridge-hue, and I would rather make that change gradually instead of in a big bang.  v0.8 is actually a step in that direction, introducing a separate object for accessories.

**Comment by ebaauw** [comment]
Closing this one, to be picked up under #4.

**Comment by DSchumacher2104** [comment]
Hello Eric! Is it possible to change the default duration when (re-)starting the plugin? Now everytime when restarting your plugin, the duration time resets to the minimum time of 5 seconds. It would be great if you could set the default time to a 2-minutes-duration when restarting the plugin. I think a 2-minutes-duration is a good mean time for a Motion sensor. A 5-seconds-duration is very useless cause it let's your lights flash permanently ;-)

**Comment by ebaauw** [comment]
The default value is hard-coded: https://github.com/ebaauw/homebridge-hue/blob/4651169938f76b2dd2d87ecf946aca9bac9063d5/lib/HueSensor.js#L508

(The HomeKit value will be 5, since that's the minimum value that Eve supports).  You can patch `HueSensor.js` and change that to 120.  I'm reluctant to change it, since all Hue bridge users will be impacted.  I suppose we could create yet another config.json key, but I really want fewer of these, not more.  I'd rather spend my time on the dynamic platform accessories.

**Comment by DSchumacher2104** [comment]
Okay, thank you for this workaround! It works, but only if i change the value in line 1099 from 5 to 120. This saves much time when restarting homebridge, cause i use 7 Motion Sensors :-)

**Comment by ebaauw** [comment]
Oops, indeed it’s hardcoded there as well.  It would have been better to use the logic in `checkDuration()`.
