### ISSUE TITLE
AnybodyHome and NobodyHome

### ISSUE THREAD

**Issue by adekka** [ebaauw/homebridge-hue#31]
Is it possible to create a trigger NobodyHome besides the AnybodyHome? The automation part of HomeKit can only be triggered by a value true. AnybodyHome won't trigger an automation if its false.

**Comment by jaytay79** [comment]
Are you referring to the geofence occupancy sensor? If so you will need to use something like Elgato Eve to create a new rule for this. I have just tested this with a motion sensor turning on a light when it is "clear" (rather than "motion") and that worked OK. The rule in the Home app looks a bit weird but it works fine.

As a footnote is that the default name for your occupancy sensor created by the Hue app itself? Mine was called HomeAway by default but I have also had one called "iPhone" created as well.

**Comment by ebaauw** [comment]
Hi @adekka 
As @jaytay79 indicates, HomeKit supports this, but the iOS 10 Home app is rather limited (see **Caveats** in the README) and doesn't support all HomeKit capabilities.  In particular it only supports motion or occupancy sensors detecting something.

**Comment by adekka** [comment]
@jaytay79 it works fine for coming home. I can't get it to work when leaving home. I  also renamed it, but it was something like PDXHomeAway

@ebaauw :( guess we'll have to wait then. Would be great if the lux variable could be used..

**Comment by ebaauw** [comment]
@adekka instead of waiting for Apple to enhance the iOS Home app, you could try another HomeKit app.  Both apps I mention in the README support triggers on motion or occupancy sensor showing clear or away, as well as triggers on light level or temperature.

**Comment by adekka** [comment]
@ebaauw thx! totally missed that
