### ISSUE TITLE
Problem with Osram GardenSpot mini not solved with version0.9.4

### ISSUE THREAD

**Issue by Kohle81** [ebaauw/homebridge-hue#352]
Hey Erik,

yesterday I have tried with hue-plugin 0.9.4 to switch on my Osram GardenSpot mini.

In HomeKit it turns on and in the Hue app too. But the GardenSpot doesn‘t do lights on.

The live-log in homebridge is ok:

Jun 03 10:06:54 raspberrypi homebridge[605]: [2018-6-3 10:06:54] [Hue] Gartenspot: homekit on changed from 0 to 1
Jun 03 10:06:58 raspberrypi homebridge[605]: [2018-6-3 10:06:58] [Hue] Gartenspot: homekit on changed from 1 to 0

When I switch the GardenSpot on in the Hue App it works.

I know the user @nastra have the same problem.

**Comment by ebaauw** [comment]
That is odd - if you can turn the Gardenspot on or off using the Hue app, you should be able to do so from homebridge-hue as well.  Could you please attach the debug dump file and create and attach a debug log file?  Do the Hue app and HomeKit show the same state?  Did you turn on/off the individual light in the Hue app, or the room (group) the light is in.

I haven't tried connecting the Gardenspot to my (mostly unused) Hue bridge, but I had some funny issues trying to connect it to deCONZ, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/610#issuecomment-393972287.  It appears that OSRAM, like IKEA, uses a different way to build up the ZigBee mesh network than Philips.  And it doesn't help that the garden (or terrace in my case) typically lies on the edge of the ZigBee network, causing the Gardenspot to connect to deCONZ or to the Hue bridge over the mesh network rather than directly.

**Comment by CooperCGN** [comment]
I know this doesn't help but my GardenSpots work perfectly even when the hue app most of the times shows them as not reachable.
