### ISSUE TITLE
Accessory Not Supported.

### ISSUE THREAD

**Issue by farstreet** [ebaauw/homebridge-hue#36]
Hoi Erik,

Installed the homebridge-hue plugin, ran it for a first time, pressed the button on my bridge, entered the info from he logging into the config.json file, started homebridge again and.. nothing :)

Well, what happens is that in the Home app (and also in Eve), there is a new 'Philips hue' accessory, but the Home app says it's not supported.   See screenshot below.   Checked with Eve, see the same accessory but cannot do anything with it, not even change it to another room.   config.json & logging output also included below.   

I must say that I have the Hue bridge itself connected directly to the Homekit already, only reason for me to include the plugin was for the Dimmer and Tap switch, as I can then include more actions than only hue updating hue lamps when these are used.

As I kept all additional parameters out of the config.json file, my expectation was that only these switches (and maybe other switches/sensors, except for the light bulbs themselves) would appear.   My idea was to have those switches do nothing (or as little as technically possible) within the Hue environment itself but take advantage of the exposure of the switches/sensors to HomeKit to either use their characteristics as Triggers or Conditions.

Your thoughts & feedback are highly appreciated.    

Met vriendelijke groet vanuit California.
Jurgen

**config.json**
_{
 "platform": "Hue",
 "name": "Hue",
 "users":    {
      "0XXXXXXXXX6": "AXXXXXXXXXXXXXXB"
                   }
}_

**Logging:**
_[1/1/2017, 11:50:14 PM] [Hue] Philips hue: hue bridge request: get /
[1/1/2017, 11:50:19 PM] [Hue] Philips hue: hue bridge request: get /
[1/1/2017, 11:50:24 PM] [Hue] Philips hue: hue bridge request: get /
[1/1/2017, 11:50:29 PM] [Hue] Philips hue: hue bridge request: get /
[1/1/2017, 11:50:34 PM] [Hue] Philips hue: hue bridge request: get /_
Etc.. goes on like that 

![fullsizerender](https://cloud.githubusercontent.com/assets/24705229/21585957/55620c5e-d07f-11e6-974f-5853c232beb3.jpg)

**Comment by ebaauw** [comment]
Hallo Jurgen @farstreet , 

You need to add `"sensors": true` to config.json to make homebridge-hue expose the sensors to HomeKit, see the README.

Currently, the only thing you can do with the bridge accessory is dump the bridge state to file by selecting Identify on it.  I plan to use this accessory to store the bridge username in future, so you would no longer need to add it manually to config.json.  You should be able to assign it to a room, however, both in the iOS Home app as well as in Eve: click on Default Room in the screen you posted.

Depending on the number of lights you have, you might want to have homebridge-hue expose groups and use these in the HomeKit scenes and triggers instead of the individual lights (exposed by the v2 bridge).  That could vastly reduce the amount of network traffic between your iOS device and (homebridge-hue and between homebridge-hue and) the Hue bridge and it would make sure all lights react simultaneously.  This is more of a concern for a v1 (round) bridge, however.

Also you might want to specify a lower value for `heartrate` in config.json to have homebridge-hue react quicker to your switches.  I'm using 2 seconds myself, but I've heard others using 1 second successfully.

Personally, I like to programme all interaction between Hue bridge resources in the bridge itself.  That way, my dimmer switches and motion sensors continue to work with my lights, even when my home network is out.  The official Hue app does a lousy job at programming this interaction imho, so I've created my own Hue bridge rules.  I only use HomeKit triggers to let the motion sensors and dimmer switches interact with my other accessories: my Sonos speakers and Eve Energy plugs. 

Also note that homebridge-hue can only expose the button release events of the dimmer switches, because it needs to poll the Hue bridge and cannot detect the button press and button hold events reliably.  This is good enough for on/off control, but dimming lights is best done using Hue bridge rules.

**Comment by bspradling8** [comment]
I'm experiencing this same issue. I have included `"sensors": true` in my config.json and I'm getting the same thing of `This accessory is not currently supported by the Home app`.

**Comment by Subito** [comment]
Having the same problem as @bspradling8, same config. I can not reach my Lightify Bulbs or access the sensor on the bridge. Debug shows (with one bulb and one bridge):
```
[Hue] Philips hue: BSB002 bridge, api v1.16.0
[Hue] Philips hue: hue bridge request: get /
[Hue] Philips hue: 0 lights
[Hue] Philips hue: 0 groups
[Hue] Philips hue: Daylight: Daylight sensor
[Hue] Philips hue: 1 sensors
[Hue] Philips hue: 0 schedules
[Hue] Philips hue: 0 rules
[Hue] Philips hue: 2 accessories
[Hue] Initializing platform accessory 'Philips hue'...
[Hue] Initializing platform accessory 'Daylight'...
```

**Comment by ebaauw** [comment]
@bspradling8 You need to set `"lights": true` as well if you want to expose lights.  The `"philipslights": true` only works when lights is enabled.  The iOS 10 Home app doesn't support Hue Dimmers, Hue Taps, the Daylight sensor nor CLIPGenericStatus sensors.  These are mapped to a Stateful Programmable Switch service, which is HomeKit standard, but not (yet?) supported by Home.  They are supported by other HomeKit apps, see the README.

@Subito it looks like homebridge-hue connects to your bridge alright (it finds the Daylight sensor).  Please double-check your config.json (for `"lights": true`).  The Osram Lightly Bulb should work.  If not, could you please post the output of `homebridge -D` and a dump of your bridge state (see README)?

**Comment by bspradling8** [comment]
Thank you @ebaauw! Appreciate the work and the quick response. It is working great.

**Comment by Subito** [comment]
Thanks! Works fine. I misread the README, apparently. Got confused with `lights`, `philipslights` and `alllights`. Its clear now. Thanks!

**Comment by tony55260** [comment]
Hello I have the same problem with the " accessory not supported" on my rgb strip. Anybody have the same? 
Thks
