### ISSUE TITLE
TRÅDFRI Remote control as universal button via deConz

### ISSUE THREAD

**Issue by SebSemmi** [ebaauw/homebridge-hue#380]
#### Issue

I’m running deConz (2.5.38) headless on Ubuntu 18.04 server. I connect it via this plug-in with HomeKit. I added a TRÅDFRI Remote control to deConz and it shows up and recognise the button presses in HomeKit. But it does not trigger the in HomeKit assigned action after pressing. Is this a homebridge or a deConz problem?

#### Log Messages

```
```

**Comment by ebaauw** [comment]
If the button presses are registered in HomeKit (tile flashes in Home app), but the assciated actions don’t get fired, the problem is with your HoneKit hub.  Most likely, the HomeKit configuration hasn’t yet been synced (over iCloud) with your AppleTV or HomePod.  In Eve (which shows the button actions under automations), you can try to disable the automation on one iDevice, wait for that change to get propagated to your other iDevices, re-enable it, and, again, wait for that change to be propagated.  Unfortunately, there’s no way to check the configuration in the AppleTV.
