### ISSUE TITLE
Recommendation: best way to update nodeJS?

### ISSUE THREAD

**Issue by deanlyoung** [ebaauw/homebridge-hue#381]
@ebaauw what process/steps would you recommend to upgrade nodeJS and packages that were compiled on previous versions? homebridge-hue updates its node version more frequently than others, but I’m afraid to update node a lot of times. Don’t get me wrong, I love that you’re always keeping it updated, I just want to streamline my own process so that I don’t end up out of date.

**Comment by ebaauw** [comment]
In my experience, homebridge (and other packages using C modules) break only when the major version of NodeJS changes (e.g. 8.x.x -> 10.x.x).  In that case, best uninstall and re-install the package to force re-compilation of the C modules:
```
sudo npm -g un homebridge
sudo npm -g i homebridge --unsafe-perm
```
I stay on the latest long-term support (LTS) version of NodeJS, so this would be needed only once a year or so.

**Comment by twentyNoise** [comment]
Erik,

I'm going to have to update Node in order to use your homebridge-hue plugin. Do you have a process / trick for doing the uninstall / reinstall of Homebridge with the latest node, while still keeping all the Homebridge config intact? That is I know how to just restore the config file, but is there anyway to do all this and still keep the config in the Home app intact? As though the Home app doesn't know any uninstall actually happened? Will just restoring the .homebridge folder back to it current state be adequate? And also NOT opening the Home app until Homebridge is reinstalled?

Thanks

**Comment by ebaauw** [comment]
Homebridge installs to /usr/lib/node_modules or somewhere similar; your configuration is in ~/.homebridge.  Re-installing homebridge doesn’t touch your configuration.  The Home app will just show accessories as not responding when homebridge isn’t running.  The only thing to avoid is running homebridge without all plugins, or when plugins won’t expose all accessories.  HomeKit will remove the missing accessories and when they’re present again after restarting homebridge, HomeKit will see them as new accessories, losing any room, group, and scene assignments and any automations.

See above how to uninstall and re-install homebridge after updating node to a different major version.
