### ISSUE TITLE
set option for a specific light 

### ISSUE THREAD

**Issue by SebSemmi** [ebaauw/homebridge-hue#387]
I want to set the wallSwitch option to true only for one light. Is this possible with the config?
I'm using the latest Homebridge-hue and deCONZ version.l

**Comment by ebaauw** [comment]
Internally, the setting is actually maintained per light resource (so _Outlet_ services can be excluded), but there's currently no way to set it.  That's probably best implemented through a `wallSwitches` resourcelink.  And a corresponding `ph` command to create it.

**Comment by SebSemmi** [comment]
I have to say, I  still don't quit get `ph` and `resourcelinks`. Do I have to run your example on the machine with the deCONZ gateway or with the homebridge?

On my homebridge machine I get
```
$ ph discover              
{
  "192.168.1.4": "xxx"
}
$ ph post /resourcelinks '{
  "name": "homebridge-hue",
  "description": "wallswitch",
  "links": [
    "/lights/1"
  ],
  "classid": 1
}'
ph: error: localhost: not a Hue bridge nor deCONZ gateway
```

**Comment by ebaauw** [comment]
Looks like you're running deCONZ on a different machine than homebridge (and `ph`)?  In that case, you need to specify to `ph` where to find deCONZ, either by `ph -H 192.168.1.4` or by setting the `PH_HOST` environment variable.  Also, you would need to unlock the gateway and run `ph createuser` to create an API key.  This key will be stored in `~/.ph`.

**Comment by JanMisker** [comment]
Is there some documentation somewhere about the resourcelinks. Do I understand correctly that it would allow me to change how a resource is exposed? For example could I remove the “color temperature” setting from a light that way?

**Comment by ebaauw** [comment]
Resourcelinks are simply feature the Hue bridge and deCONZ gateway provide to apps to ... link resources.  From https://developers.meethue.com/documentation/resourcelinks-api:
> Resourcelinks are a way to group resources in the bridge. Resourcelinks can be used to order, combine and delete resources in the bridge. Furthermore they are useful to visualize functionalities that make use of various resources in the bridge (for example: Routines).

homebridge-hue reads resourcelinks for:
- Blacklisting which resources not to expose to HomeKit (overrides the config.json settings);
- Whitelisting which resources to expose to HomeKit (overrides the config.json settings);
- Listing which `/lights` and `/groups` resources should be exposed as _Outlet_ instead of _Lightbulb_;
- Combining multiple CLIP sensors into a single multiCLIP accessory (to mitigate the 99 accessories per bridge limit of HomeKit);
- Combining multiple lights into a single multilight accessory (to mitigate the 99 accessories per bridge limit of HomeKit;
- And now: setting `wallSwitch` per light.

> For example could I remove the “color temperature” setting from a light that way?

No.  Why would you want to do that?  On a light for light case?

**Comment by SebSemmi** [comment]
I accidentally created a bunch of resourcelink on the deCONZ machine.
`"resourcelinks": {
    "1": {
      "classid": 1,
      "description": "wallswitch",
      "links": [
        "/lights/...",
        "/lights/..."
      ],
      "name": "homebridge-hue",
      "owner": "44DF01C5DA",
      "recycle": false,
      "type": "Link"
    },
    "2": {
      "classid": 1,
      "description": "wallswitch",
      "links": [
        "/lights/1"
      ],
      "name": "homebridge-hue",
      "owner": "44DF01C5DA",
      "recycle": false,
      "type": "Link"
    },
    "3": {
      "classid": 1,
      "description": "wallswitch",
      "links": [
        "/lights/...",
        "/lights/..."
      ],
      "name": "homebridge-hue",
      "owner": "44DF01C5DA",
      "recycle": false,
      "type": "Link"
    }
  },
`
How can I remove them and fix this

**Comment by ebaauw** [comment]
Through the REST API.  Easiest by using `ph`:
```
ph delete /resourcelinks/1
```

**Comment by SebSemmi** [comment]
Thank you for your help. Still can't get my head around this thing.

with `ph get` I found the resourcelink of the one light connected to my deCONZ.
```"lights": {
    "1": {
      "etag": "a9b11d5bd3ccdef69a7c725fb696f752",
      "hascolor": false,
      "manufacturername": "IKEA of Sweden",
      "modelid": "TRADFRI bulb E14 W op/ch 400lm",
      "name": "Herd",
      "state": {
        "alert": "none",
        "bri": 254,
        "on": false,
        "reachable": true
      },
      "swversion": "1.2.214",
      "type": "Dimmable light",
      "uniqueid": "00:0b:57:ff:fe:da:b6:0d-01"
    }
  },```

Is the following the right way to set the `wallswitch` resourcelink?
```ph post /resourcelinks '{
  "name": "homebridge-hue",
  "description": "wallswitch",
  "links": [
    "/lights/1"
  ],
  "classid": 1
}'```

**Comment by ebaauw** [comment]
The _No Response_ status in HomeKit has nothing to do with the light being powered (or reachable by the ZigBee gateway).  It’s caused by your iDevice not being able to find or contact the accessory (i.c. Homebridge).  Most likely this is caused by your network router, switch, and/or WiFi access point not forwarding the (multicast) Bonjour announcement by Homebridge to your iDevice.  Fritz!Box devices are notoriously problematic; for other devices, make sure you disable IGMP snooping.

**Comment by SebSemmi** [comment]
I don't know. The other devices are available through the ZigBee gateway. What does the option `wallswitch` do exactly?

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

Are you saying the only one accessory shows _Not Responding_ in HomeKit, and other accessories are responsive in HomeKit?  Are these other accessories exposed by the same Homebridge instance?

**Comment by SebSemmi** [comment]
It is just this light bulb, which connects to deCONZ which talks to one Homebridge instance. This on light bulb is mainly operated via the wall switch. If I turn the light bulb off via wall switch the `state. reachable` becomes `false`. Shouldn't the `wallSwitch` option expose the light in HomeKit as `off` instead of No Response??

**Comment by ebaauw** [comment]
> Shouldn't the `wallSwitch` option expose the light in HomeKit as off instead of No Response??

Yes, and it does.  homebridge-hue does _not_ set the light to _No Response_: when a HomeKit app requests a value, homebridge-hue immediately returns the value from memory (irrespective of the `wallSwitch` setting, irrespective whether the light is reachable).

As I said before, _No Response_ is typically caused by failed communication between the HomeKit app and Homebridge, and _not_ by failed communication between homebridge-hue and the light.

**Comment by santheman-nl** [comment]
Goedemiddag,
Ik heb zowel de Hue Bridge, de Ikea Tradfri bridge én een Homebridge draaien met daarop uw homebridge-hue plugin. Dit vanwege een paar Innr ledstrips die niet "meegenomen" worden bij Hue. Nu staan dus bijna alle lampen 2 keer in Homekit. De ikea bridge kan ik niet uitzetten ivm slimme stekkers en ik wil graag ook hue blijven gebruiken. Is er een mogelijkheid dat slechts 1 lamp "doorgegeven" wordt aan Homekit? Ik ben vrij nieuw in deze materie, dus  ik kijk uit naar uw hulp.

**Comment by ebaauw** [comment]
Homebridge Hue doesn't support the Trådfri hub.  It uses a completely different API.

Set `nativeHomeKitLights` to true in config.json to prevent Homebridge Hue from exposing lights already exposed natively by the Hue bridge.
