### ISSUE TITLE
initial install of version v0.11.6

### ISSUE THREAD

**Issue by skipper79** [ebaauw/homebridge-hue#421]
I tried to install homebridge-hue via the UI 'plugin' of Homebridge 0.4.45 which is installed in a 'docker' [this](https://github.com/oznu/docker-homebridge) site

But get no result, probably due to a wrong directory...
![image](https://user-images.githubusercontent.com/3088540/50655244-d16f8f00-0f8f-11e9-9cf8-6ee1613df622.png)

I checked the directories and conclude that the modules are stored in /home/pi/homebridge/**config**/node_modules
![image](https://user-images.githubusercontent.com/3088540/50656980-51e4be80-0f95-11e9-88dd-4a9f09c5b58e.png)
Is it possible to change  #this?

**Comment by ebaauw** [comment]
I have no experience running homebridge in a Docker container.  From what I read, it's causing more troubles than benefits.  I run homebridge natively on Raspbian Stretch.

Having said that, some pointers:
- I think you're checking the directories on the host system rather than from within the container?  The `npm` logfile should be within the container.
- What versions of `node` and `npm` are you using?  Are you sure you're on a recent version of `npm`?
- Normally, `homebridge` and its plugins are installed globally, using `npm -g install ...` into `/usr/lib/node_modules` or `/usr/local/lib/node_modules` (depending on how you installed NodeJS).  With that setup, the dependencies per plugin are in `/usr/lib/node_modules/homebridge-plugin/node_modules`.  In your installation, it looks like the dependencies are installed "flattened" in the main `node_modules` directory.
- I think `npm` fails to install homebridge-hue in the last step, where it creates symbolic links from the `cli` utilities by homebridge-lib and homebridge-hue-utils into `/usr/bin` or `/usr/local/bin`.

**Comment by skipper79** [comment]
Thanks Erik for you reply. I thought a docker is quite simple to install with less experince ;-)
I moved the hue-plugin to map `node_modules` and now the plugin is recognize! Also an update of nodeJS was necessary.

**Comment by skipper79** [comment]
after updating `homebridge` the plugin  got an error;
`
homebridge_1  | [1/6/2019, 12:58:58 PM] ====================
homebridge_1  | [1/6/2019, 12:58:58 PM] ERROR LOADING PLUGIN homebridge-hue:
homebridge_1  | [1/6/2019, 12:58:58 PM] Error: Cannot find module 'deferred'
homebridge_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
homebridge_1  |     at Module.require (internal/modules/cjs/loader.js:637:17)
homebridge_1  |     at require (internal/modules/cjs/helpers.js:22:18)
homebridge_1  |     at Object.<anonymous> (/homebridge/node_modules/homebridge-hue/lib/HuePlatform.js:16:18)
homebridge_1  |     at Module._compile (internal/modules/cjs/loader.js:689:30)
homebridge_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
homebridge_1  |     at Module.load (internal/modules/cjs/loader.js:599:32)
homebridge_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
homebridge_1  | [1/6/2019, 12:58:58 PM] ====================
`

**Comment by ebaauw** [comment]
Looks like the dependencies of homebridge-hue (like `deferred`) aren't installed, or at the wrong directory.

**Comment by ebaauw** [comment]
This looks like an issue with you Docker setup.  I'm sorry, I cannot help you with that.

**Comment by skipper79** [comment]
ok, thnx so fare!
