### ISSUE TITLE
Gledopto 0% to x% doesn't turn on ledstrip

### ISSUE THREAD

**Issue by Yardco** [ebaauw/homebridge-hue#424]
#### Issue

My Gledopto RGB+CCT Controller doesn't turn on when adjusting the brightness from off to a random value in homekit (sliding the brightness slider up). My hue led strip (and other dimmable lights) turn on right away when doing this but the Gledopto strip just stays off and doesn't turn on. Tapping the icon to turn it off and back on again works tho. Is this expected behavior for the Gledopto controller or something that could be added?

**Comment by ebaauw** [comment]
homebridge-hue doesn’t do anything in this area; it’s probably between the GLEDOPTO and deCONZ.   I suspect the GLEDOPTO doesn’t react well to the _Goto Level with On/Off_ command, which deCONZ would send when PUTting `{“on”: true, “bri”: 123}`.  When only PUTting `{“on”: true}`, deCONZ sends an _On_ command.

**Comment by ebaauw** [comment]
I checked my GLEDOPTO floodlight (which has an RGBW controller inside).  It turns on when sliding brightness up from off, on the white light endpoint as well as on the colour light endpoint.  If memory serves, the RBG+CCT only has one light endpoint, so that might react differently.

Could you double-check by running from the command line (while the light is off):
```
$ ph put /lights/xx '{“on”: true, “bri”: 123}'
```
versus (again, while the light is off):
```
$ ph put /lights/xx '{"on": true}'
```
I wouldn't be surprised if the RBG+CCT controller would react differently when it was displaying a white vs a colour before turning off.

**Comment by Yardco** [comment]
Tried both commands with the controller turned off after setting it to white and a colour, but bot unfortunately gave the same response:

$ ph put /lights/xx '{“on”: true, “bri”: 123}':
`ph put: error: Unexpected token “ in JSON at position 1`

$ ph put /lights/xx '{"on": true}'
`ph put: error: 6 parameter, on, not available`

**Comment by Yardco** [comment]
Tried both again and:

`$ ph put /lights/xx/state '{"on": true, "bri": 123}'`
sets the color but does not turn on the led strip. Also tried to set brightness first and send the on state after, but led strip just stays off. 

`$ ph put /lights/xx/state '{"on": true}'`
does turn on the led strip

**Comment by ebaauw** [comment]
What do you mean "sets the colour"?  Do you have a single 5-channel light strip connected to the controller or separate colour vs white light strips?  The controller powers the CW, WW channels when setting `ct` and the RGB channels when setting `xy`.  It will not power the white and colour channels at the same time.  See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/945.

**Comment by ebaauw** [comment]
> when running the command I can see the device adhering the brightness value in the home app, but nothing actually happens. After a few seconds the home app displays the light as off again

deCONZ keeps a cache of the light states.  After sending the _Move to Level (with on/off)_ command, it updates the cached value for `on` and `bri`, assuming (wrongly) that the light will take these values.  When it next polls the light, it notices that the light hasn't, and updates its cache accordingly.  homebridge-hue simply gets the cached data from deCONZ.

It would seem the real problem is with the GLEDOPTO firmware, not handing the command correctly.  

As a workaround, you could try setting `waitTimeUpdate: 0` in config.json.  That should cause homebridge-hue to send two separate commands to deCONZ, `{"on": true}` and `{"bri": 123}`, instead of a combined `{"on": true, "bri" 123}`.  deCONZ, in turn will send two commands to the lights,  _On_, followed by a plain _Mode to Level_ command.  I hope with that setting, the light will go on.

Note that the setting will probably do more harm than good, especially when you use HomeKit scenes, as `waitTimeUpdate` is used for all lights.  However, if this works, I might be able to override the default 20ms for just the RGB+CCT.

**Comment by Yardco** [comment]
setting `waitTimeUpdate: 0` works but it does produce a flickering effect when turning the led strips on from 0 (as if the controller turns on, quickly turns off and on again within a few ms)

Also seeing a few errors popping up:
` [Hue] Philips hue: bridge request 18: put /lights/xx/state {"bri":10}`
and
`[Hue] Philips hue: bridge error 201: parameter, bri, is not modifiable. Device is set to off.`

But it does reflect the behavior of hue bulbs a lot beter this way.

**Comment by Yardco** [comment]
Should have checked more thoroughly before posting 🤦‍♂️, the errors mentioned above are also being displayed without `waitTimeUpdate:` set to 0.

**Comment by ebaauw** [comment]
Could you please attach the debug dump file and two debug log files while controlling the GLEDOPTO: one when `waitTimeUpdate` is set to 0, and one when it's not present in config.json.  See https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by ebaauw** [comment]
Thanks.

These are different (firmware) versions of the RGB+CCT controller than the one I had on loan.  The have `modelid` of `GL-C-008` instead of `GLEDOPTO`.  Also, they're different versions: `1.0.3` and `1.0.6` (mine was `1.0.2`).  I'd love to see what they look like when paired with deCONZ...

With `waitTimeUpdate` of 0, when changing brightness while the light is off:
```
[2019-1-19 13:17:03] [Hue] Gledopto rgb+cct rechts: homekit brightness changed from 44% to 10%
[2019-1-19 13:17:03] [Hue] Philips hue: bridge request 12: put /lights/5/state {"bri":25}
[2019-1-19 13:17:03] [Hue] Gledopto rgb+cct rechts: homekit on changed from 0 to 1
[2019-1-19 13:17:03] [Hue] Philips hue: bridge request 13: put /lights/5/state {"on":true}
...
[2019-1-19 13:17:03] [Hue] Philips hue: bridge request 12: put /lights/5/state {"bri":25}
[2019-1-19 13:17:03] [Hue] Philips hue: bridge error 201: parameter, bri, is not modifiable. Device is set to off.
[2019-1-19 13:17:03] [Hue] Philips hue: bridge request 13: ok
```
So homebridge-hue receives the change in _Brightness_ before receiving the change in _On_.  As it doesn't collect multiple changes into a single request, the PUT of `state.bri` is rejected by the Hue bridge, because the light is off; the PUT of `state.on` succeeds.

The next change of _Brightness_ succeeds, since the light is now on:
```
[2019-1-19 13:17:03] [Hue] Gledopto rgb+cct rechts: homekit brightness changed from 44% to 15%
[2019-1-19 13:17:03] [Hue] Philips hue: bridge request 16: put /lights/5/state {"bri":38}
[2019-1-19 13:17:03] [Hue] Philips hue: bridge request 16: ok
```

With default `waitTimeUpdate`, when changing brightness while the light is off:
```
[2019-1-19 13:15:10] [Hue] Gledopto rgb+cct rechts: homekit brightness changed from 11% to 4%
[2019-1-19 13:15:10] [Hue] Gledopto rgb+cct rechts: homekit on changed from 0 to 1
[2019-1-19 13:15:10] [Hue] Philips hue: bridge request 12: put /lights/5/state {"bri":10,"on":true}
[2019-1-19 13:15:10] [Hue] Philips hue: bridge request 12: ok
```
homebridge-hue combines the two changes into a single PUT, updating both `state.bri` and `state.on`.  The Hue bridge is happy with this, and thinks the light is on.  So do homebridge-hue and HomeKit.  When the _Brightness_ is changed next, HomeKit doesn't send a change notification for _On_, homebridge-hue issues a PUT for `state.bri`, and the Hue bridge happily accepts that:
```
[2019-1-19 13:15:10] [Hue] Gledopto rgb+cct rechts: homekit brightness changed from 4% to 7%
[2019-1-19 13:15:10] [Hue] Philips hue: bridge request 14: put /lights/5/state {"bri":18}
[2019-1-19 13:15:10] [Hue] Philips hue: bridge request 14: ok
```
The light is still off, so nothing actually happens.

When the Hue bridge next polls the light, it notices that it's actually off and updates `state.on`.  At this moment, homebridge-hue and HomeKit still think the light is on.  So the next change in _Brightness_ results in a PUT of only `state.bri`, which the Hue bridge now rejects:
```
[2019-1-19 13:15:12] [Hue] Gledopto rgb+cct rechts: homekit brightness changed from 25% to 28%
[2019-1-19 13:15:12] [Hue] Philips hue: bridge request 28: put /lights/5/state {"bri":71}
[2019-1-19 13:15:13] [Hue] Philips hue: bridge request 28: put /lights/5/state {"bri":71}
[2019-1-19 13:15:13] [Hue] Philips hue: bridge error 201: parameter, bri, is not modifiable. Device is set to off.
```
When homebridge-hue next polls the Hue bridge, it learns that `state.on` is false and updates HomeKit:
```
[2019-1-19 13:15:13] [Hue] Philips hue: bridge request 36: get /lights
[2019-1-19 13:15:13] [Hue] Philips hue: bridge request 36: ok
[2019-1-19 13:15:13] [Hue] Gledopto rgb+cct rechts: light on changed from true to false
[2019-1-19 13:15:13] [Hue] Gledopto rgb+cct rechts: set homekit on from 1 to 0
```
After that, we're back at the initial situation, where _Brightness_ is changed while (HomeKit knows that) the light is off.

So with the default `waitTimeUpdate`, the Hue bridge error is caused by the delay in updating HomeKit due to homebridge-hue having to poll the Hue bridge.  The Hue bridge doesn't send push notifications when it updates `state.on`.  You might increase the polling frequency by setting `heartrate: 2` in config.json.

With `waitTimeUpdate` of 0, the Hue bridge error is caused by the HomeKit app sending _Brightness_ before _On_.  However, in this case, the light does turn on, and subsequent changes in _Brightness_ work as intended.  I think the GLEDOPTO turn on at full brightness, instead of previous brightness as e.g. the Hue lights, hence the flickering.

I could change homebridge-hue to keep a `waitTimeUpdate` setting per light, and whitelist this model GLEDOPTO to use `waitTimeUpdate` of 0, so other lights continue to work with the default `waitTimeUpdate`.  I cannot work around the flickering, nor the Hue bridge error, though.

**Comment by Oggymator** [comment]
Hi Erik, yes we changed the Name of the produces with item ID and die some hardware and software improvements.
If I can help you with any information about GLEDOPTO products you can mail me.
Regards 
Tobias

**Comment by ebaauw** [comment]
Hey @Oggymator long time no hear.

I'm happy about the _Model Identifier_ change (assuming the RGBW controller now has a different name).  This makes it a lot easier to figure out what model the software is dealing with.  Do you the values for the other products?

Can you get confirmation that the controller no longer support the _Move to Level (with On/Off)_ command?

**Comment by Oggymator** [comment]
@ebaauw 
will email you a list of ID and kind of product.
Maybe it is a software bug, can you explain more the problem?

**Comment by Yardco** [comment]
@Oggymator See OP, the GLEDOPTO RGB+CCT controller won't turn on when sliding from 0% upwards. All my other Hue compatible lights do this without issue except the two GLEDOPTO controllers I have

@ebaauw If @Oggymator wont be able to help out i'd say go ahead and whitelist the GL-C-008 controller to use waitTimeUpdate: 0 if possible. I'd rather have the flickering then not being able to quickly turn on the controller from 0%.

**Comment by Oggymator** [comment]
pls explain me how I can test it an easy way with hue bridge or deconz.
I will check it. if we can change it by modify software, you have send the controller to my german company and we can update it.

**Comment by ebaauw** [comment]
If you PUT the light state with `{"on": true, "bri": 123}` while the light is off, it doesn't turn on.  If you PUT `{"on": true}` is does come on.  In the first case, the Hue bridge sends a _Move to Level (with On/Off)_ command (0x04) to the _Level Control_ cluster (0x0008); in the second case it sends an _On_ command (0x01) to the _OnOff_ cluster (0x0006).  Same for deCONZ.

**Comment by ebaauw** [comment]
@Yardco could you try v0.11.11-0 (`sudo npm -g i homebridge-hue@beta`)?  It should apply a `waitTimeUpdate` of 0 to the `GL-C-008`, irrespective of the config.json setting.

**Comment by Yardco** [comment]
Just updated, dimming from 0% upwards now works 👍 Thanks for the great help, homebridge-hue is turning out to be an unmissable plugin!
