### ISSUE TITLE
Support Thermostat

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-hue#426]
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1098.

**Comment by ebaauw** [comment]
I added support for ZHAThermostat and CLIPThermostat, but cannot test it, as CLIPThermostat is not yet implemented in deCONZ, and I don't have a thermostat myself.

Also, deCONZ doesn't expose `state.lastupdated`, `config.reachable`, and `config.on` for the ZHAThermostat.  I think homebridge-hue:
- Will report "n/a" for _Last Updated_;
- Might report the Thermostat's _Status Fault_ as true;
- Will report errors when trying to change _Enabled_.

**Comment by ebaauw** [comment]
In [v0.11.7](https://github.com/ebaauw/homebridge-hue/releases/tag/v0.11.7)

**Comment by thecem** [comment]
Hi ebaauw which thermostat data do you need ? I have Netatmo and Tado....

**Comment by ebaauw** [comment]
I need the data homebridge-hue collects for a thermostat that talks Zigbee and connects to deCONZ, like the Bitron or the Eurotronic.

**Comment by thecem** [comment]
Ah OK, those one I dosn´t have.

**Comment by tkintscher** [comment]
I do not (yet) have a deCONZ/Zigbee thermostat to test this, but for my current integration of Z-Wave thermostats into HomeKit I set the characteristics as follows:
* currentTemperature: sensed by the thermostat
* targetTemperature: whatever is set in HomeKit, but I call `round(input*2)/2` to round to 0.5 degrees (values in between tend to be rejected by the thermostat)
* targetHeatingCoolingState: whatever is set in HomeKit. My scenes only pick Auto or Off. Off is "Off" at the device, all other settings get translated to "Heat".
* currentHeatingCoolingState: "Off" if the device says "off" _or_ if the valve opening is below 10%. Otherwise "Heat".

This shows in the Home app as follows:
![7j52bbdkrccz6ea mq01yw_thumb_43f](https://user-images.githubusercontent.com/7606910/51803699-5c266f80-2258-11e9-9b82-0fe906ffd0c4.jpg)
Orange circles indicate rooms where the thermostat is actually heating (device is configured to "Heat" and valve is >10% open), green circles indicate rooms where the mode in HomeKit is set to "Auto" (i.e. device mode = "Heat"), but the valve is currently closed, because the temperature is close to the target. (Not shown here but gray circles would show rooms where the thermostat is turned off)

Maybe this would be a nice addition here (provided that the current valve opening is reported, I don't know about that for the Zigbee thermostats).

**Comment by dergreg** [comment]
Additionally, is there any chance to display errors reported (such as valve adjustment failures etc.) within HomeKit? deConz recently added the necessary clusters, at least for the eurotronics thermostat.

**Comment by tkintscher** [comment]
I have now tested with the Eurotronic thermostat. Adjusting the setpoint and showing the current temperature works. For the setpoint however, I had to insert
```
targetTemperature = Math.round(targetTemperature / 0.5) * 0.5
```
at line 2152 in `HueSensor.js`, because even though the HomeKit-Apps only show 0.5 degree steps, at least the slider in Apple's Home app tends to return values in between.

The heating mode does not seem to be supported by this device at all. The only way to turn it off (e.g. when windows are opened) is by lowering the temperature. The minimum in the thermostat is 5°C, but the minimum in HomeKit is 10°C...
However, I would not map "Off" -> 5°C, because there is no way to reverse it (e.g. switching from "Off" to "Heat", it's not clear what the temperature should be).

Mapping "Off" to a valve opening of 0% could be an alternative, but I also wouldn't recommend it, as this provides no anti-freeze protection (and is currently not exported through the REST API).

**Comment by ebaauw** [comment]
> I have now tested with the Eurotronic thermostat.  Adjusting the setpoint and showing the current temperature works.

So the Home app show the tiles as intended (as for the Z-Wave thermostats)?

>  but I call round(input*2)/2 to round to 0.5 degrees (values in between tend to be rejected by the thermostat)
> even though the HomeKit-Apps only show 0.5 degree steps, at least the slider in Apple's Home app tends to return values in between.

@tkintscher the best solution for this would be to set the `minStep` property of the _TargetTemperature_ characteristic to 0.5.  To be on the safe side, we would also need to round the value retrieved from deCONZ to 0.5°C (instead of to 0.1°C).

**Comment by ebaauw** [comment]
Will include that in next version.

Did you try to control the thermostat from Eve?  Does it show the temperature history?

**Comment by tkintscher** [comment]
> Will include that in next version.

Many thanks for your effort and this great tool!

> Did you try to control the thermostat from Eve? Does it show the temperature history?

Yes, the target temperature can be controlled from the Eve App as well.
Eve also keeps a history of the local (measured) temperature (not much yet, because I reset it after some experimenting):

![img_4cf86ec862f7-1](https://user-images.githubusercontent.com/7606910/52230587-1f8df000-28b8-11e9-8b3e-364b2565806d.jpeg)

**Comment by tkintscher** [comment]
That triangle doesn't show any history, there's an empty plot with no measurements:
![img_59cea34eab50-1](https://user-images.githubusercontent.com/7606910/52232482-f2900c00-28bc-11e9-8add-60abe47d0727.jpeg)

Here is the file, the `setTemp` entries exist: [history_00158D000192D18D.json](https://github.com/ebaauw/homebridge-hue/files/2829560/history_00158D000192D18D.json.txt)

Btw, what is "Mode" -- is it the "CurrentHeatingCoolingState" characteristic? I'm confused because the options for my other (Z-Wave, not using homebridge) thermostat are off-heat-cool-on. How did you hide the heat/cool options?

**Comment by tkintscher** [comment]
I guess you're refering to [that comment](https://github.com/simont77/fakegato-history/issues/11#issuecomment-357458763). 
The three dots lead to a larger version of the graph. There's a "compare" toggle switch, which adds another line. It seems to be the same graph but shifted in time (it is not the setpoint, because that was set to 20C for the last hours). Actually the "Compare" option is the same as for all other measurements (like the Xiaomi multisensor):

![img_0920](https://user-images.githubusercontent.com/7606910/52236349-eb6dfb80-28c6-11e9-838c-ac3b7487cbca.PNG) ![img_0921](https://user-images.githubusercontent.com/7606910/52236350-eb6dfb80-28c6-11e9-8473-eaa4ebe6b717.PNG)

Thanks for the explanation about the characteristics. I've always had trouble finding out which properties are supported by which device classes.
If I find some time later this week, I can play around with the options and see what works best here.

**Comment by ebaauw** [comment]
Supported in v0.11.4, but needs https://github.com/dresden-elektronik/deconz-rest-plugin/pull/1230.

**Comment by ebaauw** [comment]
Found a bug in thermostat history, fixed in https://github.com/ebaauw/homebridge-hue/commit/a45beee0abc61a5236e591eeffc401caf428e55a, which will be included in the next version.

Closing this for now.  Until the schedule for the Eve Thermo has been reverse engineered, there's nothing I can do.
