### ISSUE TITLE
Xiaomi Humidity Sensor doesn't trigger

### ISSUE THREAD

**Issue by brandungskieker** [ebaauw/homebridge-hue#436]
#### Issue
I created a scene in Homekit/Homebridge (Eve-App):
_IF Humidity becomes >=55% THEN Start Scene "Switch Off Osram Smart Plug"_
But the humidity value doesn't trigger anything. The values appear correctly in HomeKit. And if I add any other trigger event (e.g. switch on a light) the scene will be triggered correctly. 
I had a burn-down of my RasPi SD card, so I have a completely new installed base. 

Does anyone have a suggestions? Maybe it has to do with a value-formatting mismatch between DeConz/Homebridge/Hue/HomeKit?

**Comment by ebaauw** [comment]
HomeKit automations run on your HomeKit Hub (AppleTV, HomePod, or iPad) - deCONZ, homebridge, homebridge-hue have little to do with that (other than pushing the changed characteristic value that triggers the automation).  The most common causes for HomeKit automations not running are:
- The HomeKit hub doesn't have a connection to homebridge, causing it not to receive the notification that the characteristic has changed, that would trigger the automation.  Check with netstat on your homebridge machine that homebridge (port in config.json) has an incoming connection from the hub.  Reboot the hub if needed.  I find my AppleTV sometimes doesn't reconnect (quickly enough) when homebridge restarts.
- The automation hasn't been synched (over iCloud) to the HomeKit hub.  There's no way to check this directly, but typically it's remedied by turning off the automation on one iDevice, wait for it to replicate (become visible) on the other iDevices.  Turn it back on and again wait for the change to propagate.

If both your humidity sensor and plug are connected to deCONZ, I would use deCONZ rules instead of HomeKit automations.  Way faster and more reliable in my experience.  I only use HomeKit automation for triggers, conditions, or action on devices that are not connected to deCONZ (e.g. switching on the Sonos when the Hue motion sensor detects motion, or dimming the lights when the Sonos PlayBar detects TV input).

**Comment by brandungskieker** [comment]
Thanks a lot! Fast and accurate help, as I know ;-)
Is there any possibility to create deCONZ rules with an GUI instead of using REST API? I didn't find a way to create rules for temperature/humidity sensors in the Phoscon Web-App.

**Comment by Einstein2150** [comment]
> Thanks a lot! Fast and accurate help, as I know ;-)
> Is there any possibility to create deCONZ rules with an GUI instead of using REST API? I didn't find a way to create rules for temperature/humidity sensors in the Phoscon Web-App.

@brandungskieker 
Maybe too late but you can create really simple rules in Node Red. I created my humidity-rule there and it works quick and accurate.
