### ISSUE TITLE
Groups in Homebridge

### ISSUE THREAD

**Issue by tomfritz1** [ebaauw/homebridge-hue#443]
I have a strange behavior in Homekit. I am using most current version of deconz/homebridge/homebridge-hue. I have exposed groups from deconz to homebridge and I can see all the groups in Homekit. But I cannot turn ON the groups in Homekit – I can turn them OFF (if turned ON in Phoscon) and I can unregularly change brightness. Any ideas? (I have played with all different values in config and do not see any error in debug).
Second issue: I have a lot of sensors including new and old version of Xiaomi Temperature/Humidity sensors. The new versions show up as one single sensor in Homekit which is perfect. The old version shows two sensors (temperature and humidity separate) -> having > 10 temperature sensors it would be suitable if the two sensors could be combined like it is exposed for the new version of the sensor.

**Comment by ebaauw** [comment]
> But I cannot turn ON the groups in Homekit – I can turn them OFF (if turned ON in Phoscon)

The group's `state.all_on` attribute is mapped to the (standard) HomeKit _On_ characteristic; `state.any_on` is mapped to a (custom) _Any On_ characteristic.  Apple's Home app only shows the standard _On_ characteristic.  Consequently, you can only turn on a group when at least one light is (reported by deCONZ as) off, and you can only turn off a group when all lights are (reported by deCONZ as) on.  Use another HomeKit app (like Eve) to see _Any On_, so you can turn off a group when only some lights are (reported by deCONZ) as off.

I'm not quire sure what you mean by "cannot turn ON the groups".  Does the Home app not allow you to turn on the group, or do the lights not react when you turn on the group in the Home app?  Of the latter, please attach a debug log file (see https://github.com/ebaauw/homebridge-hue#debug-log-file), so I can see what's going on.

> and I can unregularly change brightness.

I have no idea what you mean here.

>  The old version shows two sensors (temperature and humidity separate) -> having > 10 temperature sensors it would be suitable if the two sensors could be combined like it is exposed for the new version of the sensor.

homebridge-hue exposes each sensor device as a single HomeKit accessory, with separate HomeKit services for _Temperature_, _Humidity_, and, when present, _Pressure_.  It's up to the HomeKit app, how this is displayed.  Apple's Home app displays a tile per (standard) service (it supports) and ignores the (custom) _Pressure_ service.

> The new versions show up as one single sensor in Homekit which is perfect.

If you only see one tile for the new Temperature/Humidity sensors, I'm afraid the deCONZ REST API hasn't fully exposed the sensor.  Could you attach the debug dump file (see https://github.com/ebaauw/homebridge-hue#debug-dump-file), so I can see what's going on?

**Comment by tomfritz1** [comment]
Thanks for your prompt response. I cannot "turn ON" the group means: when I click on the group in homekit or eve there is no reaction (on the symbol it says "Keine Antwort" - "No response"). But when the group is on I can turn it OFF by clicking on the group in homekit or eve.

![image-1](https://user-images.githubusercontent.com/36574732/52903729-14c14c80-3222-11e9-808e-c3c579a47221.jpg)

Regarding temperature - there is a misunderstanding

You can see on the screenshot below:
- Keller: this is a new model of the sensor (Aqara) - shows humidity and temperature in one symbol - perfect
- TempSchlaf: this is the old model of the sensor (Xiaomi) - shows humidty and temperatrue in two symbols - would like to combine this in one symbol as in Keller

![image](https://user-images.githubusercontent.com/36574732/52903700-b5fbd300-3221-11e9-8c6a-a06da3fe63b0.png)

**Comment by tomfritz1** [comment]
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/2872288/homebridge-hue.json.gz)

here is the dump file

**Comment by ebaauw** [comment]
> You can see on the screenshot below:
> * Keller: this is a new model of the sensor (Aqara) - shows humidity and temperature in one symbol - perfect
> * TempSchlaf: this is the old model of the sensor (Xiaomi) - shows humidty and temperatrue in two symbols - would like to combine this in one symbol as in Keller

So the round Mi temperature/humidity sensors only provide temperature and humidity, whereas the square Aqara weather sensors provide temperature, humidity, and air pressure.  Consequently, homebridge-hue exposes the Mi sensor with two services and the Aqara sensor with three.  As I said above, it's up to the HomeKit app how to display this.  The Eve app recognises the square sensor as an Eve Weather, causing it to combine the three services in a single tile.  It doesn't recognise the round sensors, because air pressure is missing.  If you check Apple's Home app, it will show both sensor types as two tiles.

**Comment by ebaauw** [comment]
> I cannot "turn ON" the group means: when I click on the group in homekit or eve there is no reaction (on the symbol it says "Keine Antwort" - "No response"). But when the group is on I can turn it OFF by clicking on the group in homekit or eve.

The _No Response_ status is typically caused by HomeKit itself, not by homebridge nor by homebridge-hue.  HomeKit doesn't like configuration changes.  It might take some time, before HomeKit is happy after restarting homebridge, especially of you added or changed the exposed accessories.  Eve might not be able to clear this status; sometimes you need to switch rooms in Apple's Home app to clear this status by forcing a refresh of the accessories.

**Comment by ebaauw** [comment]
Could you try v0.11.16-0 (install by `sudo npm -g i homebridge-hue@beta`).  It supports a new config.json parameter `"forceEveWeather"`.  When set to `true`, temperature/humidity sensors are exposed as an Eve Weather, by adding a dummy _Air Pressure_ service.

**Comment by tomfritz1** [comment]
Amazing - works perfectly (see below) - thank you very much!!!
(I will give this hint to hansemann as well - https://github.com/hannseman/homebridge-mi-hygrothermograph/issues - I am using two LCD sensor and they could do the same....)

The group issue is unfortunetly still not woking - created a new room in homekit where I put the group, waited 12h and still not reaction when clicking it "ON"
![image-1](https://user-images.githubusercontent.com/36574732/52908877-8c24c980-327e-11e9-8036-1d79325d8e85.jpg)

**Comment by ebaauw** [comment]
> Amazing - works perfectly (see below)

Cool!

> The group issue is unfortunetly still not woking

Could you attach a debug log file, capturing when you (try to) turn the group on and off?  Are the red exclamation marks in the screenshot also non-responding accessories?  Are they exposed by homebridge-hue or by another homebridge plugin?

**Comment by tomfritz1** [comment]
The red exclamation marks are gone after restart :-) 

The log is attached - I had to copy&paste it from terminal - the created .log is empty. Hope that works.

The group I tested is called "Esstisch" 
[homebridge.log](https://github.com/ebaauw/homebridge-hue/files/2873186/homebridge.log)

**Comment by ebaauw** [comment]
As far as I can tell, you only turned off the group from HomeKit.  homebridge-hue sends the right command to deCONZ, and deCONZ reports the three lights as off, and changes `state.all_on` of the other groups that these lights are in.  If the lights didn't go off, the problem lies with deCONZ.

If you're sure you tried to turn the group on from HomeKit, that change wasn't forwarded to homebridge-hue.  That would indicate a problem with homebridge, or with the communication between HomeKit and homebridge.

You didn't copy the start of the logfile, so I cannot see what other plugins you're running, but there seem to be quite a lot.  I'm counting 69 accessories by homebridge-hue and 15 by Tahoma.  I cannot see what you other plugins are doing, but you might be hitting the 99 accessories per HomeKit bridge limit, when you added the groups.  I strongly suggest you split your homebridge setup into multiple installations, and run homebridge-hue as the only plugin in one of these.
