### ISSUE TITLE
ph outlet: error: invalid SSL certificate

### ISSUE THREAD

**Issue by baerenmarke90** [ebaauw/homebridge-hue#456]
#### Issue
Hi,
I can't add more Osram Smart+ Plugs with Homebridge-hue v0.11.20. 
I always get bad ssl certificate. I've added an new hue user, but this didn't work.

What can I do?

#### Log Messages

```
pi@raspberrypi:~ $ ph -H 192.168.178.20 -u Hue-User outlet -v
ph outlet: error: invalid SSL certificate
```

**Comment by ebaauw** [comment]
`ph` doesn't like the SSL certificate presented by the Hue bridge.  Unfortunately, I don't yet log this in de debug log.

Can you open `https://192.168.178.20` in your webbrowser?  It will probably bitch about an invalid certificate, because the Hue bridge uses a self-signed root certificate.  Just trust it and accept the are you sure? prompt.  Then, can you press the lock symbol in the address bar to show the certificate and make a screenshot?

I need to see the subject, issuer, and serial number.

Here's an example using Safari on macOS:
![Screenshot 2019-04-09 at 21 09](https://user-images.githubusercontent.com/22179355/55828182-1fa2aa00-5b0c-11e9-92af-7e10e0b39153.png)

**Comment by baerenmarke90** [comment]
Hi, Thanks for your quick answer.

Here's the screenshot

<img width="526" alt="image" src="https://user-images.githubusercontent.com/49028921/55828983-e2d7b280-5b0d-11e9-921a-ecfc0869956d.png">

**Comment by ebaauw** [comment]
That is indeed not a valid Hue certificate.  Looks like your AVAST Web Shield has screwed it up, see https://blog.avast.com/2015/05/25/explaining-avasts-https-scanning-feature/.

It should work if you turn Avast off, or tell it not to check your Hue bridge.

**Comment by baerenmarke90** [comment]
Oh, Thanks! 

Here's the right certificate:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/49028921/55829975-4531b280-5b10-11e9-9b2f-47a87feaf5e7.png">

**Comment by ebaauw** [comment]
And you still get an _Invalid Certificate_ error, with AVAST turned off, I'm afraid?  The issuer common name (Aussteller Allgemeneiner Name)  is `root-bridge` instead of the bridge serial number.

What Hue bridge version are you on?  What's the output of `ph -H 192.168.178.20 config`?

**Comment by baerenmarke90** [comment]
Hmm, I've turned off the https scanning..
Here's the output:

`pi@raspberrypi:~ $ ph -H 192.168.178.20 config
{
  "name": "Philips hue",
  "datastoreversion": "80",
  "swversion": "1931069120",
  "apiversion": "1.31.0",
  "mac": "ec:b5:fa:03:6d:1e",
  "bridgeid": "ECB5FAFFFE036D1E",
  "factorynew": false,
  "replacesbridgeid": null,
  "modelid": "BSB002",
 `

**Comment by ebaauw** [comment]
Should be working in homebridge-hue-utils@2.0.16.  If you re-install homebridge-hue, you should get a new version of `ph`.

**Comment by baerenmarke90** [comment]
Thank you! After re-installing, it works.

pi@raspberrypi:~ $ ph -H 192.168.178.20 -u ezvO7mFVqG9Iaf288GhVRq78THceoWCd5Gver7UL outlet -v
ph outlet: /resourcelinks/25250: 4 outlets
