### ISSUE TITLE
innr lights getting misidentified

### ISSUE THREAD

**Issue by jaytay79** [ebaauw/homebridge-hue#46]
Following on from some issues with my homebridge set-up I had to remove homebridge and re-add it. I also updated all my plugins at the same time. I have 4 innr GU10 bulbs in my kitchen and since re-doing the HomeKit set-up I now find that all but one are getting mis-identified - [like this](https://cloud.githubusercontent.com/assets/10902647/21962919/d9eaadd4-db27-11e6-81d3-60bf81b06346.png). Note that when I first re-added homebridge all of these 4 lights appeared correctly as lights....

I attempted to perform an Identify on the homebridge accessory using Elgato Eve as per the troubleshooting instructions but no debug bridge json file is getting created when I do it....

The relevant part of my config.json is below, and here is my [slightly edited log file](https://github.com/ebaauw/homebridge-hue/files/706617/log.txt)

```
{
		"platform": "Hue",
		"name": "Hue",
		"host": "",
		"users": {
			"removed": "removed"
		},
		"heartrate": 5,
		"timeout": 5,
		"lights": true,
		"philipslights": false,
		"groups": false,
		"group0": false,
		"rooms": false,
		"sensors": true,
		"clipsensors": true,
		"schedules": false,
		"rules": false,term
                "excludeSensorTypes": [ "CLIP", "ZLLSwitch", "ZGPSwitch", "Geofence"]
	}
```

Quick edit: I removed the accessories and persist folders, removed homebridge and re-added it again and everything is showing correctly again, for now.....

**Comment by ebaauw** [comment]
> I have 4 innr GU10 bulbs in my kitchen and since re-doing the HomeKit set-up I now find that all but one are getting mis-identified - like this.

I've never seen that cloud symbol in Eve.  I only have some innr RB 162 bulbs, UC 110 strips, and PL 110 pucks, but the GU10 spots should work just as well.

> I removed the accessories and persist folders, removed homebridge and re-added it again and everything is showing correctly again, for now.....

I'd guess your HomeKit database was seriously out of sync with your HomeKit devices (i.c. homebridge).  Also note in the screenshot that Eve sees the _Kicthen light 4_ as on/off light, instead of dimmable light (which is it from the log).

> I attempted to perform an Identify on the homebridge accessory using Elgato Eve as per the troubleshooting instructions but no debug bridge json file is getting created when I do it....

You need to do the Identify on the Hue bridge accessory that homebridge-hue creates (where you can now control the heartrate), not on the homebridge bridge accessory.

>  here is my slightly edited log file

Looks fine to me.  All four innr lights are recognised by homebridge-hue as dimmable lights.

> The relevant part of my config.json is below
[...]
"rules": false,term
[...]

I assume this is cut/paste error (otherwise home bridge would crash on an invalid config.json file)?

**Comment by jaytay79** [comment]
Everything was working fine, up until I had to re-do the HomeKit config. At some point after this is where it went wrong however in the absence of any definitive errors and the fact it's now working OK I'm chalking this one up to random homebridge/HomeKit weirdness :)
