### ISSUE TITLE
Add offset parameter to ZLLTemperature sensor to be controlled from the Eve app

### ISSUE THREAD

**Issue by jbergbrede** [ebaauw/homebridge-hue#492]
#### Issue

Hi, first of all thank you very much for this great plugin!
I can't believe this hasn't been brought up before but I couldn't find any corresponding issue. 

Is it possible to add a temperature offset parameter to `ZLLTemperature` sensors to be controlled from the Eve app? It is not uncommon that there are inaccuracies in the temperature measurements of the Hue Motion Sensor and it would be cool to be able to adjust that. Now I'm not sure if this is technically possible but it would be amazing if you considered looking into it.

Again, thanks a lot and keep up the good work!

Edit: ...or in the config, doesn't have to be in the app.

**Comment by ebaauw** [comment]
This is not possible at the moment, because there's nowhere to store the offset between homebridge restarts.  Neither the Hue motion sensor nor the Hue bridge supports this.

deCONZ does support `config.offset` for temperature sensors (stored at the gateway).  I find the the Hue motion sensor temperature offset is not constant, however.  When I configure the offset so it reports the correct temperature at 15°C, it still reports the wrong temperature at 25°C.

**Comment by jbergbrede** [comment]
I see. Thank you for clarifying!
