### ISSUE TITLE
Klik aan Klik uit with HomeKit 

### ISSUE THREAD

**Issue by Danofski** [ebaauw/homebridge-hue#503]
I have my house fully equipped with Klik aan Klik uit (former Trust) transmitters, receivers, sensors, etc and an ICS-2000. 

The 1 thing I would like to do is integrate it with Apples HomeKit. I saw some post on the internet that Homebridge is 1 option, but only with the ICS-1000 series. 

Someone on Reddit reffered this GitHub, so I will try it here. 

Does anybody know how to do this with the 2000 serie? Do I need something else to do?

**Comment by ebaauw** [comment]
I understand that the newer Klik aan Klik uit devices talk Zigbee.  These might be connected to deCONZ (instead of to the ICS-2000), and from there be exposed to HomeKit by homebridge-hue.  The older devices use a proprietary 433/868 MHz protocol, nothing deCONZ can do there.

I'm unfamiliar with the ICS-2000 gateway.  If, like deCONZ, it provides a local REST API that's more or less the same as the Hue API, homebridge-hue might support it.  If they use a cloud based API or an entirely different local API, you would need another homebridge plugin.
