### ISSUE TITLE
homekit: No Response

### ISSUE THREAD

**Issue by mentaluproar** [ebaauw/homebridge-hue#507]
#### Issue

homebridge-hue returns "No Response" in the home app.

#### Log Messages

```
```
nothing in the log indicates a problem.

#### Debug Files

[homebridgeredacted.log.gz](https://github.com/ebaauw/homebridge-hue/files/3458885/homebridgeredacted.log.gz)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/3458886/homebridge-hue.json.gz)

**Comment by mentaluproar** [comment]
new symptom: tapping on a light that says no response shows its off.  keep tapping and it reacts normally.  It seems its just not understanding the first response its given and has to manually ask again.

**Comment by ebaauw** [comment]
> homebridge-hue returns "No Response" in the home app.

Technically, that’s not possible.  HomeKit sets “no response” when it cannot communicate with the accessory, or in this case homebridge.  Most likely, due to issues in your network.

Does this go away when you force-quit Home, and briefly disable the WiFi on your iPhone?  Does this show on all your iPhones and iPads, or only on one at a time?

Most common cause is that HomeKit no longer sees the accessory’s Bonjour announcement, after your iPhone has connected to another WiFi access point.  Disable IGMP snooping on your routers, switches, and access points.  If you have a Fritz!box, make sure the server running homebridge and your iPhone are on the same network port on the Fritz!box.

**Comment by mentaluproar** [comment]
IGMP snooping is already disabled.  Force quitting doesn't make a difference.  Neither does rebooting, or switching to the 5 ghz network.  It happens on my iPhone X running the latest public beta, but nothing else has that problem.  My Mac running Catalina beta 19A526h has the same issue.  A roommate with an iPhone XS running 12.3.1 sits on "updating" and eventually times out to "no response." Another roommate with an iPhone 7 on the public beta has the same problems.

I can send commands to the Cree bulbs and they respond properly, but if I am just checking in on them, they return "no response."  That doesn't change unless I issue a command to them first.

**Comment by ebaauw** [comment]
HomeKit only clears the no response state, when it issues a (read or write) request and receives a response this time.  The state cannot be pushed from the accessory.  To force a request, switch rooms or switch between the Home and Rooms view.  Or force-quit the app.

Are the Cree bulbs native HomeKit devices, or are you using homebridge with another plugin to expose them?

**Comment by mentaluproar** [comment]
No, they are zigbee bulbs connected through the hue bridge.  I'm using this plugin to give them HomeKit support.  It mostly works. I just have to manually interact with them to make that no response message go away.
