### ISSUE TITLE
v0.11.36 update failed

### ISSUE THREAD

**Issue by Hochiss** [ebaauw/homebridge-hue#519]
Error:

> USER: abc
DIR: /homebridge
CMD: npm --no-update-notifier install --unsafe-perm --save homebridge-hue@latest
Unhandled rejection Error: EACCES: permission denied, open '/root/.npm/_cacache/tmp/47145002'
npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
Command failed. Please review log for details.

checking log via ui-x, err:

> Cannot show logs. "log" option is not configured correctly in your Homebridge config.json file.
See https://github.com/oznu/homebridge-config-ui-x#log-viewer-configuration for instructions.

But the old version .35 was fine w/o this log definition in config.json. 

Don't know where should I begin to debug, pls. advise.

**Comment by ebaauw** [comment]
> Unhandled rejection Error: EACCES: permission denied, open '/root/.npm/_cacache/tmp/47145002'

This is an issue with `npm`, not with homebridge-hue.  Not sure what's causing it, but mixing `npm -g ...` and `sudo npm -g ...` seems like a bad idea.  I find clearing the cache (removing `.npm`) solves it.

> checking log via ui-x, err:

That's an issue with homebridge-config-ui-x, not with homebridge-hue.

**Comment by Hochiss** [comment]
Thanks for the explanation! 
without any debugging, I just notice the update went through successfully and log came back.

---- 
So I should remove /root/.npm in docker/HB,  which I notice somewhere it has a .lock file? It was due to node.js server was down temporarily?   

if I am not mistaken, _sudo npm -g_ will install globally e.g. into /usr/local/lib, and _npm -g_ will install locally in e.g. /homebridge ? It seems all plugins were/are instructed to install using _sudo_, but where comes the USER:**abc** (as in the error above) and I found in /homebridge, the directory itself and files inside changed owner to **abc**, "_homebridge-hue.json.gz_" can be found in the directory too. It is a update from hue-v.36 or from ui-x @oznu,  I am confused. 

What would be in the future the correct/secured way to update plugin to avoid this, esp. to identify or trace down where comes the faults, e.g. from npm server/docker/plugin manager(e.g. ui-x)/config.json? 

Sorry if this is off-topic or maybe I am asking too much :-)

Thanks in advance!

**Comment by ebaauw** [comment]
> maybe I am asking too much

That's not for me to judge, but you are asking the wrong person.  I run homebridge on a Raspberry Pi, installing it per the [official instructions](https://github.com/nfarina/homebridge#installation).  I develop and test my plugins using the same setup.  Rather than inventing brilliant new ways to install homebridge, I spend my scarce time on supporting more devices through my plugins.

> node.js server was down temporarily

NodeJS is not a server; it's a runtime engine for JavaScript, much like python, ruby, perl, etc.  `npm` and `homebridge` are "just" Javascript programmes running on NodeJS.  Of course, you can create a server in your JavaScript programme (that is exactly what homebridge does), but `npm` runs as a standalone programme.  It does connect to the npm registry (over the Internet).

> `sudo npm -g` will install globally e.g. into `/usr/local/lib`, and `npm -g` will install locally in e.g. /homebridge

Yes.  The global directory depends on how you installed NodeJS (and on what platform); the local install is in the local directory, if I'm not mistaken.  For global install you typcally need `sudo`, as a regular user doesn't have permissions to create files in global directories.

Where (and under what user) you _install_ homebridge is different from under what user you _run_ homebridge.  The files that homebridge creates run-time (by default in `~/.homebridge`) are owned by the user running homebridge.  Of course, when you use homebridge-config-ui-x, the user running homebridge is doing the installation as well (possibly through `sudo`, depending on how you configured homebridge-config-ui-x).
