### ISSUE TITLE
Removed bulb not showing a non-responsive

### ISSUE THREAD

**Issue by Tom41234** [ebaauw/homebridge-hue#554]
#### Issue

Hello Erik!

First I'd like to thank you for creating this amazing plugin! I'm very happy to be able to buy bulbs from different brands and all get them in my HomeKit through the Hue bridge. I've tried to find an answer to my question by reading through the issues, but I found nothing. So here goes.

One thing I've noticed and haven't been able to find an answer to is this: Whenever I remove a bulb from a lamp/socket it still shows in my HomeKit. Homebridge-hue does register the missing the bulb, as seen in the log below. It doesn't change the status in HomeKit tho, where I'm still able to turn the bulb on and off instead of it showing as non-responsive. 

Is this normal or there a way for me to fix this? Thanks for reading and again, thanks for creating this amazing plugin!

#### Log Messages

```
[11/1/2019, 10:11:35 AM] [Hue] Innr lamp 2: homekit on changed from 0 to 1
[11/1/2019, 10:11:35 AM] [Hue] Innr lamp 2: homekit on changed from 1 to 0
[11/1/2019, 10:11:35 AM] [Hue] Innr lamp 2: set homekit status fault from 0 to 1
[11/1/2019, 10:11:35 AM] [Hue] Innr lamp 2: homekit on changed from 0 to 1
[11/1/2019, 10:11:35 AM] [Hue] Innr lamp 2: homekit on changed from 1 to 0
[11/1/2019, 10:11:35 AM] [Hue] Innr lamp 2: homekit on changed from 0 to 1
```

#### Debug Files

No need, afaik.

No need, afaik.

**Comment by ebaauw** [comment]
The issue is that the Hue bridge doesn't know whether the light has been permanently removed, temporarily powered off, or simply temporarily unreachable because of hiccups in the ZigBee network.  The Hue API eventually reports the light as unreachable, when it doesn't respond to polling requests for its state.  This causes homebridge-hue to set _Status Fault_ (as you can see in your log), but Apple's Home app ignores this (standard!) characteristic.  Other HomeKit apps, like Eve do show it.

I use _Status Fault_, because, unfortunately, you cannot push the fact that an accessory has become/no longer is unreachable to HomeKit: the Home app only sets this state when it actively queries the device.

By setting `"wallswitch": true` in config.json, homebridge-hue will force the light off when the bridge reports it as unreachable, under the (often wrong!) assumption that the light has been powered off by the 20th century wall switch.  If you permanently remove a bulb, you better remove it from the Hue bridge (e.g. using the Hue app) and restart homebridge (so homebridge-hue removes it from HomeKit as well).

**Comment by Tom41234** [comment]
So as I understand it's impossible to get the unresponsive state from a bulb when someone accidentally turned off the wall switch? Good to know. Thank you for the response.
