### ISSUE TITLE
Gledopto RGB+CT gu10 bulbs issues 

### ISSUE THREAD

**Issue by abkarcher** [ebaauw/homebridge-hue#582]
Greetings! Thank you for the work you do on homebridge-hue!

I have Gledopto GU10 (Model: GL-S-007Z) bulbs tied into a gen2 hue hub. I was following the thread in [issue 557](https://github.com/ebaauw/homebridge-hue/issues/571) but the outcome is not clear to me.

For one, I experience the issue described (and screen-recorded) where choosing a color in the home app then choosing another color replaces the other color with the originally selected color. From my understanding, this is a not-fixable bug in the home app with bulbs that can address both CT and RGB, can someone confirm?

Otherwise, things things work - I can select the temperature or color tabs through the Home app and it successfully turns on/off the white flood lights/RGB lights within the bulb accordingly. RGB colors also work with Siri. The issue arises when trying to set white colors ("white", "warm white") with Siri. It simply sets the (much more dim) RGB channels to max instead of controlling the flood lights at all. 

From my understanding, Siri uses HTML color values to set the colors and doesn't actually have any temperature logic involved - is this likely the culprit? (Do the official hue bulbs have a special way they handle this differently?)
Would there be any existing workaround for this, apart from me trying to write logic that converts specific hue/saturation values to white temperature values?

Thanks for your time!

**Comment by ebaauw** [comment]
> For one, I experience the issue described (and screen-recorded) where choosing a color in the home app then choosing another color replaces the other color with the originally selected color. From my understanding, this is a not-fixable bug in the home app with bulbs that can address both CT and RGB, can someone confirm?

You mean that you try and select one of the six preset colour, but instead of setting the light colour, the preset is changed?  I don’t think that’s related to exposing both _Color Temperature_ and _Hue_/_Saturation_.  I’ve seen this behaviour also with `forceCt` set to false.

> From my understanding, Siri uses HTML color values to set the colors and doesn't actually have any temperature logic involved - is this likely the culprit?

For lights that only expose _Hue_/_Saturation_, the Home app translates colour temperature values to _Hue_/_Saturation_ values.  When _Color Temperature_ is (also) exposed, Home sends the colour temperature value.  That part works fine.  The problem is when homebridge-hue updates the _Color Temperature_ (reported by the light) after you set _Hue_/_Saturation_ from Home.  This is when the colours start “jumping”.  I haven’t tested Siri in this detail.

> Would there be any existing workaround for this

Create a HomeKit scene to set the _Color Temperature_ and recall that scene from Siri.  You might need to create the scene in Eve.

> Do the official hue bulbs have a special way they handle this differently?

There’s three different types of Hue bulbs:
- Gamut A with three channels that don’t support `ct`, only `xy`;
- Gamut B with three channels that support both `xy` and `ct`.  They use different RGB LEDs optimised for mixing colour temperatures, at the expense of fewer supported colours (especially green and orange);
- Gamut C with five channels, where `ct` drives the CW/WW channels and `xy` the RGB channels, similar to the GLEDOPTO RGB+CCT lights.

Only exposing _Hue_ and _Saturation_ makes sense for gamut B (and, of course, gamut A), since setting `ct` or the corresponding `xy` value leads to the same light state (driving the RGB LEDs to mix a colour temperature).  Imho it doesn’t make sense for gamut C, as you cannot drive the white channels from HomeKit.

Also, imho, faking colour temperature for gamut A lights makes no sense, as these lights cannot produce decent colour temperatures.

**Comment by abkarcher** [comment]
Hello,
Thank you for your response! that is useful information and interesting to know.
Mostly, I am not using the home app for any of this - I am trying to only control this all with Siri. The problems I am running into are:

1.) Setting a "warm white" color with Siri only adjusts the RGB in the bulb to simulate (poorly) a warm white color, which is also much more dim than using the white LEDs in the bulb.

2.) Setting a scene in home app and trying to invoke that with siri or the app results in the flood lights turning on for an instant, then transitioning back to a white color made by the RGB LEDs (and staying that way when trying to invoke scene again) - I think this is related to the home app not saving colors properly but swapping things around. 

I have tried toying with eve but it also has issues addressing the CT aspect of the lights. (Doesn't seem to acknowledge most of the CT spectrum of the lights? Unsure).

My solution, as most of these bugs seem to be unrelated to homebridge-hue (And I mostly just post this for anyone else mostly interested in siri control for bulbs that work with hue but dont appear in homekit) is to make scenes in the hue app and create shortcuts in iOS to address those scenes. Much less modular and requires specific wording, but for my use case, it works. I think in the future I will just invest in the revised hue gu10 bulbs that just came out!

Thanks for your time! (I will leave this open for you to close in case you have any other thoughts to add).
