### ISSUE TITLE
Specify brightness range?

### ISSUE THREAD

**Issue by iCarl** [ebaauw/homebridge-hue#604]
#### Issue

Im using a not yet released Zigbee to 0-10v/pwm controller that connects to a Jolly Maxi US LED driver.
The controller is connected to a 2nd gen Philips Hue Bridge.
The dimming works well, but the lights turns of when I set a brightness below 8%.
Is there a way to specify a brightness range? 

#### Log Messages

```
```

**Comment by ebaauw** [comment]
No.

Typically this is handled by the ZigBee device, where you can set what the minimum (output) brightness should be.  E.g. for the iCasa dimmers, this is set through a hardware button on the device, so that works with the Hue bridge.  For the ubisys D1, it's set over ZigBee, using the _MinLevel_ attribute of the _Ballast Configuration_ cluster.  The Hue bridge API doesn't support this.

I don't think I can implement a brightness range in homebridge-hue.  The setting depends on the load connected to the dimmer, so whitelisting the device type isn't enough.  I don't want config.json settings per resource: this is too error prone and leads to too many support issues.  I see no way to specify this on the bridge using `/resourcelinks` resources.

I think the best way to force the minimum brightness is to create a rule, that sets the brightness to 8% when it falls below 8%:
```
{
  "actions": [
    {
      "address": "/lights/1/state",
      "body": {
        "bri": 20
      },
      "method": "PUT"
    }
  ],
  "conditions": [
    {
      "address": "/lights/1/state/bri",
      "operator": "lt",
      "value": "20"
    }
  ],
  "created": "2020-01-24T13:08:07",
  "etag": "0d084f24297ecdf8df9db9fb62afd390",
  "lasttriggered": "2020-01-24T13:08:42",
  "name": "Test",
  "owner": "624ECA116F",
  "periodic": 0,
  "status": "enabled",
  "timestriggered": 1
}
```
This works on deCONZ, but I'm not sure if the Hue bridge allows rule conditions on `state.bri`, so you might need to use a home automation system on top of the Hue bridge to implement this.

**Comment by iCarl** [comment]
Ok, thanks!

**Comment by jakemauer** [comment]
@iCarl I’m interested to learn more about your zigbee controller and solution. I’m trying to connect standard constant current devices to homebridge. I realize this is not the ideal way to contact you but I’m not sure of a better way.

**Comment by iCarl** [comment]
Here are some documents regarding this: https://mega.nz/#F!mFsS2YpS!tTWtXAi8NlqWlu7XjH02Dw
