### ISSUE TITLE
Show scenes in home app

### ISSUE THREAD

**Issue by Mallepi** [ebaauw/homebridge-hue#609]
Good evening I've seen that you can now fade scenes into home kit. I would like to use the scenes to link them to my light switch in homekit.

Unfortunately the scenes are only shown in the Eve app. I would like to use the eve app as well, unfortunately apple has a scene limit for third party apps of 100 scenes. If you create the scenes via the home app, the limit does not apply. With 15 switches with 4 buttons each, the limit would be reached very quickly only fpr my switches without me having created other automations.

Therfore I asked if there is any way to show the scenes in the home app. Maybe as an extra device with many scene switches?

**Comment by Mallepi** [comment]
> I wasn't aware of the scene limit, but Apple customary uses a double standard for Home vs other HomeKit apps (e.g. television support). Cannot you create the scene in Home and then edit it in Eve? Or does the other HomeKit app only get to see the first 100 scenes?

There are the automation scenes that are created in a third party app. These can be edited in all Homekit apps. Here the limit of 100 applies.


Look here, there the problem is also described. But the workaround only works if the device is shown in the home app.

https://www.google.de/amp/s/amp.reddit.com/r/HomeKit/comments/8l29km/homekit_100_scene_limit/

Then there are the automations scenes that are created via the home app. These scenes are created by apple so that they can be displayed in many homekit apps but can only be edited in the home app. There is no limit here.

>  I could add a config.json parameter to expose these as Switch with the On characteristic instead.

That would be cool if you optionally put it in the config.

Alternatively, you could still display the scenes as a custom characteristic on the group and add a switch as an additional device.

This switch then gets all scenes from the groups as On characteristic and can be moved to a dummy room. This switch can then be used for automations. The advantage would be that you don't have the problem with siri.

I'm not sure what the better option is.
What do you think?

> Note that using Hue bridge rules instead of HomeKit automations to activate Hue bridge scenes from Hue dimmer switches offers better response times and is far more reliable. I only use HomeKit automations to control my non-ZigBee devices.

I use different switches. Some of them are only HomeKit capable so I have to program them in homekit.

**Comment by ebaauw** [comment]
You can move the group accessory to the dummy room, just as easily.  No need to expose an additional accessory for the scenes.  The is a HomeKit limit of 149 accessories per bridge (i.c. homebridge instance), so “less is more” really applies here.

**Comment by Mallepi** [comment]
Yeah, you're right. That's why I wanted your opinion on it. Because I wasn't sure.

Are you gonna put it in as on characteristic?

If so I would be very happy 👍

**Comment by Nastras** [comment]
Hi everyone, I've been thinking about this for a while now, that it's a bit silly that you can't use the Apple Home App to integrate the scenes into automations.

So I think it's a good idea that you can optionally show the scenes as On characteristic by the group.

I might have another idea but I am not sure if it is technically possible and if it is a good idea 🤓

What would be if it were possible to show the scenes as On characteristic additionally directly at the switch? 

![E617B6A1-BA42-496A-B803-DC9EC1E4D8EC](https://user-images.githubusercontent.com/27686185/73370760-00505580-42b5-11ea-995b-78ac36ad7364.jpeg)



One would have the advantage that one could finally operate his switch buttons directly on the device via Homekit App and one would not need any additional resources.

Of course this is only possible with switches that are integrated via homebridge-hue.

What do you think?

**Comment by ebaauw** [comment]
HomeKit automations (incl. actions linked to _Stateless Programmable Switch_ buttons) can only be accessed by HomeKit apps, through the HomeKit API.  The HAP protocol doesn't expose them, so they're invisible to HomeKit accessories (incl. homebridge).

I could theoretically expose the scenes as buttons, but that wouldn't do you any good, as there's no way to press the button from Siri or HomeKit.  The buttons need to be linked to a physical device on which you press the button.

**Comment by Nastras** [comment]
All right, so the idea fails because of home-kit restrictions.

Then I also vote for the idea to show the scenes at the group as on characteristic optional 😉

**Comment by ebaauw** [comment]
In v0.11.52-0, you can set `scenesAsSwitch` in config.json.  Please let me know if this works for you folks.

Install by `sudo npm -g homebridge-hue@beta`

**Comment by Nastras** [comment]
I just tried it out. Unfortunately, nothing is shown to me in the home app and nothing in the eve app.

I installed the beta and entered this in the config:
"scenesAsSwitch": true,

I created the scene over hueessential.

**Comment by Nastras** [comment]
"users": {
"": ""
},
"excludeSensorTypes": ["CLIPGenericStatus","CLIPGenericFlag","ZHATemperature","Daylight","Geofence","ZLLTemperature"],
"nativeHomeKitLights": false,
"nativeHomeKitSensors": false,
"sensors": true,
"lights": true,
"schedules": false,
"scenes": false,
"scenesAsSwitch": true,
"groups": true,
"group0": false,
"rooms": false,
"wallSwitch": false,
"hueDimmerRepeat": false,
"hueMotionTemperatureHistory": false,
"forceCt": true,
"forceEveWeather": false,
"resource": false,
"nupnp": true,
"linkbutton": true,
"lowBattery": 10,
"heartrate": 2,
"parallelRequests": 20,
"timeout": 5,
"waitTimeResend": 300,
"waitTimeUpdate": 100
}
]
}

**Comment by Nastras** [comment]
Sorry Erik, it all works 👍👍👍. Wrong message from me, I had deactivated scenes at the config from the bridge I had taken to try out.

![0E49BE32-9BBD-4AAD-A70B-0FB9FF6F440F](https://user-images.githubusercontent.com/27686185/73390646-d4de6280-42d6-11ea-8ddd-978911a4cefe.jpeg)

**Comment by Mallepi** [comment]
Hello wanted to let you know that it works for me too.


Thanks for the fast support 💪

**Comment by Nastras** [comment]
Good morning @ebaauw

i would like to know if i stop the homebridge and delete the scene and create a new one with the same name if homekit notices this? So is the scene connected by name or by id?

Would be good to know for a later adaptation of the scenes.

**Comment by ebaauw** [comment]
The scenes are identified by resource id.  At startup, homebridge-hue scans all scenes, and links them to the appropriate group.  When exposing the group, a service is created for each linked scene, in the order of linking.  HomeKit will continue to see the same service, but behind the scenes (pun intended) it’s linked to a different scene.  HomeKit will probably show the previous name (since this cannot be updated over HAP), but (in Eve) will show the new scene resource.

After changing the scenes, best unset `scenes`, restart homebridge, set `scenes` and restart homebridge.  You will have to redo your button actions after that.

**Comment by Nastras** [comment]
Thanks for the explanation.

One more thing, would it be possible that when you start homebridge-hue in the journalctl you can see which groups are loaded with which scenes? 

Would not be bad for debugging if something does not appear in homekit.

**Comment by Nastras** [comment]
One more info for you, I have now played a little bit with Siri to test how the light is switched on and off via the scene function.

If you don't give the scenes the property of a light, they won't be switched on when you call them via siri: switch the light in room X on.

Only when I name the switch does siri switch the scene on. 

In summary it works great and is a really great function that enriches the light control via homekit. 

Thanks Erik!

**Comment by Nastras** [comment]
I noticed something else while programming my hue tap light switch with groups and scenes function.

I have assigned a button with the group off function to switch off the light. So no extra scene for off.

Unfortunately the problem is that when I use the hue tap to call up a scene in the group where not all lights are turned on, only the any on switch is turned on and the group power switch remains on off.

If I now have 3 lights on in the room and press the button off on the hue tap nothing happens because the group button is off.

Would it be possible that you can also set the any on switch as on characteristic with a config option that you can also set it in the home app?

Alternatively you would have to create an off scene in the hue app so that it is displayed as an additional switch.

Then you would have 3 possible off buttons in a group 😔

**Comment by ebaauw** [comment]
> would it be possible that when you start homebridge-hue in the journalctl you can see which groups are loaded with which scenes?

Run `homebridge -D`.

> Only when I name the switch does siri switch the scene on.

And, in my experience, when you name the room itself.

**Comment by ebaauw** [comment]
> Would it be possible that you can also set the any on switch as on characteristic with a config option that you can also set it in the home app?

You can only have one _On_ characteristic per service, so I would have to create a new service for that.

> Or maybe you have another idea how to solve it?

Add the _AnyOn_ characteristic to a HomeKit scene in Eve, and recall the scene from Home or Siri.

**Comment by Nastras** [comment]
Then I prefer to create another power off scene in the hue app and insert it as a button on the hue tap. Of course it's a pity that you can't use the group off switch in the home app because it's always off if not all lamps in the group are on.

Another possibility would be that the group power switch remains on until the last lamp of the group is switched off. Then maybe you probably don't need a any on switch 🤔

But I don't want to get too intrusive and annoy you with any enhancements.
I'm still happy about the group scenes function, which is really great 😉


> Run homebridge -D. 

😒


> And, in my experience, when you name the room itself.

What exactly do you say turn on room x?

I say switch on light room x and he does not switch on the group switch.
But I also have the single lamp currently in my home kit.

**Comment by ebaauw** [comment]
> Another possibility would be that the group power switch remains on until the last lamp of the group is switched off. Then maybe you probably don't need a any on switch 

The problem is, I need to cater for three different situations:
- All lights are off (both `all_on` and `any_on` are `false`).  In this state, you want to be able to turn on (all) the lights;
- All lights are on (both `all_on` and `any_on` are `true`).  In this state, you want to be able to turn off (all) the lights;
- Some lights are on, others are off (`all_on` is `false`, but `any_on` is `true`).  In this state you want to be able to turn off the lights that are on, and you want to be able to turn on the remaining lights.

For the first two cases you can use either _On_ or _AnyOn_.  In the third case, _AnyOn_ turns the lights off, and _On_ turns the remaining lights on.  I suppose I could have used `On` for `any_on` and introduced _AllOn_ for `all_on`, but since turning a group on, sets `all_on`, using a separate _AnyOn_ makes more sense to me.

> What exactly do you say turn on room x?

“Hey Siri, turn on the Living Room”.  It’s a long time any many versions ago that I last tried this, maybe Siri has become smarter in the mean time.

**Comment by Nastras** [comment]
> Some lights are on, others are off (all_on is false, but any_on is true). In this state you want to be able to turn off the lights that are on, and you want to be able to turn on the remaining lights.

This function is also not possible in the Home App if I have defined lights as group. If I want to switch on or off single lamps in the group I have to do this manually in the group, lamp by lamp. Or just switch off the group and switch it on again and all lamps will be set back to the status on.

I think the scenario of switching on a single lamp in the group after the event is rare.

> “Hey Siri, turn on the Living Room”. It’s a long time any many versions ago that I last tried this, maybe Siri has become smarter in the mean time.

Ok i never switch the whole room on or off because i have my homehub = homepods and apple tvs also on sockets for a fast reboot. These would then also go off.

Besides siri would probably also turn off the heating 😅

Try switching only the light and it works fine 😉

**Comment by Nastras** [comment]
What I also remembered is that you can almost never tell at a glance if the lamps in the room are switched on because the group is almost always shown as off if not all lamps in the room are switched on. Only when you open the device you can see if the lights in the room are on.

This is the case in the home app and also in the eve app.

**Comment by ebaauw** [comment]
@Nastras could you try the latest beta?  Set `"anyOn": false` in config.json not to expose _AnyOn_ for groups.  In this case, _On_ is mapped to `state.any_on` (instead of to `state.all_on` in the default case).

**Comment by Nastras** [comment]
I just tried it out. It all works, now controlling the group is really fun.
It's cool that you put the feature in. Thanks a lot!!!

**Comment by Nastras** [comment]
Good morning, I noticed something else in the group's percentages. Not sure if it's a bug, though.

I've been playing around with some lamp settings. Actually the group should be calculating the average. With a setting where three lamps are set to 50%, a group value of 7% is displayed. There are 6 lamps in the group

Here a few screens:
![24AF2B77-1CCC-4EEC-AA73-8D4DA1C4D11A](https://user-images.githubusercontent.com/27686185/73586558-3c4f0a80-44af-11ea-88b1-b5fb2fe510ff.jpeg)
![5BF68762-50E8-481D-AEDC-CCCB08DD3C28](https://user-images.githubusercontent.com/27686185/73586559-3c4f0a80-44af-11ea-85a3-90b16ba99726.jpeg)

**Comment by Nastras** [comment]
If all lamps have the same brightness the value is right.

![6F2E6F51-D3F3-4380-AFA2-D3A1E940CAE1](https://user-images.githubusercontent.com/27686185/73586586-ae275400-44af-11ea-9e22-e0ad7b04b99c.jpeg)
![B6995139-EF32-4ECE-8AAD-8D85F04A735A](https://user-images.githubusercontent.com/27686185/73586587-aebfea80-44af-11ea-80d5-a014e4d4defe.jpeg)

**Comment by ebaauw** [comment]
> Actually the group should be calculating the average.

Tell that to the Hue bridge and/or deCONZ gateway.  The only state the APIs keep for a group is `all_on` and `any_on`.  The `action` attributes are documented as write-only, i.e. they reflect the last command sent to the group or (for the Hue bridge) a light in the group.

**Comment by Nastras** [comment]
Wasn't sure if it was related to the plugin or not.

> Tell that to the Hue bridge and/or deCONZ gateway. 

Will do on occasion 😂👍

**Comment by ebaauw** [comment]
Published v0.11.52.

**Comment by Nastras** [comment]
Good morning @ebaauw 

after i had a few days to test the new scene functions i noticed something else which is not so nice and you already suspected that it could come to problems.

You have made it possible to display the scenes as On characteristic on my request to use them in the home app. Which also works great.

Unfortunately I noticed that when controlling with siri with the command switch off light in room x all scenes are called up more often and the light does not switch off reliably. All scenes light up briefly one after the other. This does not always happen, but often depending on the mood of siri 🤪

It looks like that Siri even if the scene switches are already set to off, they are still switched on for a short time and then switched off.

![226A4582-8BA9-40E3-A2C7-B896D60C3924](https://user-images.githubusercontent.com/27686185/75619022-7545d200-5b76-11ea-830b-1c4902d249b1.jpeg)



Do you see a possibility to stop this? For example by checking that the switches are only activated when they are on? 

Greeting
Nastra

**Comment by ebaauw** [comment]
homebridge-hue doesn’t check the value to which the switch has been set.  I figured it could only be set to true from HomeKit, as the switch resets itself after recalling the scene.  Apparently Siri thinks it necessary to switch off switches that are already off...  As I said before, it’s generally a bad idea to give her control over stuff she doesn’t understand, but I’ll add the check to recall the scene only when the switch has been set to true.

**Comment by Nastras** [comment]
> As I said before, it’s generally a bad idea to give her control over stuff she doesn’t understand
I know 🤪🤪🤪

It also took me a couple of days to understand that siri turns off in a scene even though they are not on.

> but I’ll add the check to recall the scene only when the switch has been set to true.

That would be so cool 👍

Thank you!

**Comment by ebaauw** [comment]
Could you try beta v0.11.57-1?  Install thru `sudo npm -g homebridge-hue@beta`.

**Comment by Nastras** [comment]
I have done so, so far the problem has not occurred after several attempts. Looks like it's fixed 👌

**Comment by ebaauw** [comment]
Published v0.11.57.
