### ISSUE TITLE
Provided user data but plugin keeps complaining

### ISSUE THREAD

**Issue by zeromancer1972** [ebaauw/homebridge-hue#616]
I had to setup the plugin again from scratch and now I added a new user to the config.
First, the UI for configuration (using homebridge-config-ui-x) does not expose the user area so using the UI always remove the users section.
Anyway, using the config file and adding the users section again, still produces this messages:

Philips hue: Philips BSB002 bridge v1935144040, api v1.35.0
[7.2.2020, 01:01:20] [Hue] Philips hue: bridge request 2: post / {"devicetype":"homebridge-hue#homebridge"}
[7.2.2020, 01:01:20] [Hue] Philips hue: bridge error 101: link button not pressed
[7.2.2020, 01:01:20] [Hue] Philips hue: press link button on the bridge to create a user

This goes on and on and is counting ("request gazillion...: post"). What is this?
Config looks like this:

```
{
            "platform": "Hue",
            "users": {
                "001788FFFE6E4BC7": "-i9xaNNPjTig-evW9GERHut5Q-yEeDV1zoFDC5Gy"
            },
            "sensors": true,
            "nativeHomeKitSensors": false,
            "excludeSensorTypes": [
                "Daylight",
                "CLIP",
                "Geofence"
            ],
            "lights": true
        }
```

It's not usable atm.

**Comment by ebaauw** [comment]
> First, the UI for configuration (using homebridge-config-ui-x) does not expose the user area so using the UI always remove the users section.

As I understand, that’s a limitation of the software that they use to generate the forms: it cannot handle dynamic keys (like the bridge ID).

> This goes on and on and is counting ("request gazillion...: post"). What is this?

homebridge-hue doesn’t have a username (API key) for the bridge and tries to create one.  This fails, because the link button hasn’t been pressed.

> Config looks like this:

That’s looking good to me.  Did you double-check the bridge ID?  Are you sure this is the config that homebridge uses?  Different ways of installing homebridge might place config.json differently.  If you run `homebridge -D` homebridge-hue logs a debug message with the config contents.

If you need me to have a detailed look, please capture and attach a debug log file, see https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by zeromancer1972** [comment]
Yeah it looks like nvm changed my homebridge default path so I adopted it. I just was wondering why my existing (more complex) config did not work - and the user key wasn't recognized after the update.
