### ISSUE TITLE
Support for On/Off plug-in unit

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-hue#63]
Currently, homebridge-hue exposes an _On/Off plug-in unit_ light (e.g. the OSRAM Lightify plug), as a `Switch` (see issue #28).  A Hue bridge group containing only _On/Off plug-in unit_ lights is also exposed as a `Switch`.

However, plugs, like Elgato's Eve Energy, are typically presented as `Outlet` rather than `Switch`.  On the other hand, for a group of plugs, `Switch` seems to make more sense than `Outlet`.

As far as I can see, `Switch` and `Outlet` are functionally the same: both have an `On` characteristic, you can specify whether it's used as Switch/Outlet, Light, or Fan.  `Outlet` does have an additional read-only `OutletInUse` characteristic.  I have no clue what it's for: it seems to be true all the time for the Eve Energy plugs.

Should homebridge-hue expose the plug as `Outlet` instead?  @sejoki, any-one: what's your view on this?  What are your experiences with other plugs?  Do you use the `OutletInUse` characteristic?

**Comment by sejoki** [comment]
Thanks for the update and for continuing to put so much thought into this plugin.

I don't have any experience with the Eve Energy. The additional monitoring of how much power it uses doesn't justify spending 20 more €.
My original issue was that it was exposed as a light, which isn't the case for me. I use it to control my media rack, switching off power for my TV, A/V receiver and a couple of other small electronics that I don't need to be running in standby over night.

Technically, it is an outlet rather than a switch, though I think most people buy the plug to have one specific device home kit enabled. I also have one for my espresso maker that turns on with my morning scene. In both cases, a specific device is either on or off.

The outlet characteristic would only make sense to me if I had plugs on all my outlets throughout my apartment and would name them accordingly, for example "kitchen countertop" "kitchen cupboard" and so on.

The way I use them, I control a device, not the outlet the device is plugged in to, so for me personally, the switch makes more sense.

My guess on the OutletInUse characteristic would be that it's tied to the Eve's energy monitor and if a device is plugged in (like my coffee maker) that has a separate on/off switch, it becomes false if it's turned off.

**Comment by ebaauw** [comment]
Thanks, @sejoki 

> My guess on the OutletInUse characteristic would be that it's tied to the Eve's energy monitor and if a device is plugged in (like my coffee maker) that has a separate on/off switch, it becomes false if it's turned off.

My guess as well, but `OutletInUse` remains true, regardless whether the device plugged into it actually consumes power.  Even when I have nothing plugged into the Eve Energy.

**Comment by pponce** [comment]
I use the homebridge-mpower plugin and have each outlet on the mpower power strip exposed as an outlet. The OutletInUse characteristic is based on the power draw. Mine can be in the on state and have outletInUse be "no".  It's sort of a nice to have data point.
I like that it's actually in real life a set of outlets and is referred to as outlets by HomeKit.  For an outlet that is single use I give it a specific name and never think twice about it being an outlet vs device.  For an outlet powering more than one device, it is nice to see if it's in use or not because in that case I leave the outlet always on and use the devices plugged into it the old school way (in my case a portable BT speaker that is always plugged in and a humidifier).

**Comment by pponce** [comment]
The mpower powerstrip exposes the amount of power draw per outlet. You can then decide what constitutes "inuse" or by checking for great than X current being consumed.

**Comment by ebaauw** [comment]
Thanks @pponce, @sejoki.  It would seem that the Eve Energy is the odd one out

 I'll keep using `Switch` for an _On/Off plug-in unit_, as there's no power monitoring or anything to derive a value for the `OutletInUse` characteristic, which is mandatory for `Outlet`.
