### ISSUE TITLE
Question pi zero w

### ISSUE THREAD

**Issue by Kristian8606** [ebaauw/homebridge-hue#648]
Hello!
Congratulations on your wonderful work.
I decided to remove all my hubs and replace them with deconz and homebridge-hue.
I have pi zero w and I plan to use it, will I have problems with it or will I have to replace it with a more powerful one?

**Comment by ebaauw** [comment]
I don't have any personal experience with the Pi zero.

I'm running deCONZ and two homebridge instances on a Pi 3B+ without any issues.  One instance runs homebridge-hue, the other homebridge-otgw, homebridge-p1, homebridge-ws, and homebridge-zp.

**Comment by Kristian8606** [comment]
I've been testing ConBee 2 with Homebridge-hue on pi zero w for two days and it works fine. I noticed that the processor runs between 55-75%. I had cases when I turned off the lights after about 10 minutes in the annex again showing that the lights were on, The same case I had with the ikea gateway, the bulbs are on ikea. Has anyone had such a case and what is the reason?

**Comment by ebaauw** [comment]
How did you turn off the lights?  What type of lights are you using?

**Comment by Kristian8606** [comment]
I turned off the lights with the Home application.
bulb is Tradfri bulb E27 opal 1000lm

**Comment by ebaauw** [comment]
That should work normally.

The issue could be:
1. (with the IP network) between HomeKit and the accessory (IKEA hub, Hue bridge, or homebridge - whomever is exposing the light to HomeKit); or
2. (with the IP network) between homebridge-hue and the Hue bridge/deCONZ gateway; or
3. (with the ZigBee network) between the light and and the hub/bridge/gateway.

You want to check a native hub/bridge/gateway app to see if the hub/birdge/gateway also reports the wrong light state.  If not, you want to check the `homebridge -D` log to see if homebridge-hue sends the wrong state to HomeKit.  If not, the issue is with your home network or HomeKit app losing the link to the HomeKit accessory.

**Comment by Kristian8606** [comment]
Thank you for the tips I will take the time to look at in detail.  by the way, I just found that when I turn off a light bulb through the wall switch in the home application and also in phoscon it remains inclusive.

**Comment by ebaauw** [comment]
You don't want to use 20th century wall switches with your smart lights.

**Comment by Kristian8606** [comment]
Yes, but other accessories I own update  my tile  in the home app when I unplug and turn them on.

**Comment by ebaauw** [comment]
This behaviour is caused by ZigBee: it doesn't detect that devices are powered down.  homebridge-hue can do nothing about this.

**Comment by Kristian8606** [comment]
I didn't know this, now everything became clear to me.  Once again, congratulations on the well-supported project

**Comment by Kristian8606** [comment]
In the previous version, when turning off the bulb with the wall switch in the app, the home did not respond, and after restoring the power the tile did not update and constantly showed that it did not respond.  Now with the new update, I notice that the bulb is updating.  My question is whether you correct this or the problem was in my configuration

**Comment by ebaauw** [comment]
I haven't changed anything in that area recently, see https://github.com/ebaauw/homebridge-hue/releases.
