### ISSUE TITLE
Xiaomi Aqara water sensor temperature

### ISSUE THREAD

**Issue by the-ress** [ebaauw/homebridge-hue#657]
#### Feature Request
Hi, can homebridge-hue expose temperature for Xiaomi water sensors? I can see it in Phoscon, but not in HomeKit.

Phoscon:
![9953EE3E-492D-4F30-BCE1-3C8478888C56](https://user-images.githubusercontent.com/1612377/76671954-ca7fdb80-6599-11ea-87fd-6a42ffa011f0.jpeg)

HomeKit services:
![D24BCAD4-1E82-4C0F-98EA-2E2AEE984494](https://user-images.githubusercontent.com/1612377/76671957-ce136280-6599-11ea-9d88-23f58963b660.jpeg)

**Comment by ebaauw** [comment]
Most Xioami devices have an internal temperature sensor that measures the device temperature.  The value reported by this sensor is very coarse, in °C instead of 0.01°C, and very imprecise, it doesn’t reflect the room (environment) temperature outside the device.

The REST API plugin exposes this value as `config.temperature`, to distinguish it from the value from “real” temperature sensors, which is exposed as `state.temperature`.

Homebridge-hue only supports `state.temperature` and ignores `config.temperature`.  Technically, it could support `config.temperature`, but functionally, it doesn’t seem to make much sense.  It would be tricky to provide history, as the device might already have a primary function for which homebridge-hue already exposes the history.

**Comment by the-ress** [comment]
Thanks for the explanation
