### ISSUE TITLE
Question about resource connection.

### ISSUE THREAD

**Issue by Kristian8606** [ebaauw/homebridge-hue#669]
When I remove a device from a deconz that had a resource link, the homebridge cannot start until I manually delete the resource link.
Is there a way to automatically delete the resource link it when I remove a acsesoar from  deconz device.

**Comment by ebaauw** [comment]
> When I remove a device from a deconz that had a resource link, the homebridge cannot start until I manually delete the resource link.

That's by design.  Homebridge Hue cannot see the difference between a not-yet-exposed and a deleted resource.

> Is there a way to automatically delete the resource link it when I remove a acsesoar from deconz device.

Note that the `/lights` and `/sensors` resources do **not** get deleted, when you remove a node from the GUI.  I think I've seen some code in the deCONZ REST API plugin to remove any references from groups, scenes, when a `/lights` resource is deleted, but I don't know about rules, schedules or resourcelinks.  Nor about deleting `/sensors` resources.

Cross referencing https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2377.
