### ISSUE TITLE
Home App reporting interim brightness value when switching lamp on / off

### ISSUE THREAD

**Issue by rutteger** [ebaauw/homebridge-hue#697]
Brief overview of issue, albeit a minor one. Not clear if this is related to homebridge-hue plugin or deCONZ (or Home app)

Setup. rpi4, homebridge 1.04,  homebridge-hue v0.11.64, raspbee, deCONZ 2.05.75.

In the process of moving various hue bulbs, osram bulbs and outlets and aqara devices onto deCONZ. Already using homebridge-hue with hue hub to reveal Osram outlets and bulbs.

All the hue bulbs which have been migrated thus far when switching on or off will intermittently report an interim brightness value in the Home app (not in Home+ or EVE).

For example bulb already set at 41%. Switch off, bulb reports 0%, fine. Switch back on, bulb physically goes to 41% but Home reports an interim value, maybe 0%, maybe 20% before updating to correct value several seconds later.

Extract from log below. Can supply full debug info if required..

May 11 22:56:07 superbridge homebridge[390]: [5/11/2020, 22:56:07] [Hue] Hallway Light: homekit on changed from 1 to 0
May 11 22:56:09 superbridge homebridge[390]: [5/11/2020, 22:56:09] [Hue] Hallway Light: homekit on changed from 0 to 1
May 11 22:56:10 superbridge homebridge[390]: [5/11/2020, 22:56:10] [Hue] Hallway Light: set homekit brightness from 41% to 24%
May 11 22:56:15 superbridge homebridge[390]: [5/11/2020, 22:56:15] [Hue] Hallway Light: set homekit brightness from 24% to 41%

**Comment by rutteger** [comment]
Attached debug log and config file 
[20200513.zip](https://github.com/ebaauw/homebridge-hue/files/4622930/20200513.zip)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4622931/homebridge-hue.json.gz)

Added a few more devices. Still noting the issue on all Hue bulbs. Unable to replicate on the single non hue bulb type device (zigbee dimmer).
Log above (hopefully) shows toggling lamp on and off with a brightness of 30. Final event shows an off event, home app reporting 10% initially then finally 30%.

**Comment by Kristian8606** [comment]
I have the same problem.

**Comment by ebaauw** [comment]
I'm sorry @rutteger, I don't get anything useful from the log.  There's only three messages from the Homebridge Hue plugin on startup.  Looks like you ran Homebridge with `DEBUG=*` instead of `homebridge -D`?  Did you capture both stderr and stdout?

> All the hue bulbs which have been migrated thus far when switching on or off will intermittently report an interim brightness value in the Home app (not in Home+ or EVE).

I don't think I've ever seen that.  If it's only in Home, I would suspect that app.  Do you see this on multiple devices?  Do you still see this after rebooting the iDevice?  And after rebooting the Home hub (Apple TV or HomePod)?

Are you sure it's for Hue lights exposed by Homebridge Hue, not by lights (still) exposed by the Hue bridge?  Did you delete the lights from the Hue bridge, before pairing them to deCONZ?

> For example bulb already set at 41%. Switch off, bulb reports 0%, fine.  Switch back on, bulb physically goes to 41% but Home reports an interim value, maybe 0%, maybe 20% before updating to correct value several seconds later.

How do you switch the light off or on?  Do you use a transition time?  Normally the light would continue to show the same brightness after turning it off.

In principle this behaviour is to be expected, but I don't understand how it happens in your situation.  I think Philips/Signify as well as Apple made a fundamental design error, which has been copied by deCONZ.  They don't distinguish between current and target state for lights.  While this makes sense for 20th century dumb lights, which turn on or off instantly, it's an oversight for smart lights, that transition over time to their target state.  When changing the light state through the API, the Hue bridge and deCONZ gateway update their cache of the light state with the target state.  Next time the light is polled, or when the light actively reports its state, the currently state in the transition is shown.  Only when the transition has completed, the target state (which is now the current state) is shown again.

Now this would only happen if the transition takes long enough for the light to be polled (or send reports) during the transition.  By default both Hue and deCONZ use a transition time of 0.4 seconds.  Hue lights don't support attribute reporting, so the state can only be updated by the Hue bridge or deCONZ gateway polling the light.  Very unlikely with the default transition time, especially when adding more lights (as the time between polls for the same light increases).  I would sooner expect this for lights that support attribute reporting.
