### ISSUE TITLE
[Investigation] feasibility on exposing resource group as switch service 

### ISSUE THREAD

**Issue by Soldiiier** [ebaauw/homebridge-hue#709]
Unsure if this is feasible. 
Wondering if resource groups can be exposed as “switches”. Similar to the currently  supported exposing resource groups as “outlets”.

**Comment by ebaauw** [comment]
Strictly speaking the `/resoucelinks` resource itself isn't exposed, but the `/lights` and `/groups` resources it links to, would be exposed as _Switch_ (instead of as _Lightbulb_).

Yeah, that's feasible.  You only want to link _On/Off_ lights or plugin units, as you'll lose _Brightness_, _Hue_/_Saturation_ and _Color Temperature_.

**Comment by ebaauw** [comment]
Above commits add support for `switch` resourcelink.  `ph switch` creates the resourcelink with all _On/Off_ `/lights` resources in it.  You might want to update the link manually (using the API).  It supports `/lights` as well as `/groups` resources.
