### ISSUE TITLE
Status Faults

### ISSUE THREAD

**Issue by Lorccan** [ebaauw/homebridge-hue#740]
Hello Erik

I have a question: I know that when homebridge-hue shows a status fault, this is to do with the most recent poll from the Hue bridge not succeeding and does not necessarily mean that an attempt to control the light will fail.

No matter what I do (moving bridges, changing channels, etc) I still see intermittent status faults across a whole range of devices and on several bridges. Most of the time my commands succeed but I also get failures on a significant minority of occasions where a scene fails to set correct brightness and/or hue (but the light comes on), or where it fails to switch on at all. Clearly, on those occasions the lights are actually unreachable by the Hue bridge and it's frustrating that this doesn't seem to be an issue the Hue's engineers are paying any attention to.

So, finally, I have some questions:

If you experience such failures, do you have a strategy for dealing with them? (One thing I tried for rooms where the scene I use is constant, is a rule that uses dx on a light that's set by the scene - one that never seems to have any issues being reached - so that the scene gets fired again a little while later, but this is inexact as there's no telling how transient the status fault is.)

Does a ConBee II to build the ZigBee network offer significant advantages over Hue? (I like Hue's API, but I find it frustrating that I need three or four bridges to run all my devices because of an arbitrary limit.)

**Comment by ebaauw** [comment]
> I know that when homebridge-hue shows a status fault, this is to do with the most recent poll from the Hue bridge not succeeding and does not necessarily mean that an attempt to control the light will fail.

_Status Fault_ actually mirrors `state.reachable` as exposed by the Hue API.  Unfortunately, that doesn't reflect whether the lights is actually reachable, only that the bridge didn't get a response the last (couple of) time(s) it tried to reach the light.  See also https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2590.

> where a scene fails to set correct brightness and/or hue (but the light comes on)

I think you're referring to HomeKit scenes?  Note that HomeKit sends a different event to Homebridge for each characteristic in the scene.  This comes dangerously close to a denial-of-service attack on Homebridge.  Homebridge Hue tries to combine the characteristics for a single light into one Hue bridge API call, but the bridge splits these in two or three Zigbee commands.  Without throttling the Hue API calls in Homebridge Hue, this would saturate the Zigbee network.

Conversely,  Hue bridge scenes are implemented in Zigbee.  Each light stores their target state for the scene locally, and only a single Zigbee broadcast command is needed to recall the scene.

> If you experience such failures, do you have a strategy for dealing with them?

Yes:
- Use `/groups` API calls instead of `/lights` API calls.  These result in Zigbee broadcast instead of unicast messages, and are immune to routing issues.
- Use Hue bridge scenes instead of Homebridge scenes.   Homebridge Hue can expose these to HomeKit (as switches), so you can recall them directly from HomeKit.
- Only use Hue lights; a lot of Zigbee routing issues are due to different manufacturers handling this differently causing issues in multi-vendor networks.

> Does a ConBee II to build the ZigBee network offer significant advantages over Hue? 

Yes, notably real-time notifications (through web sockets), support for up to 200 nodes, support for way more devices.  Unfortunately, it's also suffering from Zigbee routing issues.  Also, you cannot use Hue Entertainment.

**Comment by Lorccan** [comment]
Thank you for the quick and detailed response.

That gives me plenty to think about! I think I'll go back to the drawing board on scenes. My original intention was only to use HomeKit scenes out of necessity - where devices are exposed by different bridges - but I think I need to follow your suggestion to expose the Hue bridge scene as a switch in HomeKit. (I assume I can then safely use these switches in a single HomeKit scene, or would you just group them?)

I do have one more question please: if I expose a Hue bridge rule through homebridge-hue what use is this on the HomeKit side and how does it appear?

Thanks, as always, for your wonderful homebridge plugin

**Comment by ebaauw** [comment]
I exposed the rules so I could monitor them being triggered when debugging them.  Haven’t used it for ages, since I check the deCONZ log instead.  The Hue bridge doesn’t provide any logs.

**Comment by Lorccan** [comment]
Understood. Thanks again.
