### ISSUE TITLE
Second homebridge for guests

### ISSUE THREAD

**Issue by AlfaJackal** [ebaauw/homebridge-hue#752]
Before I destroy my setup I would like to ask a question here. Please excuse if it is just a basic question: Is it possible to have two independent connections via two homebridges that are configured differently?

What I want to achieve: A second homebridge (separate docker) that only exposes two lights for my guest site in Apple Home App.

My main site should be unaffected with all lights and sensors that are already exposed. Only two lights (Living Room and Guest Room) should be accessible for guests.

In order to expose only two lights, I have to use homebridge-hue with a whitelist. I understood that it is necessary to use `ressourcelinks` for that. 
Is it correct, that I need a second API user for that on my bridge? Is that possible without changing anything to my main/fist user/site?

How exactly do I push my whitelist for only this user via  `ressourcelinks` to hue bridge? With `ph post`?

**Comment by ebaauw** [comment]
Interesting use case.

> Please excuse if it is just a basic question: Is it possible to have two independent connections via two homebridges that are configured differently?

It's perfectly possible to have multiple Homebridge Hue instances connected to the same Hue bridge and/or deCONZ gateway.  I do this quite often for development and testing.  The two instances do have different `config.json` files, so they can be configured differently.
The same accessories can be exposed by both instances; HomeKit tells them apart because they're exposed through different HomeKit bridges (i.c. Homebridge instances).
However, this will confuse Eve; apparently it only looks at the UUID of the accessory, not at that of the HomeKit bridge).  I don't think this will be an issue for lights, but the history of the two accessories gets combined, leading to all sorts of weirdness.  It doesn't matter whether the Homebridge instances are paired to the same HomeKit home or to different HomeKit homes.  For full separation, you need to use different iCloud accounts (and therefore different iDevices).

> How exactly do I push my whitelist for only this user via `resourcelinks` to hue bridge? With `ph post`?

Currently, it's not possible to have a whitelist per instance, as the `resourcelinks` resources are seen by both Homebridge Hue instances.
I've considered taking into account the `owner` (creator) of the `resourcelink`, but then you would have to create it from Homebridge Hue, or at least use the same API key (username) as Homebridge Hue.  I figured that would cause more confusion than that it's worth, so I dropped that idea.
In your case, I think it wouldn't be a problem.  You'd set `lights` in `config.json` of (the Homebridge instance paired with) your own home, but not in that of your guest home.  As you expose all lights already, the whitelist doesn't change your own home, and effectively only impacts the guest home.
I would be an issue if you wanted to expose some lights only to the guest home.

> Is it correct, that I need a second API user for that on my bridge? Is that possible without changing anything to my main/fist user/site?

In theory, an API key (username) could be shared by multiple API clients.  I think this is a bad practice, even with the limited amount of logging/monitoring currently provided by the Hue bridge or deCONZ gateway.  I use separate API keys for each Homebridge Hue instance (and `ph` instance).  Homebridge Hue and `ph` create an API Key with a `name` of `homebridge-hue#`_host_ or `"ph-`_host_, so if you run the two Homebridge instances on the same host, it's a bit challenging to tell them apart.  I don't know whether they would take the _host_ from the container or from the host system.

**Comment by AlfaJackal** [comment]
That is fantastic! Thank you very much for this really detailed answer!

I managed to setup my homebridge with a second user. I exposed everything with `homebridge-hue` and then I send this via `.../debug/clip.html`:

URL:
`/api/XXX/resourcelinks`

Message Body:
```
{
  "name": "homebridge-hue",
  "classid": 1,
  "description": "whitelist",
  "links": [
    "/lights/7",
    "/lights/8",
    "/groups/3"
  ]
}
```

Command Response is:
```
[
	{
		"success": {
			"id": "36131"
		}
	}
]
```

After restarting homebridge I receive this error:
```
[Hue] homebridge: error: Cannot add a Service with the same UUID '00000043-0000-1000-8000-0026BB765291' and subtype '0b' as another Service in this Accessory.
```
What did I do wrong and how can I fix that?

**Comment by ebaauw** [comment]
Are you still using one Homebridge instance?  You didn’t use two `platform` entries for Homebridge Hue in one `config.json`, did you?

Please attach the debug dump file and capture and attach a debug log file (of the Homebridge instance showing the error).

**Comment by ebaauw** [comment]
Could you try v0.11.76-0?  Install through `sudo npm -g i homebridge-hue@beta`.

**Comment by AlfaJackal** [comment]
> Damn.  I can reproduce that; apparently Homebridge Hue tries to expose the `/lights` resource twice when whitelisting it.

It looks, like you already fixed the `.js`! Like always, very impressive work and incredible fast support. Wish I could do more like only "configuring" and "setting" things up. 😉 

`blacklist` works fine, so I am using this for now.

**Comment by AlfaJackal** [comment]
> Could you try v0.11.76-0?  Install through `sudo npm -g i homebridge-hue@beta`.

Installed the new beta, unfortunately with the same result. Here ist the dump: https://pastebin.com/TJbYXktW

**Comment by ebaauw** [comment]
You probably have multiple installations of homebridge-hue, in `/usr/local/lib` vs `/homebridge`.  Most likely, Homebridge is still loading the old version.  I don't know how you originally installed homebridge-hue, but you need to install the beta in the same way.

**Comment by AlfaJackal** [comment]
> You probably have multiple installations of homebridge-hue, in `/usr/local/lib` vs `/homebridge`.  Most likely, Homebridge is still loading the old version.  I don't know how you originally installed homebridge-hue, but you need to install the beta in the same way.

Thanks! Hmm, I installed it via GUI.

**Comment by ebaauw** [comment]
Does the beta solve your issue?

**Comment by AlfaJackal** [comment]
Yep, looks good.

**Comment by jeankone** [comment]
Hello @ebaauw,

any news on this? 

> Currently, it's not possible to have a whitelist per instance, as the `resourcelinks` resources are seen by both Homebridge Hue instances.
> I've considered taking into account the `owner` (creator) of the `resourcelink`, but then you would have to create it from Homebridge Hue, or at least use the same API key (username) as Homebridge Hue. I figured that would cause more confusion than that it's worth, so I dropped that idea.
> In your case, I think it wouldn't be a problem. You'd set `lights` in `config.json` of (the Homebridge instance paired with) your own home, but not in that of your guest home. As you expose all lights already, the whitelist doesn't change your own home, and effectively only impacts the guest home.

Would it be possible to alternate the use of `description`? 
leaving "whitelist" globally for all homebridge-hue instances and add new description like `whitelist $bridgeusername` specifically for one instance?
That would solve my issue having only one deconz for the whole house for getting a good mesh topology and at the same time seperating all the devices for different users. 
also this would keep the backwards compatibility.

Thx
Jan

**Comment by ebaauw** [comment]
No news.

I want to move to a dynamic platform accessory plugin first, so Homebridge Hue itself has persistent state across restarts.  Then, I can store the advanced configuration on what to expose in Homebridge Hue, rather than using `resourcelink` resources on the bridge/gateway.  Configuration would be maintained using dynamic forms on the Homebridge UI, rather than through the Hue/deCONZ API.  Long term plan, though, no ETA.
