### ISSUE TITLE
Cannot remove Phoscon-GW from favorite Screen in Homekit

### ISSUE THREAD

**Issue by clipse2004** [ebaauw/homebridge-hue#767]
#### Issue
Hello,
I have a problem, I moved from one Raspberry to another with a completely new Homebridge installation.
But now I have the problem that I cannot remove the Phoscon Gateway in HomeKit under Favorites.
Usually there is always the button "Show in favorites" which is completely missing here: /
Any idea? Do I now have to delete the gateway and then set up all the devices again?
And second question, I have two Osram outdoor plugs. These are shown to me as a light in the HomeKit, can you change that somehow?
Or does that have to be changed in the Deconz?

Many thanks :)

PS: i already asked in discord
![IMG_2020](https://user-images.githubusercontent.com/47680803/93624972-7ab71c80-f9e1-11ea-9124-aee930d5d56d.jpg)

**Comment by ebaauw** [comment]
As I already replied in Discord, the favourites are handled by Home.  There’s nothing in the HAP protocol for that, and nothing Homebridge nor any plugin can do about that.  They changed something in iOS 14 - I got a report of this already for one of the beta versions.  Best file a bug report with Apple.
I no longer see the favourite option in iOS14 either for any _Not Supported_ accessory.  However, I already unmarked these as favourites a long time ago (even before iOS13) and that setting is still honoured.  The option is still available on macOS, and, I assume, on iOS13.

To expose the plugs as _Outlet_ instead of _Lightbulb_, create an `outlet` resourcelink.  Search in the closed issues for details.

**Comment by ebaauw** [comment]
> They changed something in iOS 14

They no linger show the setting for _Not Supported_ accessories.  It's still there on iOS 13 and macOS.  If you change it there, it should be synced with iOS 14.

If you don't have any iOS 13 or macOS devices with Home, set `linkbutton` in config.json to expose a _Stateless Programmable Switch_ on the bridge/gateway accessory, so it's no longer _Not Supported_.  This will allow you to change the favourite status of the accessory.  It will stick, after you clear `linkbutton`.
Note that the switch only works for Hue bridges with an API version < v1.31.0 (i.e. the gen-1 Hue bridge).  For non-Hue-bridge gateways it doesn't do anything, and for gen-2 Hue bridges, only one button press per minute is registered.

**Comment by gizmotronic** [comment]
Thanks for the workaround, @ebaauw, works as advertised. :+1:

**Comment by RomanGz** [comment]
I found that if I set `linkButton` to `true`, the button replaces it, and then allows me to take it out of favorites.
