### ISSUE TITLE
 LED strip still shows active

### ISSUE THREAD

**Issue by iMonZ** [ebaauw/homebridge-hue#771]
Hey,

I have a problem: When the Strip light is not connected with the hue ( the hue app shows everything correct) then you still see inside of HomeKit that the light is connected and turned on!
Is it possible to fix this?

regards 
![IMG_0289](https://user-images.githubusercontent.com/11319871/94337287-ac377580-ffe9-11ea-8f97-33555950d127.PNG)
[Screenshot 2020-09-26 at 11.16.54.zip](https://github.com/ebaauw/homebridge-hue/files/5286452/Screenshot.2020-09-26.at.11.16.54.zip)

**Comment by ebaauw** [comment]
> the hue app shows everything correct

The screenshot also shows the light as on in The Hue app.

> Is it possible to fix this?

There’s nothing to fix in Homebridge Hue.  The lightstrip is unreachable by the Hue bridge, either because it’s powered down (fix: don’t do that) or because you have connectivity issues in your Zigbee network (fix: add more Zigbee routers, move the lightstrip closer, change Zigbee channel, move away from Wifi, bluetooth, microwave oven, etc).

HomeKit doesn’t provide a settable connected state.  Homebridge Hue sets _Status Fault_ when the bridge reports the light as unreachable, but Apple’s Home app doesn’t show that (fix: use another HomeKit app).

**Comment by iMonZ** [comment]
This is not the point!

The light is working well!
This was intentional but after disconnecting the ZigBee device from the Power it still shows that this device is turned on!
HomeKit support this feature on some devices when there unplugged it shows: this device is unreachable!

**Comment by ebaauw** [comment]
> This was intentional but after disconnecting the ZigBee device from the Power it still shows that this device is turned on!

That’s because the Hue bridge still reports it as on.  I wouldn’t recommend it, but you can set `wallswitch` in config.json to force Homebridge Hue to report the light as off when the bridge marks it as unreachable.

> HomeKit support this feature on some devices when there unplugged it shows: this device is unreachable!

Not quite.  There’s two issues with this:
- HomeKit can show devices as _Not Responding_, but only when they don’t respond to their state being read.  Unfortunately, that state cannot be pushed; it can only be set and cleared when the HomeKit app is refreshing the state.  Hence, I decided to go for _Status Fault_ instead.
- The Hue bridge doesn’t report whether a light has been powered down, only whether it’s still responding to requests.  Depending on the number of devices in your Zigbee network, it might take up to a minute after powering down a light, before the Hue bridge marks it as unreachable.  And powered devices could be marked unreachable due to a hiccup in the Zigbee network.
