### ISSUE TITLE
Samjin (Samsung) Button No Longer Appears in Home App

### ISSUE THREAD

**Issue by fullphat** [ebaauw/homebridge-hue#780]
Strange issue I've only just noticed.  I have a Samjin (Samsung) button working via Conbee II and Homebridge.  It's actually exposed by Conbee as a temperature sensor (resource/23 on my installation) and a button (resource/24).

Both the temperature sensor and button appear fine in the Phoscon app and in Homebridge and even in the Eve app, but only the temperature functionality appears in the iOS Home app - that is the button itself is nowhere to be seen, even though the button itself works fine (by that I mean the scenes I've assigned to it still run).  

This leads me to think there's either a bug in the Home app, or Apple has mangled something in the recent changes to the app as part of iOS 14, rather than an issue in Homebridge, Homebridge-Hue, or Phoscon.

Has anyone else seen this, and is there a possible fix?

Thanks!

**Comment by ebaauw** [comment]
Yes it’s a change in Home on iOS 14: it no longer shows the button tile for accessories that already show a tile for another service.  Not sure if that’s intentional or a bug.

I just changed Homebridge RPi to expose any buttons under a separate accessory.  I hadn’t realised that there are Zigbee wireless switches that expose other services as well.  Could you please attach the debug dump file, so I can have a look at the device?

Homebridge Hue already supports a `splitlight` resourcelink to expose a `/lights` resource for a device as a separate accessory (for wired switches with multiple outputs, wired to lights in different rooms).  Maybe I could abuse that to also indicate that a `/sensors` resource should be exposed as separate accessory.  Alternatively, each wireless switch with another service needs to be whitelisted in the code.

**Comment by fullphat** [comment]
Thanks!

Happy to share debug output - how do I generate it?

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue#debug-dump-file.

**Comment by fullphat** [comment]
Here you go!

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5367164/homebridge-hue.json.gz)

**Comment by fullphat** [comment]
Any update on this? :)

**Comment by ebaauw** [comment]
Not yet; I do have a daytime job...

The dump contains the info I need to fix this.  I'll probably whitelist the device to create a separate accessory for the _Stateless Programmable Switch_.

**Comment by ebaauw** [comment]
Could you try beta v0.11.78-0?

**Comment by fullphat** [comment]
How do I install the beta?

**Comment by ebaauw** [comment]
Use the new _Install Previous Version_ feature in Homebridge Config UI X or manually through `sudo npm -g i homebridge-hue@beta`.

**Comment by fullphat** [comment]
Done!  Looks to have worked although it has removed the button configuration along the way.  Luckily I only have "single press" set to run a single scene. 🙂

**Comment by ebaauw** [comment]
Yeah, the button feature is now exposed as a separate accessory, so HomeKit loses any automations associated with the button in the previous accessory.  I suppose I could expose the temperature feature as separate accessory instead, so the button actions are preserved.  This would cause any automations on the temperature to be lost instead.

**Comment by fullphat** [comment]
Either works for me, but as it's fundamentally a button that just happens to also tell the temperature, makes sense to expose the temperature as a separate accessory. 👍

**Comment by ebaauw** [comment]
Will do that, but will cause another loss of automation for the button when updating to next version.

**Comment by fullphat** [comment]
Perfect.  Makes sense to do it now while still in beta. 👍

**Comment by ebaauw** [comment]
In beta v0.11.78-1.
