### ISSUE TITLE
About RGBCCT control

### ISSUE THREAD

**Issue by leyuansugar** [ebaauw/homebridge-hue#787]
When I use the philips lightstrip plus with the philips hue bridge v2 connect to homekit app.It's work fine.
The link route like this: philips lightstrip plus-> hue bridge v2->homekit app
The link route like this  rgbcct strip->gledoptp controller->hue bridge v2->homebridge-hue->homekit app.
When I just use hue app to control the rgbcct strip,it works fine.The rgb channel and cct channel both work as expected.
But if I use the homekit app to control the rgbcct strip,someting goes wrong.It seems like cct channel has been close,just work as a rgb strip.

**Comment by ebaauw** [comment]
> When I use the philips lightstrip plus with the philips hue bridge v2 connect to homekit app.It's work fine.

I think it actually drives the RGB channels instead of the CCT channels, but you don't see it because of the diffuser.

**Comment by leyuansugar** [comment]
> > When I use the philips lightstrip plus with the philips hue bridge v2 connect to homekit app.It's work fine.
> 
> I think it actually drives the RGB channels instead of the CCT channels, but you don't see it because of the diffuser.

So there is no way to use homebridge hue to control rgbcct's cct channels?All my others smart devices is in apple home app.
But why the philips lightstrip plus(also have cct)  through hue bridge to connect to apple home app it can control the cct channels?
I feel confused.
FYI I'm using the leatest gledopto rgbcct controller GL-C-008P

**Comment by ebaauw** [comment]
The problem is Apple’s Home app.  It doesn’t like devices that expose both _Hue_/_Saturation_ and _Color Temperature_.  So for an _Extended Color Light_, Homebridge Hue only exposes _Hue_ and _Saturation_, just like the Hue bridge.  If you select a colour temperature, Home translates that to _Hue_ and _Saturation_.  This causes Homebridge Hue to set `xy`, which usually causes the light to drive the RGB channels.

To drive the CCT channels, Homebridge Hue needs to set `ct`.  It does so when you change the custome _Color Temperature_ characteristic, which is ignored by Home, but supported by Eve.

I only have one Hue RGB+CCT (Gamut C) bulb and I haven’t mutilated it, so I cannot verify that it actually drives the RGB channels on setting `xy`.  I only have the old RGB (Gamut A) lightstrip.

In theory the Hue firmware could check the `xy` values and drive the CCT channels instead, when the `xy` values fall within the `ct` range.  Afaik, Hue is the only firmware that reports back the corresponding `ct` value when setting `xy` or v.v.

**Comment by leyuansugar** [comment]
> The problem is Apple’s Home app. It doesn’t like devices that expose both _Hue_/_Saturation_ and _Color Temperature_. So for an _Extended Color Light_, Homebridge Hue only exposes _Hue_ and _Saturation_, just like the Hue bridge. If you select a colour temperature, Home translates that to _Hue_ and _Saturation_. This causes Homebridge Hue to set `xy`, which usually causes the light to drive the RGB channels.
> 
> The Hue app, on the other hand sets `ct` when selecting a colour temperature. To drive the CCT channels, Homebridge Hue needs to set `ct`. It does so when you change the custom _Color Temperature_ characteristic, which is ignored by Home, but supported by Eve.
> 
> I only have one Hue RGB+CCT (Gamut C) bulb and I haven’t mutilated it, so I cannot verify that it actually drives the RGB channels on setting `xy`. I only have the old RGB (Gamut A) lightstrip.
> 
> In theory the Hue firmware could check the `xy` values and drive the CCT channels instead, when the `xy` values fall within the `ct` range. Afaik, Hue is the only firmware that reports back the corresponding `ct` value when setting `xy` or v.v.

Thank you very much for your detailed explanation. I think this may also be related to the functional limitations of the third-party devices imposed by hue. If you have Philips lightstrip plus, maybe you can do more testing on this. Anyway, thank you very much for your answer.
