### ISSUE TITLE
Issues with Ikea Fyrtur / Target position isn't shown

### ISSUE THREAD

**Issue by MasterofKungfu9999** [ebaauw/homebridge-hue#807]
I have some trouble with the window covering "fyrtur". in homebridge the target position of the covering is shown right in the logs. But in Homekit the covering says "closing" even if it has already reached its final position. Also the spinner keeps turning.

Thanks for looking at my problem!

**Comment by ebaauw** [comment]
The problem is probably that deCONZ isn't updating the current position (`state.lift`), so Homebridge Hue doesn't update the _Current Position_ and HomeKit continues to report the blind as _Opening_.

See deCONZ issues for the FYRTUR: make sure binding and attribute reporting has been setup.  If they have and the blind still doesn't send any reports, power cycle the blind (remove the battery for 5s).

**Comment by MasterofKungfu9999** [comment]
Ok an where can i do? I'm unsing the phoscon app.

**Comment by ebaauw** [comment]
See any of the deCONZ GitHub issues on this: you need to use the deCONZ GUI.

**Comment by MasterofKungfu9999** [comment]
i have a headless installation on an iobroker system, so it's a little bit difficult the use the GUI. I also installed VNC but it didn't work.

**Comment by ebaauw** [comment]
Please go to the deCONZ Discord or GitHub for issues with deCONZ.
