### ISSUE TITLE
IKEA trådfri drops out of homekit etc

### ISSUE THREAD

**Issue by Pastar243** [ebaauw/homebridge-hue#815]
#### Issue

Hello, 
This is a first for me  since I just start learning, but I can not figure out why I have this issue that have showed up a few weeks ago . 
I run homebridge-hue with a IKEA trådfri light, that works and shows up correct in home bridge but in homekit it just comes up for about 30 seconds (works then) and just disappears after. 
I tried to do everything over from the beginning (which was stupid but then I learned a little more anyhow) but still no change. 

Would like some advice if possible where to start. 

Best regards //
 
#### Log Messages

```
```

**Comment by ebaauw** [comment]
If the light works in Homebridge UI, the issue is not with Homebridge Hue.  Most likely, the communication is failing between Homebridge and your iDevice running HomeKit.  You really need to check with the Homebridge repo, but some general hints:
- Make sure they're on the same subnet, and that IGMP snooping is disabled on your router/switch/access points;
- Make sure no firewall is blocking any traffic;
- Revert to Homebridge v1.1.6 if you're running a more recent beta (see https://github.com/homebridge/homebridge/issues/2681).

**Comment by Pastar243** [comment]
Great. I will look into this. Appreciate your quick answer.  Best regards //
