### ISSUE TITLE
meethue portal: communication error ENETUNREACH

### ISSUE THREAD

**Issue by nickbrown20** [ebaauw/homebridge-hue#85]
Does anyone have any ideas why i get this error when i start my home bridge please?

meethue portal: communication error ENETUNREACH

Cheers,

Nick

**Comment by nickbrown20** [comment]
Restarted the pi and it now reports the error being reported is this

[Hue] meethue portal: communication error ENOTFOUND...

**Comment by ebaauw** [comment]
To discovery any Hue bridges on your local network, homebridge-hue queries the meethue portal on the Internet (at https://www.meethue.com/api/nupnp).  ENETUNREACH means that the network of the meethue portal cannot be reached.  ENOTFOUND means it cannot resolve the hostname (www.meethue.com).

My guess would be a problem with the pi's Internet connection.

**Comment by nickbrown20** [comment]
Ok thanks, both bridges are definitely on the network, which is connected to the web, but I am struggling to connect to both from a phone via 4G. (one generally works). I wonder if its because I can't connect to both bridges at the same time on the hue website portal?

**Comment by ebaauw** [comment]
> both bridges are definitely on the network

What do you mean both bridges?  The Hue bridge and the pi?  Or two Hue bridges?

> which is connected to the web

To double-check: can you access https://www.meethue.com/api/nupnp from a browser running on the pi?

> I am struggling to connect to both from a phone via 4G. (one generally works).

Now you lost me completely.  How are you trying to connect via 4G?  Using a Hue app?  Using HomeKit?  Which one works?  
Note that the errors have nothing to do with the connection between your Hue bridge(s) and the Internet, only with the connection between your pi (running homebridge) and the Internet.

**Comment by nickbrown20** [comment]
Sorry for being unclear.

I have to V2 Hue Hubs now. I can link to them on the meethue website via my hue login, but not at the same time it seems. I can link to both hubs on my network via the hue app on my phone. When I switch to 4G (iPhone) to test the out of home connection, only the hub that is currently linked on the meethue website is reachable.

I've updated the pi tonight from the web and it seemed fine, however I have just checked the pi and you are quite correct, it does not appear to be connected to the web (can't resolve websites), so I will now investigate this. 

Thank you for you help, I really like your plugin.

**Comment by ebaauw** [comment]
> I have to V2 Hue Hubs now. I can link to them on the meethue website via my hue login, but not at the same time it seems.

I've never tried that, but it could very well be a limitation of the meehue website.  It mentions "your bridge" (singular).

> I can link to both hubs on my network via the hue app on my phone. When I switch to 4G (iPhone) to test the out of home connection, only the hub that is currently linked on the meethue website is reachable.

That's to be expected.  There's no direct connection over 4G between the phone and the Hue bridge.  The Hue bridge makes an outgoing connection to the meethue portal.  So does (the Hue app on) the phone.  The meethue portal relays commands from the Hue app on your phone to the Hue bridge.  Most cloud-based IoT services work that way, so you don't have to configure any incoming connections on your Internet router.  
Personally, I prefer a VPN over all these cloud-based solutions (except for HomeKit) to access my home over 4G .  Unlike HomeKit (or any Bonjour-based service), the Hue app works fine over a VPN.

> I've updated the pi tonight from the web and it seemed fine, however I have just checked the pi and you are quite correct, it does not appear to be connected to the web (can't resolve websites), so I will now investigate this.

Sounds like a missing or incorrect DNS and/or default gateway setting.  Is it using DHCP or a static IP configuration?  Did it by change switch from a wired network connection to Wifi because of the update?

By the way, homebridge-hue only uses the Internet connection for bridge discovery.  As it now also discovers your bridges using UPnP on the local network, it will probably just work, despite the meethue portal connection errors.  If you specify the hostnames of your Hue bridges in config.json, homebridge-hue won't even try and discover any bridges.

**Comment by nickbrown20** [comment]
Hi,

Right I have solved this problem, and got both working fine now, needed to reconnect to wifi (despite being connected to ethernet!)

Thank you for you patience and help.

Nick
