### ISSUE TITLE
Hue Tap Switch

### ISSUE THREAD

**Issue by fabvis** [ebaauw/homebridge-hue#86]
hi

i try to use a Hue Tap Switch to turn on/off all my lights (include philips & non-philips lights)... but the trigger scenes won't work...

In Eve.app, i see my tap switch, and his value change (1,2,3 or 4)... 

i've created 2 rules, if value=1 -> scene allON, if value=2 -> scene allOFF... 

but when i push button 1 or 2, default behavior of tap switch are executed.

any idea ?

(sorry, i wrote english like a spanish cow)

**Comment by ebaauw** [comment]
> In Eve.app, i see my tap switch, and his value change (1,2,3 or 4)...

That's good news: homebridge-hue seems to be working correctly.

> i've created 2 rules, if value=1 -> scene allON, if value=2 -> scene allOFF...

I assume you're using the `Output State` value?

> but when i push button 1 or 2, default behavior of tap switch are executed.

I assume this default behaviour is defined in rules on the Hue bridge?  Probably created by the Hue app when you connected the Hue tap.

> any idea ?

Do you have any other HomeKit rules?  Are they executed?  Do you see any errors in the homebridge output?

Note that HomeKit rules are executed on the HomeKit Hub (an Apple TV gen 4 or iPad configured as such), not on your iPhone.  I find that sometimes the synchronisation (over iCloud) of HomeKit rules between your iPhone and AppleTV fails.  What usually works for me is:
- Disable all rules;
- Wait for these changes to appear on another iPhone or iPad (if you don't have one: wait for at least five minutes);
- Re-enable all rules;
- Again, wait for these changes to appear on another iPhone or iPad.

**Comment by fabvis** [comment]
> In Eve.app, i see my tap switch, and his value change (1,2,3 or 4)...
> That's good news: homebridge-hue seems to be working correctly.

yes, no error in log journal

> i've created 2 rules, if value=1 -> scene allON, if value=2 -> scene allOFF...
> I assume you're using the Output State value?

of course, the output value

> but when i push button 1 or 2, default behavior of tap switch are executed.
> I assume this default behaviour is defined in rules on the Hue bridge? Probably created by the Hue app when you connected the Hue tap.

it is that !

> Do you have any other HomeKit rules? Are they executed? Do you see any errors in the homebridge output?

all my rules works perfectly with Siri or homekit apps.
homekit run without error.

i tested to turn off homekit on my aTV4, same thing... :(

i will test to disable all rules, i cross fingers :)

thank you

**Comment by fabvis** [comment]
so,
after disabling all rules, wait for sync, re-enabling, wait for sync, rules work only one time... after that, broken... strange...
another strange thing: sometime, rules sync take 5 secondes, and sometime take 10 minutes...

**Comment by ebaauw** [comment]
> rules work only one time... after that, broken... strange...

For all rules or only for the rules related to the Hue tap?

> another strange thing: sometime, rules sync take 5 secondes, and sometime take 10 minutes...

Yeah, something's definitely broken in the iCloud sync.  Also sometimes, I make a configuration change that get reverted instead of synced to the other devices.

I'm sorry, I don't have an answer, except for the usual reboot all your devices, retry the rules off/sync/rules on/sync, and, as last resort, reset your entire HomeKit configuration.

**Comment by fabvis** [comment]
> For all rules or only for the rules related to the Hue tap?

only rules for hue tap

too many bugs with rules... last night i decide to reset my aTV, and delete my home kit configuration... after a looooong reconfig (i have a lot of accessories), everything work fine, except rules for the tap :-D 

i think the (shitty) Hue.app is the problem

**Comment by ebaauw** [comment]
> everything work fine, except rules for the tap

That could be an issue related to homebridge-hue/homebridge/HAPNodeJS.  To trigger a change to HomeKit, I set the `Output State` value briefly (20ms) to 0, before changing it to the value 1-4 corresponding to the button pressed.  Depending on the speed of the server running homebridge,  the timing might be wrong.  I used to set the value to 0 only when the same button was pressed as last time, but in the preparation for iOS 10.3 (see issue #54), I changed that to every press (which is needed for the programmable switch `Input Event`).  
If you haven't given up yet, I could revert this.  If you would then see a difference between pressing the same button twice (rule not executed) vs pressing two different buttons in a row (rule executed), we know it's related to the timing.  Also, I could create config.json parameter for the delay instead of hardcoding the 20ms, so you would be able to try different values.  
What system are you running homebridge on?  Is it connected to the network over WiFi, power LAN, or ethernet?

> i think the (shitty) Hue.app is the problem

What type of rules have you created using the app?  Are you changing multiple rooms on a single button?  Do you have a v1 (round) or a v2 (square) Hue bridge?  If you could do in Eve an `Identify` on the hue bridge accessory (the one where you can set the heartbeat), homebridge-hue dumps your bridge config to a file.  If you attach the file here, I could have a look.

**Comment by fabvis** [comment]
> What system are you running homebridge on? Is it connected to the network over WiFi, power LAN, or ethernet?
on a Pi3 connected over ethernet  

> What type of rules have you created using the app? 

on my first attempt:
in Hue.app, i left the default behaviors for the 4 tap switch
in Eve.app -if outputvalue = x, start scene x (with philips & non-philips lights), work 1 time, and broken
or in eve.app -if bouton x pressed, start scene x), work 1 time, and broken

second attempt:
in Hue.app, button x dim 1 light to 1%
in Eve.app, if light x = 1%, start scene x
work randomly 

> Do you have a v1 (round) or a v2 (square) Hue bridge?
v2

>  If you could do in Eve an Identify on the hue bridge accessory

Mar 22 18:56:16 PiCam homebridge[539]: [3/22/2017, 6:56:16 PM] [Hue test] Philips hue: identify
Mar 22 18:56:16 PiCam homebridge[539]: [3/22/2017, 6:56:16 PM] [Hue test] Philips hue: dumping masked state to Philips hue.json
Mar 22 18:56:16 PiCam homebridge[539]: [3/22/2017, 6:56:16 PM] [Hue test] cannot create Philips hue.json: error EACCES

uhuh

**Comment by ebaauw** [comment]
> on a Pi3 connected over ethernet
> v2

That makes the hypothesis that the timing in homebridge-hue could be wrong less likely.

> in Eve.app -if outputvalue = x, start scene x (with philips & non-philips lights), work 1 time, and broken
or in eve.app -if bouton x pressed, start scene x, work 1 time, and broken

Did you try pressing a different button and then button x again?

> second attempt:
in Hue.app, button x dim 1 light to 1%
in Eve.app, if light x = 1%, start scene x
work randomly

This definitely has nothing to do with the timing in homebridge-hue.  
Did you (or the scene) set the light to a different brightness, before pressing the button for a second time?  
What Hue app are you using?  I can only select a room and some pre-defined scenes and recipes.  Also note that the Hue bridge uses values 0 to 254 for brightness where HomeKit uses 0% to 100%.  Are you sure the light is reported as 1% in Eve every time you press the button?

> Mar 22 18:56:16 PiCam homebridge[539]: [3/22/2017, 6:56:16 PM] [Hue test] cannot create Philips hue.json: error EACCES

Homebridge-hue tries to create the file in the current directory.  I think, homebridge is started in a directory where it cannot create files.

**Comment by fabvis** [comment]
> Did you try pressing a different button and then button x again?

of course

> What Hue app are you using?

the official hue app for iOS 

>  I think, homebridge is started in a directory where it cannot create files.

i will fixe this after a good night 

thank you for your answers

**Comment by fabvis** [comment]
question to Philips:
opening Hue to Homekit is a good thing, but why opening at 50% ???

**Comment by ebaauw** [comment]
On their developer forum, Philips suggested it was due to Apple's certification process that they cannot expose non-Philips lights.  As for the taps, dimmers, motion sensors, and CLIP sensors: I don't know.  I spend my energy on creating homebridge-hue rather than asking that question ;-)

**Comment by fabvis** [comment]
long live to Homebridge & accessories !

**Comment by ebaauw** [comment]
> That could be an issue related to homebridge-hue/homebridge/HAPNodeJS. To trigger a change to HomeKit, I set the Output State value briefly (20ms) to 0, before changing it to the value 1-4 corresponding to the button pressed. Depending on the speed of the server running homebridge, the timing might be wrong.

Please see issue #88 for more info on this.
