### ISSUE TITLE
Lidl Xmas Light Dimming and Effects on

### ISSUE THREAD

**Issue by jannnfe** [ebaauw/homebridge-hue#860]
Hello,

First of all, many thanks for the quick integration of the fairy lights. I discovered a few problems though.

When I want to dim the light, the colors change. 

It is also very difficult to control the light in HomeKit because the upper part takes up more than half of the scrollable area. See here (click on the image):

<img src="https://user-images.githubusercontent.com/30130742/102412199-73f57100-3ff3-11eb-95df-82c59b486f39.jpeg" width="400" />

The light is also always displayed as "On" because the effects are switched on. Sometimes that irritates. See here:

<img src="https://user-images.githubusercontent.com/30130742/102412632-07c73d00-3ff4-11eb-83fb-8e6d3fc67e9d.jpeg" width="400" />

Maybe I'm the only one who bothers but I wanted to address the whole thing. Maybe it still bothered someone and you can solve the problems mentioned. Many Thanks! :)

**Comment by ebaauw** [comment]
> When I want to dim the light, the colors change.

Hadn't seen that before, but now seeing that as well.  Also when setting `bri` from the API.  I'm afraid this is caused by my latest PR on deCONZ (https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3789), which has been merged with v2.7.1.  What version of deCONZ are you running?

> It is also very difficult to control the light in HomeKit because the upper part takes up more than half of the scrollable area. 

You'll have to take that up with Apple.  You can select _Show as Multiple Tiles_ in the _Settings_, to have Home display a tile per service.

> The light is also always displayed as "On" because the effects are switched on.

_On_ for these services means: enable this colour to the effect.  You can exclude these services from the status by deselecting _Display in Home Status_ under _Settings_, when you're displaying the accessory as multiple tiles.  This change sticks when afterwards displaying the accessory again as single tile.

**Comment by ebaauw** [comment]
Created PR on deCONZ that fixes the dimming: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3953.

**Comment by jannnfe** [comment]
Many thanks for the help. I am very grateful to you. :)
