### ISSUE TITLE
Help EHOSTUNREACH / ECONNREFUSED

### ISSUE THREAD

**Issue by marvelousmo** [ebaauw/homebridge-hue#869]
Hello,

Out of nothing the hue plugin show these errors and I am getting the following messages:

12/28/2020, 7:16:06 PM [Hue] 192.***.***.175: 192.168.8.175:80: cannot connect: EHOSTUNREACH - retrying in 15s
12/28/2020, 7:16:07 PM [Hue] request 1: GET /config
12/28/2020, 7:16:07 PM [Hue] 192.168.8.144:80: cannot connect: ECONNREFUSED
12/28/2020, 7:16:07 PM [Hue] 192.***.***.144: 192.168.8.144:80: cannot connect: ECONNREFUSED - retrying in 15s
12/28/2020, 7:16:10 PM [Hue] request 1: GET /config
12/28/2020, 7:16:10 PM [Hue] 192.168.0.50: timeout after 5 seconds
12/28/2020, 7:16:10 PM [Hue] 192.***.***.50: 192.168.0.50: timeout after 5 seconds - retrying in 15s
12/28/2020, 7:16:11 PM [Hue] request 1: GET /config
12/28/2020, 7:16:11 PM [Hue] 192.168.8.144:80: cannot connect: ECONNREFUSED
12/28/2020, 7:16:11 PM [Hue] 192.***.***.144: 192.168.8.144:80: cannot connect: ECONNREFUSED - retrying in 15s
12/28/2020, 7:16:11 PM [Hue] request 1: GET /config12/28/2020, 7:16:11 PM [Hue]

192.***.***.144 is my harmony hub, but it works fine.
I changed nothing in my setup and restarted everything several times. Hue bridge is online and is connected.
Any help is very much appreciated!

**Comment by ebaauw** [comment]
Homebridge Hue cannot reach your bridges.  Did they get a new IP address?  Did you specify them in config.json under `hosts`, or is Homebridge Hue discovering them automatically?

**Comment by marvelousmo** [comment]
thanks for reaching out. I tried both, assigning a host as well as discovering automatically, no luck. 
I deinstalled the hue plugin and restored from
a backup (the backup was made when the hue plugin kept already crashing) and now it is working again. strange...

**Comment by ebaauw** [comment]
Check the output of `ph discover -v` to see what bridges/gateways Homebridge Hue discovers.  When your ISP shares "your" public IPv4 address with others, you might discover their bridges/gateways as well.  Set `nupnp` to false, to disable discovery using the portals.

When specifying the bridges/gateways under `hosts`, make sure that they have a fixes IP address, either by configuring a status IP address, or by reserving an IP address in your DHCP server, based on the bridge/gateway MAC address.

Of course, the timeouts and unreachable host could also be caused by network issues.
