### ISSUE TITLE
How to delete Sensor?

### ISSUE THREAD

**Issue by Kohle81** [ebaauw/homebridge-hue#870]
I use your plugin for deconz Raspbee and I had a ghost sensor in Homekit, but no active device at deconz. In deconz gui there is no node.

![22F52CBE-291B-481E-A737-5C897D0E96CB](https://user-images.githubusercontent.com/33038709/103242816-e94c3480-4957-11eb-9bd8-28301e12f1c7.png)

The Resource is named /sensors/11

I tried ph -h xxx.xxx.xxx.xx -u yyyyyy lightlink -v , but nothing happened. I noticed later that it is a sensor, but I don‘t know how to delete........

Could you please help me?

**Comment by ebaauw** [comment]
What type of sensor is `/sensors/11`?  It could be a CLIP sensor, in which case you could use `excludeSensorTypes` in config.json to prevent Homebridge Hue from exposing it, see https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

Otherwise, you need to create a resourcelink using the API, to blacklist the individual resource, see https://github.com/ebaauw/homebridge-hue#configuration.

**Comment by Kohle81** [comment]
i was able to delete the sensor.  i happened to download the app “**hue essentials**”.  all active and - I'll call them shadow devices - were displayed here and I could simply delete this inactive sensor.  homebridge restarted and everything is fine.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
