### ISSUE TITLE
Hue Tap switch automation with Eve

### ISSUE THREAD

**Issue by mczac** [ebaauw/homebridge-hue#88]
Hello ebaauw, thanks for your effort with homebridge-hue, great plug-in.
I am trying to automate my Hue lights in the house that I run on multiple bridges.
So far I am doing a simple routine, when the Tap Switch button is pressed I turn one group lights on if they were off, and turn them off if they were on. Automation is made in Eve.app. It works, however very sporadically. I have to press the button several times to get results with no predictable outcome. Eve.app returns the right change of the button, however doesn't trigger the automation via (AppleTV and iPad) immediately, but only every other time, when I press the button several times or press different buttons on Tap switch and press the button 1 again. Can't really nail down the issue.
Eve.app and terminal outputs the button 1 single press, maybe AppleTV/iPad aren't catching up this change? I am Running 10.2.1
I was wondering if I have any issues with network latency or timeout/heartbeat settings? 
Any thoughts?

![terminal](https://cloud.githubusercontent.com/assets/26639163/24276114/51546854-102c-11e7-9aeb-7b9cd83c0429.png)
![config](https://cloud.githubusercontent.com/assets/26639163/24276115/51780930-102c-11e7-911f-0664d159398e.png)
![fullsizerender 2](https://cloud.githubusercontent.com/assets/26639163/24276204/dff20292-102c-11e7-84a3-130bb80f3078.jpg)
![fullsizerender 3](https://cloud.githubusercontent.com/assets/26639163/24276207/e01d2882-102c-11e7-8bb4-ad8fe0edd341.jpg)
![fullsizerender 4](https://cloud.githubusercontent.com/assets/26639163/24276206/e019e852-102c-11e7-820a-a3de2e3e99e1.jpg)
![fullsizerender](https://cloud.githubusercontent.com/assets/26639163/24276205/e015d776-102c-11e7-9441-1ebe9f472379.jpg)

**Comment by ebaauw** [comment]
You don't need the condition for `Enabled`.  When you set it to off, the Hue bridge sensor will not be updated when the tap is pressed.  Otherwise, your setup looks OK.

A 2-second heartrate works for me, for a v2 (square) bridge, running homebridge on a Mac mini server.  From what I hear, this might be challenging for a v1 (round) bridge or when running homebridge on a smaller server, like an older model RaspPi.  Make sure your server is connected by ethernet, not by WiFi nor by power LAN.  I would expect some error messages in the homebridge log, though, when there's latency issues.

Obviously, it takes homebridge-hue up to 2 seconds to take notice of the button press, due to the 2-second polling interval.  If you press the button twice between two polls, only one press will be sent to HomeKit.  
I've had frequent issues with HomeKit rules and I hear even more issues from others.  I haven't seen that rule fires only every other time, though.  I assume you check that the `Output State` and `LastUpdated` characteristics are updated in Eve, every time you press a button?

I only use HomeKit rules to control non-Hue devices from the Hue switches and motion sensors.  All light control is done through rules on the Hue bridge: they react quicker, work when my network is down, and I have a backup (a script to re-create them).

Do you have issues with other HomeKit rules, not based on the Hue tap (or dimmer switch)?  There might, at least in theory, be an issue with the way homebridge-hue handles the switches.  In order to trigger a change to HomeKit, I set the `Output State` to 0 for 20ms, before setting it to the value for the button pressed.  I should have created a parameter in config.sys, but currently the 20ms are hard-coded.

**Comment by mczac** [comment]
Thanks for the response.
It looks like that HomeKit might not pick-up the switch change. If I press the switch several times, sporadically it will execute the scene. However Eve reports every button change correctly with the output change. Somehow HomeKit doesn't recognise the switch change. I tried to press other un-assigned tap switch buttons and held the state for longer, but still scenes don't work everytime.

**Comment by mczac** [comment]
could it be that that 20ms is to short for homekit to pick up the button pressed event? However I am puzzled that I change the state to any other button, keep this state for a few seconds and press button 1 again, and scene doesn't fire

**Comment by mczac** [comment]
you are a star!!!
put 100 for waitTimeSwitch, works like a charm now

**Comment by ebaauw** [comment]
v0.3.12 actually contains two changes:
- Only reset the `Output State` to `0` when the same button is pressed again;
- Use `waitTimeSwitch` parameter from config.sys (between 20ms and 1000ms) as timeout to set the `OutputState` to the value of the button pressed.

**Comment by ebaauw** [comment]
Please note that I plan to deprecate the use of `Output State` in iOS 10.3, when we get HomeKit programmable switches to work, see issue #54.
