### ISSUE TITLE
Open history on Eve App from Contact Sensor

### ISSUE THREAD

**Issue by miquellaboria** [ebaauw/homebridge-hue#912]
Yesterday I bought a contact sensor, linked it to the system and it works perfectly.

My doubt is that in the Eve App, every time it opens it registers the opening 3 times. Am I doing something wrong?

Thank you so much!

![IMG_6F0766C57DFD-1](https://user-images.githubusercontent.com/1266767/105830880-563e0300-5fc6-11eb-99f1-7f1e5bee6a43.jpeg)

**Comment by ebaauw** [comment]
Homebridge Hue should just copy the state as reported by the deCONZ REST API.  You might want to run Homebridge in DEBUG mode to confirm that deCONZ sends six open/close notifications corresponding to the history entries.  If not, please capture and attach a debug log file.

If so, the issue is between the sensor and deCONZ.  What sensor is this?  What cluster does it use?  If _IAS Zone_: does it send restore reports?

**Comment by miquellaboria** [comment]
Today I test in debug mode.

The sensor is Xiaomi (MCCGQ01LM) and I use RaspBee device attached to Raspberry.

**Comment by miquellaboria** [comment]
I know what happened!

It is a garage door and the same door has another sensor, which passes through the same point and the magnet of the other sensor causes it to activate.

Thanks for the help and sorry any incovenience!
