### ISSUE TITLE
Support ELKO ESH 316 Endevender RF

### ISSUE THREAD

**Issue by WTell** [ebaauw/homebridge-hue#922]
#### Issue

Homebridge pull [#3409](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3409) added support for the _ELKO ESH 316 Endevender RF_ (see also [issue #3258](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3258)). The device needs support in homebridge-hue, so that it is not shown as an "unsupported" accessory tile on the front of the Home app.

The device in question is a battery powered rotary dimmer knob with three events: Rotate counter-clockwise ("Dim Down"), rotate clockwise ("Dim Up") and press rotary wheel ("Press"). The device has [pictures and documentation on the manufacturers website](https://proff.elko.no/316-endevender/esh-plus-316-endevender-rf-ph-article2625-3003.html).

#### Suggested implementation

I'm too inexperienced with GitHub to actually make a pull for this, so I'd like to simply propose the following change that I've made and tested to work quite well.

I suggest that [HueSensor.js](https://github.com/ebaauw/homebridge-hue/blob/master/lib/HueSensor.js) is amended to include the following in the same area as the IKEA remotes etc (line 281-924 area): 

```
      } else if (
        this.obj.manufacturername === 'ELKO' &&
        this.obj.modelid === 'ElkoDimmerRemoteZHA'
      ) {
        // ELKO ESH 316 Endevender RF
        this.createLabel(Characteristic.ServiceLabelNamespace.ARABIC_NUMERALS)
        this.createButton(1, 'Press', SINGLE)
        this.createButton(2, 'Dim Up', SINGLE)
        this.createButton(3, 'Dim Down', SINGLE)
        this.type = {
          key: 'buttonevent',
          homekitValue: function (v) { return Math.floor(v / 1000) },
          homekitAction: hkZLLSwitchAction
        }
```

#### Improvement potential

The suggested change works, and all three button events are registered in HomeKit. Firing sequential button events on rotary knob rotation is somewhat nonsensical, though. I don't really know how to address this, as I cannot see any other device that I can steal any approach from, and I cannot find that HomeKit really supports incremental/delta change actions (e.g. "Increase luminosity by X percentage points" etc.) I would be more than happy to have improvements suggested to take this into account.

Cheers!

**Comment by ebaauw** [comment]
I know a couple of devices with a dial or otherwise supporting turning:
1. The old model IKEA Trådfri wireless dimmer (model: `TRADFRI wireless dimmer`).
2. The IKEA Symfonisk controller (model: `SYMFONISK Sound Controller`).
3. The Xiaomi magic cube (model: `lumi.sensor_cube`);
4. The Lutron Aurora (model: `Z3-1BRL`);

The deCONZ REST API reports regular button event values for the IKEA devices and the Lutron Aurora, so there's no special handling in Homebridge Hue.  It reports the rotation angle for the Xiaomi cube, which Homebridge Hue translates to 0° <= _Single Press_ < 45° <= _Double Press_ < 90° <= _Long Press_, with different buttons for clockwise vs counterclockwise turns.

The Hue bridge uses the ZLLRelativeRotary sensor type for the Aurora.  Currently, Homebridge Hue only looks at the direction and maps all values to _Single Press_.  It's been a while since I looked at this device.  Not sure I fully understand the ZLLRelativeRotary; I don't think the Hue bridge exposes it to HomeKit, so no help there.

**Comment by WTell** [comment]
I see, thanks. I understand that Apple isn't positioning HomeKit to handle such delta (incremental/relative) changes in HomeKit – I guess HomeKit is a touch too slow to handle this gracefully, and Apple would rather this be handled internally by the device manufacturers. Still, it'd be nice to get this sort of integration in the future, so that users would be able to control anything with rotary knobs like this – audio volume, colour, fan speed etc.

I would then suggest that the change is implemented as suggested, as it is in line with the solution for `TRADFRI wireless dimmer` and that it, in fact, works.

**Comment by ebaauw** [comment]
In v0.12.22.

**Comment by Krispy44** [comment]
I'm trying to understand the outcome of the recent addition to v0.12.22 you both discussed here. Am I to understand I can not currently incorporate one of these dials for incremental brightness/volume changes?

**Comment by meistermolli** [comment]
Do you use the SYMFONISK Sound Controller to dimm the lights or is it possible to do the sound controller connected to hue bridge to set the volume of the Sonos in Homekit?
