### ISSUE TITLE
Xiaomin motion sensor - temperature missing in HB

### ISSUE THREAD

**Issue by sannc** [ebaauw/homebridge-hue#925]
#### Issue
I have a bunch of Xiaomi (Aqara) motion sensors that provide temperature information. This information is visible in deCONZ, but no temperature is exposed to Homekit. Temperature is already not visible in HB. Motioin and light level are exposed as expected, though.

#### Debug Files
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5960393/homebridge-hue.json.gz)
<img width="785" alt="Bildschirmfoto 2021-02-10 um 19 08 24" src="https://user-images.githubusercontent.com/13866650/107552155-67486000-6bd3-11eb-87da-081c1c1c2c41.png">

**Comment by ebaauw** [comment]
The device doesn’t contain a proper temperature sensor.  Like most Xiaomi devices, it reports the device temperature.  This is a very crude and coarse-grained value, that bears no resemblance to the ambient temperature.  The REST API exposes this as `config.temperature` (instead of `state.temperature` for proper temperature sensors).  Homebridge Hue ignores this by design.

**Comment by sannc** [comment]
Ok … would be a useful information anyway, even if it is not very accurate.
