### ISSUE TITLE
api error 901: Internal error, 951

### ISSUE THREAD

**Issue by b3nsk0** [ebaauw/homebridge-hue#932]
#### Issue

When I try to switch a light in HomeKit I constantly receive the following error:
[22.2.2021, 21:37:30] [Hue] DeConz: request 39: api error 901: Internal error, 951

Running homebridge-hue on a raspberry
DeConz 2.9.3
homebridge 1.3.0
homebridge-hue 0.12.22

Could you please help me fixing this?
Thank you!

**Comment by ebaauw** [comment]
The error means deCONZ is unable to queue another Zigbee command, as the queue has filled.  Most likely, this is caused by issues with the Zigbee network.  Better check the deCONZ log for errors, see https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Zigbee-Error-Codes-in-the-Log.

Could also be that REST API clients are swamping deCONZ with too many requests.  Homebridge Hue should throttle requests, so this shouldn't happen when running only (a single instance of) Homebridge Hue.  Are you running other API clients?  If not (and there's no obvious errors in the deCONZ log), please capture and attach a debug log, see the README.

**Comment by Stefan-83** [comment]
Hi, 
suddenly I have the same issue.
I've also restarted the raspberry running deconz and homebridge, but the error still occurs.
Is there a "reset deconz queue" button or something else?

**Comment by Ghitafjorback** [comment]
Anyone found a solution for this error? I am getting the same errors.

**Comment by Stefan-83** [comment]
ok, there was a second homebridge process running - accidentally.
everything works now
