### ISSUE TITLE
HUE smart plug (visible on HUE Bridge) are not visible in Homebridge. Please advice what to do how to solve this.

### ISSUE THREAD

**Issue by eronnes** [ebaauw/homebridge-hue#945]
#### Issue

My dimmers are recognized, but the smart plug (visible on HUE Bridge) are not visible in Homebridge. Please advice what to do how to solve 
#### Log Messages

```
```

**Comment by ebaauw** [comment]
I don't have the smart plug myself, so I cannot test it.  But I understand it's exposed as `/lights` resource, and the Hue bridge exposes it natively to HomeKit.

The Homebridge UI cannot connect to native HomeKit accessories, only to Homebridge accessories exposed by Homebridge.  To make Homebridge Hue expose plug, you need to set `lights` (to `true`) and clear `nativeHomeKitLights` (set to `false`) in `config.json`.  This will also expose your Hue lights.  To expose only the plug, create a `whitelist` resource links, see the Wiki.  You also might want to create an `outlet` resource link to expose the plug as _Outlet_ instead of _Lightbulb_, see the Wiki.

**Comment by eronnes** [comment]
Thank you very much, this solved my issue. Thanks!

> I don't have the smart plug myself, so I cannot test it. But I understand it's exposed as `/lights` resource, and the Hue bridge exposes it natively to HomeKit.
> 
> The Homebridge UI cannot connect to native HomeKit accessories, only to Homebridge accessories exposed by Homebridge. To make Homebridge Hue expose plug, you need to set `lights` (to `true`) and clear `nativeHomeKitLights` (set to `false`) in `config.json`. This will also expose your Hue lights. To expose only the plug, create a `whitelist` resource links, see the Wiki. You also might want to create an `outlet` resource link to expose the plug as _Outlet_ instead of _Lightbulb_, see the Wiki.
