### ISSUE TITLE
No white temperature available in HomeKit App for all lights

### ISSUE THREAD

**Issue by SmoothMC** [ebaauw/homebridge-hue#97]
Hey again,
there is an new issue for your plugin.
Since i change to your plugin there is no way to change the white key for hue lamps in the HomKit app. Only Color ist available.
But is still available in the Eve app.

Greats

**Comment by ebaauw** [comment]
> Since i change to your plugin there is no way to change the white key for hue lamps in the HomeKit app. 

The iOS Home app doesn't really support colour temperature.  It fakes _Temperature_ in the user interface, using colour (`Hue` and `Saturation`) under the surface.  Consequently, it only shows _Temperature_ for lights that support colour (i.e. _Color Lights_ and _Extended Color Lights_).  Changing plugins doesn't change this.  Are you sure you're looking at the same light?

HomeKit doesn't provide a standard `Color Temperature` characteristic, but several vendors have defined a custom one.  By default, homebridge-hue uses the Aurora Nanoleaf `Color Temperature` characteristic, which exposes the colour temperature in Kelvin.  If you set `"ct": true` in config.json, homebridge-hue uses the v2 Hue bridge `Color Temperature` characteristic that exposes the colour temperature in mired.  
Note that homebridge-hue only exposes `Color Temperature` for lights that have a `ct` attribute, i.e. _Colour Temperature Lights_ and _Extended Color Lights_.  The v2 Hue bridge only exposes `Color Temperature` for _Color Temperature Lights_.  The other plugin, homebridge-philipshue, doesn't expose `Color Temperature` at all.

The iOS Home app does not support any custom characteristic.  Eve supports both `Color Temperature` characteristics and it also fakes colour temperature for lights that support `Hue` and `Saturation`, but not `Color Temperature`.

**Comment by toogle9** [comment]
Hello sir.  So if I understand correctly, there's really no way to control the temperature of the Hue White Ambiance bulbs through the iOS Home app currently, even with homebridge-hue?

I currently am just running with "sensors": true.  I am not doing "lights": true as I have no non-Hue bulbs, and have been hesitant to enable "philipsLights": true, as I am already using the Hue Bridge 2's Homekit functionality.  What actually would happen if I enabled "philipsLights": true, would this duplicate every existing Hue light within the Home app?  And it looks like enabling "ct": true would only apply to non-Hue bulbs.

I hope this is something that Apple addresses in Home/Homekit, I suspect we'll have to wait until iOS 11 to find out since it sounds like 10.3 didn't change.

Thank you for your work!

**Comment by ebaauw** [comment]
>  So if I understand correctly, there's really no way to control the temperature of the Hue White Ambiance bulbs through the iOS Home app currently, even with homebridge-hue?

No, there isn't.  You need another HomeKit app, like Eve.  Note that the v2 Hue bridge already exposes `Color Temperature` for the Philips white ambiance lights.

If you create a HomeKit scene to change the colour temperature in Eve, you could still activate that scene from Home.

> What actually would happen if I enabled "philipsLights": true, would this duplicate every existing Hue light within the Home app?

Yes.  HomeKit won't know that they refer to the same light.

> And it looks like enabling "ct": true would only apply to non-Hue bulbs.

It applies to all lights exposed by homebridge-hue that support colour temperature.
