### ISSUE TITLE
[Request] Identify Profalux/Eveno roller shutters as shutters instead of lights

### ISSUE THREAD

**Issue by piRstone** [ebaauw/homebridge-hue#975]
Hi @ebaauw 👋 

Is there a way to make Homebridge / HomeKit recognize Profalux/Eveno roller shutters as shutters instead of lights?
As @smanar say [in its PR](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3103), it's still complicated to identify them as shutters in deCONZ but is there a way via homebridge-hue to tell Homebridge it's not lights?

<img src="https://user-images.githubusercontent.com/9979764/116001203-93c92100-a5f3-11eb-8cbd-d93b4e3a3c2d.jpeg" alt="Apple Home Capture" height="500" />

If it's not possible for now, I'm planning to create a Homebridge plugin dedicated to Profalux and Eveno shutters using the deCONZ REST API and identify them as [Window Covering](https://developers.homebridge.io/#/service/WindowCovering) accessories (as I didn't found a dedicated Service Type for roller shutters).
It will not done quickly so I prefer asking you first if a quick fix can be done rather than starting a whole project instead 😄

**Comment by ebaauw** [comment]
When it's properly exposed by deCONZ, Homebridge Hue will automatically expose it correctly to HomeKit.  I'm not going to pollute Homebridge Hue, because someone is doing a lousy job integrating the device in deCONZ.

Homebridge Hue requires the `type` to be `"Window covering device"` and uses the (newer) state attributes (`open`, `lift`, and, if applicable, `tilt`).  You might try an older version of Homebridge Hue, from before these attributes were introduced (almost a year ago now, in [v0.11.69](https://github.com/ebaauw/homebridge-hue/releases/tag/v0.11.69)), but I think it will still require the correct `type`.  The NodeJS version shouldn't matter, but I doubt it will work with the latest Homebridge versions.

**Comment by Smanar** [comment]
And this device use light command (set level) and not covering one, so if one day the deconz api stop to support this command for covering (ATM they are deprecated but still used), this device will stop working if it s reconized as covering, so better to use it like a bulb.

**Comment by piRstone** [comment]
Ok I understand the possible issues.
So what are the possibilities for me to make them appear as shutters in Apple Home?
Is my idea to make a Homebridge plugin stupid or to complex, or should I resign to see them as lights anyway?

**Comment by ebaauw** [comment]
I would think it less work to expose them correctly in deCONZ than to create a new Homebridge plugin.  That would also help other API clients.  It would need to be done in C++ instead of in Javascript/NodeJS, though.
