### ISSUE TITLE
latest release published?

### ISSUE THREAD

**Issue by pponce** [ebaauw/homebridge-hue#98]
I'm noticing that when i update homebridge-hue i'm not getting the latest version with the linkButton enhancements:
I've checked the source code for the downloaded plugin and it does not have the recent changes.
i also get this warning message:
config.json: warning: linkButton: ignoring unknown key

**Comment by ebaauw** [comment]
The latest version published on npm is 0.3.17, this is also the latest release.  It doesn't yet support the link button.

The link button support (issue #13) is work in progress but not yet released.  It will be released as v0.4.0, as `Output State` will no longer be provided for the Hue dimmer switch and Hue tap, now that programmable switches work (issue #54).

I had to make some patches to 0.3.15, after starting to work on the link button, so I created a v0.3 branch for this.  v0.3.17 is based on this branch.  I'll merge these changes back into the master branch, before publishing v0.4.0.

I think GitHub shows the latest commit in the master branch (because it's the default?), not the latest release.

**Comment by pponce** [comment]
Ah ok. I get it now. I assumed  all releases were off of master and was looking at the updates to master.
I was reading the documentation in the wiki as well and saw reference to the new linkButton parameter which re-enforced my thought that the latest release included the link button stuff.

Was pulling my hair out wondering why the master code was not being installed. 😄

All makes sense now.
Looking forward to v0.4.0.

**Comment by ebaauw** [comment]
It's out.
