### ISSUE TITLE
ColorLoop error

### ISSUE THREAD

**Issue by Kristian8606** [ebaauw/homebridge-hue#985]
hi i get a weird error when i try to turn on the colorloop for a certain light immax neo.  the other gledopto lights do not have this problem.
![58155566-82E1-4F23-8522-6B427ACF7B4A](https://user-images.githubusercontent.com/34716572/118605611-2312c000-b7bf-11eb-8643-dbb4eba0bec7.png)

**Comment by ebaauw** [comment]
That's the error that deCONZ returns when it cannot queue the Zigbee command to set the colour loop.  As far as I'm aware, it should only return this error, when it's internal queues have been filled (by clients issuing too many requests in too short a time frame), so retrying the request should be the right response.

However in this case, it would seem the error is persistent instead of temporary?  Does Homebridge Hue continue to retry the command until restarted?  I might need to add a counter to limit the number of retries.

That still won't address the cause of the error, though.  Does the light even support colour loop?  Can you set it from the deCONZ GUI?  What value for _Color Capabilities_ does the light report?  Please attach the debug dump file, so I can see how deCONZ exposes the light.

**Comment by Kristian8606** [comment]
> However in this case, it would seem the error is persistent instead of temporary? Does Homebridge Hue continue to retry the command until restarted?

Yes the error persists until I restart Homebridge



> Does the light even support colour loop?

Yes  maintains colorloop.  I have used colorloop quite often in the past for this bulb but I don't know exactly which version is causing this error.

I will add the debug log as soon as I can.

**Comment by Kristian8606** [comment]
Maybe this will be useful

```
"25": {
        "colorcapabilities": 0,
        "ctmax": 65279,
        "ctmin": 0,
        "etag": "95df81efe89c3937dc3e79c722c7ebc0",
        "hascolor": true,
        "lastannounced": null,
        "lastseen": "2021-05-18T18:01Z",
        "manufacturername": "Immax",
        "modelid": "Bulb-RGB+CCT-ZB3.0",
        "name": "Immax Neo",
        "state": {
            "alert": "none",
            "bri": 254,
            "colormode": "xy",
            "ct": 153,
            "effect": "none",
            "hue": 43087,
            "on": true,
            "reachable": true,
            "sat": 250,
            "xy": [
                0.137,
                0.0692
            ]
        },
        "swversion": "2.3",
        "type": "Extended color light",
        "uniqueid": "68:0a:e2:ff:fe:e8:de:cc-01"
    },
```

**Comment by ebaauw** [comment]
It doesn't report any valid value for _Color Capabilities_.  I think the error is caused by a recent change in deCONZ.
