### ISSUE TITLE
 MaxListenersExceededWarning

### ISSUE THREAD

**Issue by Raczka1989** [ebaauw/homebridge-hue#998]
#### Issue
 Error Warning

#### Log Messages

```
```9.7.2021, 17:23:25Hue BridgeERROR(node:20279) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
9.7.2021, 17:23:25Hue BridgeERROR(Use `node --trace-warnings ...` to show where the warning was created)

#### Debug Files
<!-- Please attach homebridge-hue.json.gz, see https://github.com/ebaauw/homebridge-hue#debug-dump-file -->
[log (2).txt](https://github.com/ebaauw/homebridge-hue/files/6792416/log.2.txt)


<!-- Please attach homebridge.log.gz here, see https://github.com/ebaauw/homebridge-hue#debug-log-file -->

**Comment by ebaauw** [comment]
I don't see any attached files?

What are you doing when this message appears?  See also https://github.com/ebaauw/homebridge-hue/issues/868 and Discord.

**Comment by Raczka1989** [comment]
I don‘t make anything, the massage is new wen i have upgraded to Hoobs 4 and i dont know how i can download log files for hue bridge sorry

**Comment by Raczka1989** [comment]
Now my HueBridge Stopt the Service everytime i set a Light to on or off on Apple Homekit and i becom a Log  like this

ERROR<--- Last few GCs --->
17:54:37Hue BridgeERROR[1646:0x539d3e0] 103305867 ms: Mark-sweep 254.2 (258.3) -> 253.7 (258.3) MB, 922.7 / 0.2 ms  (average mu = 0.550, current mu = 0.026) task scavenge might not succeed
17:54:37Hue BridgeERROR[1646:0x539d3e0] 103310002 ms: Mark-sweep 254.2 (256.8) -> 253.8 (257.3) MB, 1742.1 / 0.2 ms  (average mu = 0.567, current mu = 0.579) allocation failure scavenge might not succeed
17:54:37Hue BridgeERROR<--- JS stacktrace --->
17:54:37Hue BridgeERRORFATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap 
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/6797274/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
> Now my HueBridge Stopt the Service everytime i set a Light to on or off on Apple Homekit and i becom a Log like this

The messages do not come from Homebridge Hue, and I have never seen these before.  Google seems to suggest it's the NodeJS process running out of memory.  I would need to see a debug log file to ascertain whether this is caused by Homebridge Hue, but I think I would have gotten more reports if it were.  What version of Hoobs are you running?  v3.3.6 seems broken, see #997.  I don't know Hoobs and cannot support it, see https://github.com/ebaauw/homebridge-hue/issues/694.

> MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit

I did find the cause of this warning, see Discord.  If you re-install Homebridge Hue, it no longer appears.  Note that this is just a warning, not affecting functionality.

**Comment by Raczka1989** [comment]
I have the new Hoobs 4.0.79, I have ReInstall the Plugin now i dont have the massages
